
# This file has been generated at Tue Sep 07 13:59:24 2010

from openalea.core import *


__name__ = 'alinea.adel.macro'

__editable__ = True
__description__ = 'Contains the composite nodes for using adel'
__license__ = 'CECILL'
__url__ = ''
__alias__ = ['adel.macro']
__version__ = '0.0.1'
__authors__ = 'C. Pradal'
__institutes__ = 'CIRAD'
__icon__ = ''


__all__ = ['plot', '_48439632', 'CanT2MTG', 'genMTG', '_48439760', '_48439792', 'animator']



plot = CompositeNodeFactory(name='plot',
                             description='',
                             category='visualisation',
                             doc='',
                             inputs=[  {  'desc': 'Canestra Scene',
      'interface': IDict,
      'name': 'scene(to_plantgl)',
      'value': {  }}],
                             outputs=[{  'interface': None, 'name': 'object(plot3D)'}],
                             elt_factory={  10: ('vplants.plantgl.objects', 'Material'),
   11: ('openalea.color', 'rgb'),
   12: ('vplants.plantgl.objects', 'Material'),
   13: ('openalea.color', 'rgb'),
   14: ('vplants.plantgl.objects', 'Material'),
   15: ('openalea.color', 'rgb'),
   16: ('vplants.plantgl.visualization', 'plot3D'),
   17: ('alinea.adel.io', 'to_plantgl')},
                             elt_connections={  10019396: (11, 0, 10, 1),
   10019408: (17, 0, 16, 0),
   10019420: (16, 0, '__out__', 0),
   10019432: ('__in__', 0, 17, 0),
   10019444: (12, 0, 17, 2),
   10019456: (15, 0, 14, 1),
   10019468: (14, 0, 17, 1),
   10019480: (10, 0, 17, 3),
   10019492: (13, 0, 12, 1)},
                             elt_data={  10: {  'block': False,
          'caption': 'Material',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xae631ec> : "Material"',
          'hide': True,
          'id': 10,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 481.24999999999989,
          'posy': 212.49999999999994,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   11: {  'block': False,
          'caption': 'rgb',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xb40e16c> : "rgb"',
          'hide': True,
          'id': 11,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 509.99999999999983,
          'posy': 97.5,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   12: {  'block': False,
          'caption': 'Material',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xae631ec> : "Material"',
          'hide': True,
          'id': 12,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 305.00000000000006,
          'posy': 212.49999999999983,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   13: {  'block': False,
          'caption': 'rgb',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xb40e16c> : "rgb"',
          'hide': True,
          'id': 13,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 337.50000000000006,
          'posy': 107.49999999999994,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   14: {  'block': False,
          'caption': 'Material',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xae631ec> : "Material"',
          'hide': True,
          'id': 14,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 127.49999999999994,
          'posy': 207.49999999999997,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   15: {  'block': False,
          'caption': 'rgb',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xb40e16c> : "rgb"',
          'hide': True,
          'id': 15,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 191.24999999999994,
          'posy': 118.74999999999997,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   16: {  'block': False,
          'caption': 'plot3D',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xb047e2c> : "plot3D"',
          'hide': True,
          'id': 16,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 18.75,
          'posy': 365.0,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   17: {  'block': False,
          'caption': 'to_plantgl',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xacb5eec> : "to_plantgl"',
          'hide': True,
          'id': 17,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 1.25,
          'posy': 289.99999999999994,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 255.62499999999991,
                'posy': 37.5,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 255.62499999999991,
                 'posy': 425.0,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  10: [  (0, "''"),
          (2, '2.0'),
          (3, 'Color3(0,0,0)'),
          (4, '1.0'),
          (5, 'Color3(40,40,40)'),
          (6, '0.0')],
   11: [(0, '(170, 85, 0)')],
   12: [  (0, "''"),
          (2, '2.0'),
          (3, 'Color3(0,0,0)'),
          (4, '1.0'),
          (5, '(0, 0, 0)'),
          (6, '0.0')],
   13: [(0, '(0, 130, 0)')],
   14: [  (0, "''"),
          (2, '2.0'),
          (3, 'Color3(0,0,0)'),
          (4, '1.0'),
          (5, 'Color3(40,40,40)'),
          (6, '0.0')],
   15: [(0, '(0, 180, 0)')],
   16: [],
   17: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  10: {'position': [481.24999999999989, 212.49999999999994], 'userColor': None, 'useUserColor': False},
   11: {'position': [509.99999999999983, 97.5], 'userColor': None, 'useUserColor': False},
   12: {'position': [305.00000000000006, 212.49999999999983], 'userColor': None, 'useUserColor': False},
   13: {'position': [337.50000000000006, 107.49999999999994], 'userColor': None, 'useUserColor': False},
   14: {'position': [127.49999999999994, 207.49999999999997], 'userColor': None, 'useUserColor': False},
   15: {'position': [191.24999999999994, 118.74999999999997], 'userColor': None, 'useUserColor': False},
   16: {'position': [18.75, 365.0], 'userColor': None, 'useUserColor': False},
   17: {'position': [1.25, 289.99999999999994], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [255.62499999999991, 37.5], 'userColor': None, 'useUserColor': False},
   '__out__': {'position': [255.62499999999991, 425.0], 'userColor': None, 'useUserColor': False}},
                             lazy=True,
                             )




_48439632 = CompositeNodeFactory(name='get leaf',
                             description='Select a leaf element from a database',
                             category='composite',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': IDict, 'name': 'leaves', 'value': None},
   {  'desc': '', 'interface': IInt, 'name': 'index', 'value': None},
   {  'desc': '', 'interface': IInt, 'name': 'rank', 'value': None}],
                             outputs=[{  'desc': '', 'interface': ISequence, 'name': 'leaf'}],
                             elt_factory={  4: ('catalog.python', 'keys'),
   5: ('catalog.python', 'getitem'),
   6: ('catalog.python', 'getitem'),
   9: ('catalog.python', 'getitem')},
                             elt_connections={  9723328: ('__in__', 0, 4, 0),
   9723352: (9, 0, '__out__', 0),
   9723364: ('__in__', 0, 6, 0),
   9723412: ('__in__', 1, 9, 1),
   9723436: (6, 0, 9, 0),
   9723448: (5, 0, 6, 1),
   9723460: ('__in__', 2, 5, 1),
   9723508: (4, 0, 5, 0)},
                             elt_data={  4: {  'caption': 'keys',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 58.298472637962163,
         'posy': 96.693326144007187,
         'priority': 0},
   5: {  'caption': 'getitem',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 149.02208432705947,
         'posy': 134.34816552489417,
         'priority': 0},
   6: {  'caption': 'getitem',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': -99.012505201873864,
         'posy': 165.14184860026398,
         'priority': 0},
   9: {  'caption': 'getitem',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': -39.721420282628912,
         'posy': 303.8429692126449,
         'priority': 0},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set(),
                 'posx': -21.25,
                 'posy': 380.0,
                 'priority': 0}},
                             elt_value={  4: [], 5: [], 6: [], 9: [], '__in__': [], '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




CanT2MTG = CompositeNodeFactory(name='CanT2MTG',
                             description='generate CanMTG from R canopy table',
                             category='composite',
                             doc='',
                             inputs=[  {  'desc': 'database',
      'interface': IDict,
      'name': 'leaves(symbols)',
      'value': {  }},
   {  'desc': 'random seed',
      'interface': IInt,
      'name': 'seed(symbols)',
      'value': None},
   {  'desc': 'R Dataframe representing the canopy',
      'interface': None,
      'name': 'R Canopy Table(genString)'}],
                             outputs=[{  'desc': '', 'interface': IData, 'name': 'CanMTG(CanMTGInterpreter)'}],
                             elt_factory={  38: ('alinea.adel.geometry', 'symbols'),
   39: ('alinea.adel.wheat', 'CanMTGInterpreter'),
   40: ('alinea.adel.simulation', 'genString')},
                             elt_connections={  10018968: (38, 0, 39, 0),
   10018980: (40, 0, 39, 1),
   60318560: ('__in__', 1, 38, 1),
   60720112: (39, 0, '__out__', 0),
   60806272: ('__in__', 0, 38, 0),
   61872912: ('__in__', 2, 40, 0)},
                             elt_data={  38: {  'block': False,
          'caption': 'symbols',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 698.60330039042253,
          'posy': -4.3658203619890621,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   39: {  'block': False,
          'caption': 'CanMTGInterpreter',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 721.59726893374238,
          'posy': 78.324074126769787,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   40: {  'block': False,
          'caption': 'genString',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 791.36729250051121,
          'posy': -4.406499152331083,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None}},
                             elt_value={  38: [(1, 'None')], 39: [], 40: []},
                             elt_ad_hoc={  38: {  'position': [698.60330039042253, -4.3658203619890621],
          'useUserColor': False,
          'userColor': None},
   39: {  'position': [721.59726893374238, 78.324074126769787],
          'useUserColor': False,
          'userColor': None},
   40: {  'position': [791.36729250051121, -4.406499152331083],
          'useUserColor': False,
          'userColor': None}},
                             lazy=True,
                             )




genMTG = CompositeNodeFactory(name='genMTG',
                             description='Generate an MTG  representing the scene with ADELR ',
                             category='composite',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': None, 'name': 'Leaves db', 'value': None},
   {  'desc': '', 'interface': None, 'name': 'development Rdb', 'value': None},
   {  'desc': '', 'interface': None, 'name': 'Axe geometry (R)', 'value': None},
   {  'desc': '', 'interface': None, 'name': 'Leaf Geometry (R)', 'value': None},
   {  'desc': '', 'interface': IInt, 'name': 'Number of plants', 'value': 1},
   {  'desc': '',
      'interface': None,
      'name': 'Plant positions',
      'value': [(0, 0, 0)]},
   {  'desc': '', 'interface': IFloat, 'name': 'Date (dd)', 'value': 1000},
   {  'desc': '', 'interface': IInt, 'name': 'random seed', 'value': None}],
                             outputs=[{  'desc': '', 'interface': None, 'name': 'CanMTG'}],
                             elt_factory={  2: ('alinea.adel.wheat', 'CanMTGInterpreter'),
   3: ('openalea.python method', 'getitem'),
   4: ('alinea.adel.parameterisation', 'setAdel'),
   7: ('alinea.adel.geometry', 'symbols'),
   8: ('alinea.adel.simulation', 'RunAdel'),
   9: ('openalea.data structure', 'int'),
   10: ('alinea.adel.stand', 'CanMTGPlanter')},
                             elt_connections={  154307904: ('__in__', 7, 7, 1),
   154307916: (4, 0, 8, 1),
   154307928: (7, 0, 2, 0),
   154307940: ('__in__', 7, 4, 4),
   154307952: ('__in__', 0, 7, 0),
   154307964: (10, 0, '__out__', 0),
   154307976: ('__in__', 3, 4, 1),
   154307988: (2, 0, 10, 0),
   154308000: ('__in__', 4, 4, 3),
   154308012: (9, 0, 3, 1),
   154308024: ('__in__', 1, 4, 0),
   154308036: ('__in__', 6, 8, 0),
   154308048: (8, 0, 3, 0),
   154308060: (3, 0, 2, 1),
   154308072: ('__in__', 2, 4, 2),
   154308084: ('__in__', 5, 10, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'CanMTGInterpreter',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 255.00000000000003,
         'posy': 248.75000000000006,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'getitem',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 318.75000000000006,
         'posy': 161.25000000000003,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'setAdel',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 239.99999999999983,
         'posy': -63.75,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'symbols',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 53.750000000000114,
         'posy': -76.249999999999957,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'RunAdel',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 303.74999999999983,
         'posy': 98.749999999999915,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': '0',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 393.74999999999983,
         'posy': 100.00000000000003,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': 'CanMTGPlanter',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 621.24999999999989,
          'posy': 359.99999999999994,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 337.5,
                'posy': -136.24999999999994,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 337.5,
                 'posy': 419.99999999999994,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [],
   3: [],
   4: [],
   7: [],
   8: [],
   9: [(0, '0')],
   10: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [255.00000000000003, 248.75000000000006],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [318.75000000000006, 161.25000000000003],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [239.99999999999983, -63.75],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [46.734625668449247, 247.20588235294122], 'text': ''},
   7: {  'position': [53.750000000000114, -76.249999999999957],
         'useUserColor': False,
         'userColor': None},
   8: {  'position': [303.74999999999983, 98.749999999999915],
         'useUserColor': False,
         'userColor': None},
   9: {  'position': [393.74999999999983, 100.00000000000003],
         'useUserColor': False,
         'userColor': None},
   10: {  'position': [621.24999999999989, 359.99999999999994],
          'useUserColor': False,
          'userColor': None},
   '__in__': {  'position': [337.5, -136.24999999999994],
                'useUserColor': False,
                'userColor': None},
   '__out__': {  'position': [337.5, 419.99999999999994],
                 'useUserColor': False,
                 'userColor': None}},
                             lazy=True,
                             )




_48439760 = CompositeNodeFactory(name='leaves wheat (soissons99)',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[{  'desc': '', 'interface': IInt, 'name': 'nb_points', 'value': 6}],
                             outputs=[{  'desc': '', 'interface': IDict, 'name': 'leaves'}],
                             elt_factory={  3: ('alinea.adel.wheat.data', 'SRSo.RData'),
   4: ('alinea.adel.wheat', 'extract_leaves'),
   5: ('alinea.adel.fitting', 'fit leaves'),
   6: ('alinea.adel.wheat.data', 'So99.RData')},
                             elt_connections={  151150028: (5, 0, '__out__', 0),
   151150040: (6, 0, 4, 0),
   151150052: ('__in__', 0, 5, 1),
   151150064: (3, 0, 4, 1),
   151150076: (4, 0, 5, 0)},
                             elt_data={  3: {  'block': False,
         'caption': 'SRSo.RData',
         'delay': 0,
         'factory': '<openalea.core.data.DataFactory object at 0xa9db44c> : "SRSo.RData"',
         'hide': True,
         'id': 3,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': -805.1859701093282,
         'posy': -195.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'extract_leaves',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xa860bec> : "extract_leaves"',
         'hide': True,
         'id': 4,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -882.35059692176594,
         'posy': -135.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'fit leaves',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xa8ec1cc> : "fit leaves"',
         'hide': True,
         'id': 5,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': -848.27537289033944,
         'posy': -58.216267232708788,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'So99.RData',
         'delay': 0,
         'factory': '<openalea.core.data.DataFactory object at 0xa9db40c> : "So99.RData"',
         'hide': True,
         'id': 6,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': -927.0,
         'posy': -195.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 1,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': -798.0,
                'posy': -269.5,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 0,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': -792.5,
                 'posy': 0.5,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  3: [  (0, 'PackageData(alinea.adel.wheat.data, SRSo.RData)'),
         (1, 'None'),
         (2, 'None')],
   4: [],
   5: [],
   6: [  (0, 'PackageData(alinea.adel.wheat.data, So99.RData)'),
         (1, 'None'),
         (2, 'None')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  3: {  'position': [-805.1859701093282, -195.0],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [-882.35059692176594, -135.0],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [-848.27537289033944, -58.216267232708788],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [-927.0, -195.0], 'useUserColor': False, 'userColor': None},
   '__in__': {  'position': [-798.0, -269.5],
                'useUserColor': False,
                'userColor': None},
   '__out__': {  'position': [-792.5, 0.5],
                 'useUserColor': False,
                 'userColor': None}},
                             lazy=True,
                             )




_48439792 = CompositeNodeFactory(name='texture plot',
                             description='Plot adel canMTG with texture',
                             category='visualisation',
                             doc='',
                             inputs=[  {  'desc': 'Canestra Scene',
      'interface': IDict,
      'name': 'scene(to_plantgl)',
      'value': {  }},
   {  'desc': '', 'interface': IFileStr, 'name': 'Leaf Texture', 'value': None},
   {  'desc': '', 'interface': IFileStr, 'name': 'Stem Texture', 'value': None},
   {  'desc': '',
      'interface': IFileStr,
      'name': 'Soil(+senescent) tex',
      'value': None}],
                             outputs=[{  'desc': '', 'interface': None, 'name': 'object(plot3D)'}],
                             elt_factory={  11: ('vplants.plantgl.objects', 'ImageTexture'),
   13: ('vplants.plantgl.objects', 'ImageTexture'),
   15: ('vplants.plantgl.objects', 'ImageTexture'),
   16: ('vplants.plantgl.visualization', 'plot3D'),
   17: ('alinea.adel.io', 'to_plantgl')},
                             elt_connections={  9855204: ('__in__', 3, 15, 4),
   9855216: ('__in__', 2, 13, 4),
   9855228: ('__in__', 1, 11, 4),
   9855240: (16, 0, '__out__', 0),
   9855252: (13, 0, 17, 2),
   9855264: (17, 0, 16, 0),
   9855276: (11, 0, 17, 1),
   9855288: (15, 0, 17, 3),
   9855300: ('__in__', 0, 17, 0)},
                             elt_data={  11: {  'block': False,
          'caption': 'ImageTexture',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 48.75,
          'posy': 143.75,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'ImageTexture',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 282.5,
          'posy': 145.0,
          'priority': 0,
          'user_application': None},
   15: {  'block': False,
          'caption': 'ImageTexture',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 583.75,
          'posy': 156.25,
          'priority': 0,
          'user_application': None},
   16: {  'block': False,
          'caption': 'plot3D',
          'hide': True,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 18.75,
          'posy': 365.0,
          'priority': 0,
          'user_application': None},
   17: {  'block': False,
          'caption': 'to_plantgl',
          'hide': True,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 1.25,
          'posy': 289.99999999999994,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 31.25,
                 'posy': 430.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  11: [  (0, "''"),
          (1, 'None'),
          (2, 'None'),
          (3, 'None'),
          (5, 'None'),
          (6, 'None'),
          (7, 'None'),
          (8, 'None')],
   13: [  (0, "''"),
          (1, 'None'),
          (2, 'None'),
          (3, 'None'),
          (5, 'None'),
          (6, 'None'),
          (7, 'None'),
          (8, 'None')],
   15: [  (0, "''"),
          (1, 'None'),
          (2, 'None'),
          (3, 'None'),
          (5, 'None'),
          (6, 'None'),
          (7, 'None'),
          (8, 'None')],
   16: [],
   17: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




animator = CompositeNodeFactory(name='animator',
                             description='animate a visualisation dataflow that respond to x incrementation',
                             category='visualisation',
                             doc='',
                             inputs=[  {  'desc': '',
      'interface': None,
      'name': 'Data flow ploting function',
      'value': None},
   {  'desc': '', 'interface': IInt, 'name': 'start', 'value': 0},
   {  'desc': '', 'interface': IInt, 'name': 'end', 'value': 100},
   {  'desc': '', 'interface': IInt, 'name': 'step', 'value': 10},
   {  'desc': '', 'interface': None, 'name': 'x', 'value': None}],
                             outputs=[{  'desc': '', 'interface': None, 'name': 'OUT1'}],
                             elt_factory={  7: ('openalea.function operator', 'map'),
   9: ('openalea.flow control', 'X'),
   10: ('openalea.function operator', 'map'),
   11: ('alinea.adel.macro', 'plot')},
                             elt_connections={  9988868: (10, 0, 7, 1),
   9988880: (11, 0, 7, 0),
   9988892: (9, 0, 11, 0),
   9988940: ('__in__', 1, 10, 1),
   9989000: (7, 0, '__out__', 0),
   9989012: ('__in__', 0, 10, 0)},
                             elt_data={  7: {  'block': False,
         'caption': 'map',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 612.10495189464064,
         'posy': 683.71574154664245,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'X2',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 566.25,
         'posy': 557.45198023636965,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'map',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 653.60497822630418,
          'posy': 552.5,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'plot',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 580.70188903923508,
          'posy': 615.86298175614502,
          'priority': 0,
          'user_application': False},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 652.5,
                'posy': 475.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 450.0,
                 'posy': 740.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  7: [], 9: [(0, "'x'")], 10: [], 11: [], '__in__': [], '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




