
# This file has been generated at Mon Dec 03 16:46:24 2012

from openalea.core import *


__name__ = 'alinea.adel.macro'

__editable__ = True
__description__ = 'Contains the composite nodes for using adel'
__license__ = 'CECILL'
__url__ = ''
__alias__ = ['adel.macro']
__version__ = '0.0.1'
__authors__ = 'C. Pradal'
__institutes__ = 'CIRAD'
__icon__ = ''


__all__ = ['plot', 'CanT2MTG', '_139071216', 'CaribuZenithParStr', 'RunLpy', 'genMTG', '_139071248', '_139071376', '_356011472', 'animator']



plot = CompositeNodeFactory(name='plot',
                             description='',
                             category='visualisation',
                             doc='',
                             inputs=[  {  'desc': 'Canestra Scene',
      'interface': IDict,
      'name': 'scene(to_plantgl)',
      'value': {  }}],
                             outputs=[{  'interface': None, 'name': 'object(plot3D)'}],
                             elt_factory={  10: ('vplants.plantgl.objects', 'Material'),
   11: ('openalea.color', 'rgb'),
   12: ('vplants.plantgl.objects', 'Material'),
   13: ('openalea.color', 'rgb'),
   14: ('vplants.plantgl.objects', 'Material'),
   15: ('openalea.color', 'rgb'),
   16: ('vplants.plantgl.visualization', 'plot3D'),
   17: ('alinea.adel.io', 'to_plantgl')},
                             elt_connections={  10019396: (11, 0, 10, 1),
   10019408: (17, 0, 16, 0),
   10019420: (16, 0, '__out__', 0),
   10019432: ('__in__', 0, 17, 0),
   10019444: (12, 0, 17, 2),
   10019456: (15, 0, 14, 1),
   10019468: (14, 0, 17, 1),
   10019480: (10, 0, 17, 3),
   10019492: (13, 0, 12, 1)},
                             elt_data={  10: {  'block': False,
          'caption': 'Material',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xae631ec> : "Material"',
          'hide': True,
          'id': 10,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 481.2499999999999,
          'posy': 212.49999999999994,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   11: {  'block': False,
          'caption': 'rgb',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xb40e16c> : "rgb"',
          'hide': True,
          'id': 11,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 509.99999999999983,
          'posy': 97.5,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   12: {  'block': False,
          'caption': 'Material',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xae631ec> : "Material"',
          'hide': True,
          'id': 12,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 305.00000000000006,
          'posy': 212.49999999999983,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   13: {  'block': False,
          'caption': 'rgb',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xb40e16c> : "rgb"',
          'hide': True,
          'id': 13,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 337.50000000000006,
          'posy': 107.49999999999994,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   14: {  'block': False,
          'caption': 'Material',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xae631ec> : "Material"',
          'hide': True,
          'id': 14,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 127.49999999999994,
          'posy': 207.49999999999997,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   15: {  'block': False,
          'caption': 'rgb',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xb40e16c> : "rgb"',
          'hide': True,
          'id': 15,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 191.24999999999994,
          'posy': 118.74999999999997,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   16: {  'block': False,
          'caption': 'plot3D',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xb047e2c> : "plot3D"',
          'hide': True,
          'id': 16,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 18.75,
          'posy': 365.0,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   17: {  'block': False,
          'caption': 'to_plantgl',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xacb5eec> : "to_plantgl"',
          'hide': True,
          'id': 17,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 1.25,
          'posy': 289.99999999999994,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 255.62499999999991,
                'posy': 37.5,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 255.62499999999991,
                 'posy': 425.0,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  10: [  (0, "''"),
          (2, '2.0'),
          (3, 'Color3(0,0,0)'),
          (4, '1.0'),
          (5, 'Color3(40,40,40)'),
          (6, '0.0')],
   11: [(0, '(170, 85, 0)')],
   12: [  (0, "''"),
          (2, '2.0'),
          (3, 'Color3(0,0,0)'),
          (4, '1.0'),
          (5, '(0, 0, 0)'),
          (6, '0.0')],
   13: [(0, '(0, 130, 0)')],
   14: [  (0, "''"),
          (2, '2.0'),
          (3, 'Color3(0,0,0)'),
          (4, '1.0'),
          (5, 'Color3(40,40,40)'),
          (6, '0.0')],
   15: [(0, '(0, 180, 0)')],
   16: [],
   17: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  10: {  'position': [481.2499999999999, 212.49999999999994],
          'useUserColor': False,
          'userColor': None},
   11: {  'position': [509.99999999999983, 97.5],
          'useUserColor': False,
          'userColor': None},
   12: {  'position': [305.00000000000006, 212.49999999999983],
          'useUserColor': False,
          'userColor': None},
   13: {  'position': [337.50000000000006, 107.49999999999994],
          'useUserColor': False,
          'userColor': None},
   14: {  'position': [127.49999999999994, 207.49999999999997],
          'useUserColor': False,
          'userColor': None},
   15: {  'position': [191.24999999999994, 118.74999999999997],
          'useUserColor': False,
          'userColor': None},
   16: {  'position': [18.75, 365.0], 'useUserColor': False, 'userColor': None},
   17: {  'position': [1.25, 289.99999999999994],
          'useUserColor': False,
          'userColor': None},
   '__in__': {  'position': [255.62499999999991, 37.5],
                'useUserColor': False,
                'userColor': None},
   '__out__': {  'position': [255.62499999999991, 425.0],
                 'useUserColor': False,
                 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




CanT2MTG = CompositeNodeFactory(name='CanT2MTG',
                             description='generate CanMTG from R canopy table',
                             category='composite',
                             doc='',
                             inputs=[  {  'desc': 'database',
      'interface': IDict,
      'name': 'leaves(symbols)',
      'value': {  }},
   {  'desc': 'random seed',
      'interface': IInt,
      'name': 'seed(symbols)',
      'value': None},
   {  'desc': 'R Dataframe representing the canopy',
      'interface': None,
      'name': 'R Canopy Table(genString)'}],
                             outputs=[{  'desc': '', 'interface': IData, 'name': 'CanMTG(CanMTGInterpreter)'}],
                             elt_factory={  38: ('alinea.adel.geometry', 'symbols'),
   39: ('alinea.adel.wheat', 'CanMTGInterpreter'),
   40: ('alinea.adel.simulation', 'genString')},
                             elt_connections={  39203688: ('__in__', 2, 40, 0),
   39203712: (38, 0, 39, 0),
   39203736: (39, 0, '__out__', 0),
   39203760: (40, 0, 39, 1),
   39203784: ('__in__', 0, 38, 0),
   39203808: ('__in__', 1, 38, 1)},
                             elt_data={  38: {  'block': False,
          'caption': 'symbols',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0x7fdf9445eed0> : "symbols"',
          'hide': True,
          'id': 38,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 698.6033003904225,
          'posy': -4.365820361989062,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   39: {  'block': False,
          'caption': 'CanMTGInterpreter',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0x4f3c090> : "CanMTGInterpreter"',
          'hide': True,
          'id': 39,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 721.5972689337424,
          'posy': 78.32407412676979,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   40: {  'block': False,
          'caption': 'genString',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0x472cd90> : "genString"',
          'hide': True,
          'id': 40,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 791.3672925005112,
          'posy': -4.406499152331083,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 25.0,
                'posy': -56.5,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 37.5,
                 'posy': 33.5,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  38: [(2, 'False')], 39: [], 40: [], '__in__': [], '__out__': []},
                             elt_ad_hoc={  38: {  'position': [698.6033003904225, -4.365820361989062],
          'useUserColor': False,
          'userColor': None},
   39: {  'position': [721.5972689337424, 78.32407412676979],
          'useUserColor': False,
          'userColor': None},
   40: {  'position': [791.3672925005112, -4.406499152331083],
          'useUserColor': False,
          'userColor': None},
   '__in__': {  'position': [25.0, -56.5],
                'useUserColor': False,
                'userColor': None},
   '__out__': {  'position': [37.5, 33.5],
                 'useUserColor': False,
                 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




_139071216 = CompositeNodeFactory(name='leaves wheat (soissons99)',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[{  'desc': '', 'interface': IInt, 'name': 'nb_points', 'value': 6}],
                             outputs=[{  'desc': '', 'interface': IDict, 'name': 'leaves'}],
                             elt_factory={  3: ('alinea.adel.wheat.data', 'SRSo.RData'),
   4: ('alinea.adel.wheat', 'extract_leaves'),
   5: ('alinea.adel.fitting', 'fit leaves'),
   6: ('alinea.adel.wheat.data', 'So99.RData')},
                             elt_connections={  151150028: (5, 0, '__out__', 0),
   151150040: (6, 0, 4, 0),
   151150052: ('__in__', 0, 5, 1),
   151150064: (3, 0, 4, 1),
   151150076: (4, 0, 5, 0)},
                             elt_data={  3: {  'block': False,
         'caption': 'SRSo.RData',
         'delay': 0,
         'factory': '<openalea.core.data.DataFactory object at 0xa9db44c> : "SRSo.RData"',
         'hide': True,
         'id': 3,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': -805.1859701093282,
         'posy': -195.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'extract_leaves',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xa860bec> : "extract_leaves"',
         'hide': True,
         'id': 4,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -882.3505969217659,
         'posy': -135.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'fit leaves',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xa8ec1cc> : "fit leaves"',
         'hide': True,
         'id': 5,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': -848.2753728903394,
         'posy': -58.21626723270879,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'So99.RData',
         'delay': 0,
         'factory': '<openalea.core.data.DataFactory object at 0xa9db40c> : "So99.RData"',
         'hide': True,
         'id': 6,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': -927.0,
         'posy': -195.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 1,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': -798.0,
                'posy': -269.5,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 0,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': -792.5,
                 'posy': 0.5,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  3: [  (0, 'PackageData(alinea.adel.wheat.data, SRSo.RData)'),
         (1, 'None'),
         (2, 'None')],
   4: [],
   5: [],
   6: [  (0, 'PackageData(alinea.adel.wheat.data, So99.RData)'),
         (1, 'None'),
         (2, 'None')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  3: {  'position': [-805.1859701093282, -195.0],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [-882.3505969217659, -135.0],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [-848.2753728903394, -58.21626723270879],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [-927.0, -195.0], 'useUserColor': False, 'userColor': None},
   '__in__': {  'position': [-798.0, -269.5],
                'useUserColor': False,
                'userColor': None},
   '__out__': {  'position': [-792.5, 0.5],
                 'useUserColor': False,
                 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




CaribuZenithParStr = CompositeNodeFactory(name='CaribuZenithParStr',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': IData, 'name': 'CanScene', 'value': None},
   {  'desc': '', 'interface': ISequence, 'name': 'Pattern', 'value': None}],
                             outputs=[  {  'desc': '', 'interface': None, 'name': 'CaribuScene'},
   {  'desc': '', 'interface': None, 'name': 'CaribuOutDict'}],
                             elt_factory={  3: ('alinea.caribu', 'Caribu'),
   6: ('openalea.file', 'write'),
   7: ('alinea.caribu', 'FileCaribuScene'),
   8: ('openalea.file', 'tmpnam'),
   9: ('alinea.caribu.data', 'par.opt'),
   10: ('alinea.caribu.data', 'zenith.light')},
                             elt_connections={  35910456: (9, 0, 7, 3),
   35910480: (8, 0, 6, 1),
   35910504: ('__in__', 0, 6, 0),
   35910528: (10, 0, 7, 1),
   35910552: (6, 0, 7, 0),
   35910576: (7, 0, 3, 0),
   35910600: (3, 0, '__out__', 0),
   35910624: (3, 1, '__out__', 1)},
                             elt_data={  3: {  'block': False,
         'caption': 'Caribu',
         'delay': 0,
         'factory': '<openalea.core.compositenode.CompositeNodeFactory object at 0x599db10> : "Caribu"',
         'hide': True,
         'id': 3,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 192.5,
         'posy': 256.25,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'write',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x4b323d0> : "write"',
         'hide': True,
         'id': 6,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 67.5,
         'posy': 227.5,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'FileCaribuScene',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x599d6d0> : "FileCaribuScene"',
         'hide': True,
         'id': 7,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 167.5,
         'posy': 170.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'tmpnam',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x4b32750> : "tmpnam"',
         'hide': True,
         'id': 8,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 11.25,
         'posy': 120.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': 'par.opt',
         'delay': 0,
         'factory': '<openalea.core.data.DataFactory object at 0x4ceab50> : "par.opt"',
         'hide': True,
         'id': 9,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 301.25,
         'posy': 7.5,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': 'zenith.light',
          'delay': 0,
          'factory': '<openalea.core.data.DataFactory object at 0x4cead50> : "zenith.light"',
          'hide': True,
          'id': 10,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': 192.5,
          'posy': 7.5,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 117.0,
                'posy': -34.5,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 175.875,
                 'posy': 369.0,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  3: [  (1, 'True'),
         (2, "{'SphereDiameter': 0.5, 'Nz': 5, 'Zmax': 2, 'keepFF': False}")],
   6: [(2, "'w'")],
   7: [(2, 'None')],
   8: [],
   9: [  (0, 'PackageData(alinea.caribu.data, par.opt)'),
         (1, 'None'),
         (2, 'None')],
   10: [  (0, 'PackageData(alinea.caribu.data, zenith.light)'),
          (1, 'None'),
          (2, 'None')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  3: {  'position': [192.5, 256.25], 'useUserColor': False, 'userColor': None},
   6: {  'position': [67.5, 227.5], 'useUserColor': False, 'userColor': None},
   7: {  'position': [167.5, 170.0], 'useUserColor': False, 'userColor': None},
   8: {  'position': [11.25, 120.0], 'useUserColor': False, 'userColor': None},
   9: {  'position': [301.25, 7.5], 'useUserColor': False, 'userColor': None},
   10: {  'position': [192.5, 7.5], 'useUserColor': False, 'userColor': None},
   '__in__': {  'position': [117.0, -34.5],
                'useUserColor': False,
                'userColor': None},
   '__out__': {  'position': [175.875, 369.0],
                 'useUserColor': False,
                 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




RunLpy = CompositeNodeFactory(name='RunLpy',
                             description='macro for calling lpy',
                             category='simulation',
                             doc='',
                             inputs=[  {  'desc': '',
      'interface': IFileStr,
      'name': 'Lsystem source',
      'value': None},
   {  'desc': '', 'interface': ITextStr, 'name': 'Axiom', 'value': ''},
   {  'desc': '', 'interface': IInt, 'name': 'DerivationLength', 'value': -1},
   {  'desc': '', 'interface': IDict, 'name': 'Parameters', 'value': {  }}],
                             outputs=[  {  'desc': '', 'interface': None, 'name': 'AxialTree'},
   {  'desc': '', 'interface': None, 'name': 'Lsystem'}],
                             elt_factory={  2: ('vplants.l-py', 'LSystem'),
   3: ('vplants.l-py', 'run'),
   4: ('openalea.file', 'read')},
                             elt_connections={  10019776: ('__in__', 1, 2, 1),
   10019788: (3, 0, '__out__', 0),
   10019800: ('__in__', 2, 3, 2),
   10019812: (2, 0, '__out__', 1),
   10019824: (4, 0, 2, 0),
   10019836: (2, 0, 3, 0),
   10019848: ('__in__', 3, 2, 3),
   10019860: ('__in__', 0, 4, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'LSystem',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x0618ACF0> : "LSystem"',
         'hide': True,
         'id': 2,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -63.75,
         'posy': 146.25,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'run',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x0618AED0> : "run"',
         'hide': True,
         'id': 3,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 59.9946062567422,
         'posy': 220.38834951456317,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'read',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x045594D0> : "read"',
         'hide': True,
         'id': 4,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': -75.0,
         'posy': 82.5,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 61.17853290183385,
                'posy': 5.893743257820944,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 139.375,
                 'posy': 380.5,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(2, '-1')], 3: [(1, "''"), (3, '{}')], 4: [], '__in__': [], '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-63.75, 146.25], 'useUserColor': False, 'userColor': None},
   3: {  'position': [59.9946062567422, 220.38834951456317],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [-75.0, 82.5], 'useUserColor': False, 'userColor': None},
   '__in__': {  'position': [61.17853290183385, 5.893743257820944],
                'useUserColor': False,
                'userColor': None},
   '__out__': {  'position': [139.375, 380.5],
                 'useUserColor': False,
                 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




genMTG = CompositeNodeFactory(name='genMTG',
                             description='Generate an MTG  representing the scene with ADELR ',
                             category='composite',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': None, 'name': 'Leaves db', 'value': None},
   {  'desc': '', 'interface': None, 'name': 'development Rdb', 'value': None},
   {  'desc': '', 'interface': None, 'name': 'Axe geometry (R)', 'value': None},
   {  'desc': '', 'interface': None, 'name': 'Leaf Geometry (R)', 'value': None},
   {  'desc': '', 'interface': IInt, 'name': 'Number of plants', 'value': 1},
   {  'desc': '',
      'interface': None,
      'name': 'Plant positions',
      'value': [(0, 0, 0)]},
   {  'desc': '', 'interface': IFloat, 'name': 'Date (dd)', 'value': 1000},
   {  'desc': '', 'interface': IInt, 'name': 'random seed', 'value': None},
   {  'desc': '',
      'interface': IDict,
      'name': 'Global Parameters',
      'value': {  'endLeaf': 1.6,
                  'epsillon': 1e-06,
                  'senescence_leaf_shrink': 0.5,
                  'startLeaf': -0.4,
                  'stemLeaf': 1.2}}],
                             outputs=[{  'desc': '', 'interface': None, 'name': 'CanMTG'}],
                             elt_factory={  2: ('alinea.adel.wheat', 'CanMTGInterpreter'),
   4: ('alinea.adel.parameterisation', 'setAdel'),
   6: ('alinea.adel.simulation', 'genString'),
   7: ('alinea.adel.geometry', 'symbols'),
   8: ('alinea.adel.simulation', 'RunAdel'),
   9: ('alinea.adel.io', 'Rdataframe'),
   10: ('alinea.adel.stand', 'CanMTGPlanter')},
                             elt_connections={  10019612: (6, 0, 2, 1),
   10019624: (8, 0, 9, 0),
   10019636: ('__in__', 0, 7, 0),
   10019648: ('__in__', 7, 7, 1),
   10019660: ('__in__', 8, 8, 2),
   10019672: ('__in__', 6, 8, 0),
   10019684: (9, 0, 6, 0),
   10019696: ('__in__', 2, 4, 2),
   10019708: ('__in__', 1, 4, 0),
   10019720: ('__in__', 4, 4, 3),
   10019732: (7, 0, 2, 0),
   10019744: (10, 0, '__out__', 0),
   10019756: (4, 0, 8, 1),
   10019768: ('__in__', 7, 4, 4),
   10019780: ('__in__', 3, 4, 1),
   10019792: (2, 0, 10, 0),
   10019804: ('__in__', 5, 10, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'CanMTGInterpreter',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x0442BB10> : "CanMTGInterpreter"',
         'hide': True,
         'id': 2,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 255.00000000000003,
         'posy': 248.75000000000006,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'setAdel',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x0456F390> : "setAdel"',
         'hide': True,
         'id': 4,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 239.99999999999983,
         'posy': -63.75,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'genString',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x044D9B30> : "genString"',
         'hide': True,
         'id': 6,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 458.4521922873746,
         'posy': 236.58734089252795,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'symbols',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x03ED5C90> : "symbols"',
         'hide': True,
         'id': 7,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 53.750000000000114,
         'posy': -76.24999999999996,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'RunAdel',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x044D9B70> : "RunAdel"',
         'hide': True,
         'id': 8,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 303.74999999999983,
         'posy': 98.74999999999991,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': 'Rdataframe',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x03AF6710> : "Rdataframe"',
         'hide': True,
         'id': 9,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 463.67315671856375,
         'posy': 175.2192287374538,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': 'CanMTGPlanter',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0x02267A90> : "CanMTGPlanter"',
          'hide': True,
          'id': 10,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 621.2499999999999,
          'posy': 359.99999999999994,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 540.0,
                'posy': -293.74999999999994,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 600.3125,
                 'posy': 514.5,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [],
   4: [],
   6: [],
   7: [],
   8: [],
   9: [],
   10: [(2, '0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [255.00000000000003, 248.75000000000006],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [318.75000000000006, 161.25000000000003],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [239.99999999999983, -63.75],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [458.4521922873746, 236.58734089252795],
         'useUserColor': False,
         'userColor': None},
   7: {  'position': [53.750000000000114, -76.24999999999996],
         'useUserColor': False,
         'userColor': None},
   8: {  'position': [303.74999999999983, 98.74999999999991],
         'useUserColor': False,
         'userColor': None},
   9: {  'position': [463.67315671856375, 175.2192287374538],
         'useUserColor': False,
         'userColor': None},
   10: {  'position': [621.2499999999999, 359.99999999999994],
          'useUserColor': False,
          'userColor': None},
   '__in__': {  'position': [540.0, -293.74999999999994],
                'useUserColor': False,
                'userColor': None},
   '__out__': {  'position': [600.3125, 514.5],
                 'useUserColor': False,
                 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




_139071248 = CompositeNodeFactory(name='get leaf',
                             description='Select a leaf element from a database',
                             category='composite',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': IDict, 'name': 'leaves', 'value': None},
   {  'desc': '', 'interface': IInt, 'name': 'rank [1,maxrank]', 'value': None},
   {  'desc': '',
      'interface': IInt,
      'name': 'index [1,max_index]',
      'value': None}],
                             outputs=[{  'desc': '', 'interface': ISequence, 'name': 'leaf'}],
                             elt_factory={  4: ('openalea.data structure.string', 'string'),
   5: ('openalea.python method', 'getitem'),
   7: ('openalea.data structure', 'int'),
   8: ('openalea.math', '-'),
   9: ('openalea.python method', 'getitem')},
                             elt_connections={  10019720: ('__in__', 2, 8, 0),
   10019732: (8, 0, 9, 1),
   10019744: (7, 0, 8, 1),
   10019756: (9, 0, '__out__', 0),
   10019768: (4, 0, 5, 1),
   10019780: ('__in__', 1, 4, 0),
   10019792: ('__in__', 0, 5, 0),
   10019804: (5, 0, 9, 0)},
                             elt_data={  4: {  'block': False,
         'caption': 'string',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x040DF5B0> : "string"',
         'hide': True,
         'id': 4,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 100.02005853831852,
         'posy': -63.8329455341893,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'getitem',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x03BA19F0> : "getitem"',
         'hide': True,
         'id': 5,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': -4.340760666597365,
         'posy': 5.433461965954633,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': '1',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x040C59F0> : "int"',
         'hide': True,
         'id': 7,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 195.50446498393399,
         'posy': -113.10609179959386,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': '-',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x040BE210> : "-"',
         'hide': True,
         'id': 8,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 160.0520085290583,
         'posy': -64.16831678353952,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': 'getitem',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x03BA19F0> : "getitem"',
         'hide': True,
         'id': 9,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 67.6561223004275,
         'posy': 78.28355555184055,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set(),
                'posx': 120.0,
                'posy': -189.0,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set(),
                 'posx': 123.24988575049345,
                 'posy': 165.84609052761425,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  4: [], 5: [], 7: [(0, '1')], 8: [], 9: [], '__in__': [], '__out__': []},
                             elt_ad_hoc={  4: {  'position': [100.02005853831852, -63.8329455341893],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [-4.340760666597365, 5.433461965954633],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [-99.4321303537961, 187.7270849592482],
         'useUserColor': False,
         'userColor': None},
   7: {  'position': [195.50446498393399, -113.10609179959386],
         'useUserColor': False,
         'userColor': None},
   8: {  'position': [160.0520085290583, -64.16831678353952],
         'useUserColor': False,
         'userColor': None},
   9: {  'position': [67.6561223004275, 78.28355555184055],
         'useUserColor': False,
         'userColor': None},
   '__in__': {  'position': [120.0, -189.0],
                'useUserColor': False,
                'userColor': None},
   '__out__': {  'position': [123.24988575049345, 165.84609052761425],
                 'useUserColor': False,
                 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




_139071376 = CompositeNodeFactory(name='texture plot',
                             description='Plot adel canMTG with texture',
                             category='visualisation',
                             doc='',
                             inputs=[  {  'desc': 'Canestra Scene',
      'interface': IDict,
      'name': 'scene(to_plantgl)',
      'value': {  }},
   {  'desc': '', 'interface': IFileStr, 'name': 'Leaf Texture', 'value': None},
   {  'desc': '', 'interface': IFileStr, 'name': 'Stem Texture', 'value': None},
   {  'desc': '',
      'interface': IFileStr,
      'name': 'Soil(+senescent) tex',
      'value': None}],
                             outputs=[{  'desc': '', 'interface': None, 'name': 'object(plot3D)'}],
                             elt_factory={  11: ('vplants.plantgl.objects', 'ImageTexture'),
   13: ('vplants.plantgl.objects', 'ImageTexture'),
   15: ('vplants.plantgl.objects', 'ImageTexture'),
   16: ('vplants.plantgl.visualization', 'plot3D'),
   17: ('alinea.adel.io', 'to_plantgl')},
                             elt_connections={  9855204: ('__in__', 3, 15, 4),
   9855216: ('__in__', 2, 13, 4),
   9855228: ('__in__', 1, 11, 4),
   9855240: (16, 0, '__out__', 0),
   9855252: (13, 0, 17, 2),
   9855264: (17, 0, 16, 0),
   9855276: (11, 0, 17, 1),
   9855288: (15, 0, 17, 3),
   9855300: ('__in__', 0, 17, 0)},
                             elt_data={  11: {  'block': False,
          'caption': 'ImageTexture',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 48.75,
          'posy': 143.75,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'ImageTexture',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 282.5,
          'posy': 145.0,
          'priority': 0,
          'user_application': None},
   15: {  'block': False,
          'caption': 'ImageTexture',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 583.75,
          'posy': 156.25,
          'priority': 0,
          'user_application': None},
   16: {  'block': False,
          'caption': 'plot3D',
          'hide': True,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 18.75,
          'posy': 365.0,
          'priority': 0,
          'user_application': None},
   17: {  'block': False,
          'caption': 'to_plantgl',
          'hide': True,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 1.25,
          'posy': 289.99999999999994,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 31.25,
                 'posy': 430.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  11: [  (0, "''"),
          (1, 'None'),
          (2, 'None'),
          (3, 'None'),
          (5, 'None'),
          (6, 'None'),
          (7, 'None'),
          (8, 'None')],
   13: [  (0, "''"),
          (1, 'None'),
          (2, 'None'),
          (3, 'None'),
          (5, 'None'),
          (6, 'None'),
          (7, 'None'),
          (8, 'None')],
   15: [  (0, "''"),
          (1, 'None'),
          (2, 'None'),
          (3, 'None'),
          (5, 'None'),
          (6, 'None'),
          (7, 'None'),
          (8, 'None')],
   16: [],
   17: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




_356011472 = CompositeNodeFactory(name='genMTG_3out',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': None, 'name': 'Leaves db', 'value': None},
   {  'desc': '', 'interface': None, 'name': 'development Rdb', 'value': None},
   {  'desc': '', 'interface': None, 'name': 'Axe geometry (R)', 'value': None},
   {  'desc': '', 'interface': None, 'name': 'Leaf Geometry (R)', 'value': None},
   {  'desc': '', 'interface': IInt, 'name': 'Number of plants', 'value': 1},
   {  'desc': '',
      'interface': None,
      'name': 'Plant positions',
      'value': [(0, 0, 0)]},
   {  'desc': '', 'interface': IFloat, 'name': 'Date (dd)', 'value': 1000},
   {  'desc': '', 'interface': IInt, 'name': 'random seed', 'value': None},
   {  'desc': '',
      'interface': IDict,
      'name': 'Global Parameters',
      'value': {  'endLeaf': 1.6,
                  'epsillon': 1e-06,
                  'senescence_leaf_shrink': 0.5,
                  'startLeaf': -0.4,
                  'stemLeaf': 1.2}},
   {  'desc': '', 'interface': None, 'name': 'xy', 'value': None},
   {  'desc': '', 'interface': None, 'name': 'rd', 'value': None}],
                             outputs=[  {  'desc': '', 'interface': None, 'name': 'CanMTG'},
   {  'desc': '', 'interface': None, 'name': 'Rdataframe'},
   {  'desc': '', 'interface': None, 'name': 'RunAdel'}],
                             elt_factory={  2: ('alinea.adel.wheat', 'CanMTGInterpreter'),
   4: ('alinea.adel.parameterisation', 'setAdel'),
   6: ('alinea.adel.simulation', 'genString'),
   7: ('alinea.adel.geometry', 'symbols'),
   8: ('alinea.adel.simulation', 'RunAdel'),
   9: ('alinea.adel.io', 'Rdataframe'),
   10: ('alinea.adel.stand', 'CanMTGPlanter')},
                             elt_connections={  29816188: (9, 0, '__out__', 1),
   29816200: (8, 0, 9, 0),
   29816212: ('__in__', 2, 4, 2),
   29816224: ('__in__', 7, 4, 4),
   29816236: ('__in__', 9, 4, 5),
   29816248: (10, 0, '__out__', 0),
   29816260: ('__in__', 4, 4, 3),
   29816272: ('__in__', 8, 8, 2),
   29816284: ('__in__', 3, 4, 1),
   29816296: (9, 0, 6, 0),
   29816308: ('__in__', 7, 7, 1),
   29816320: ('__in__', 10, 4, 6),
   29816332: (6, 0, 2, 1),
   29816344: (2, 0, 10, 0),
   29816356: ('__in__', 1, 4, 0),
   29816368: (7, 0, 2, 0),
   29816380: (4, 0, 8, 1),
   29816392: ('__in__', 5, 10, 1),
   29816404: ('__in__', 0, 7, 0),
   29816416: ('__in__', 6, 8, 0),
   29816428: (8, 0, '__out__', 2)},
                             elt_data={  2: {  'block': False,
         'caption': 'CanMTGInterpreter',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x08526750> : "CanMTGInterpreter"',
         'hide': True,
         'id': 2,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 255.00000000000003,
         'posy': 248.75000000000006,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'setAdel',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x09D6F810> : "setAdel"',
         'hide': True,
         'id': 4,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 239.99999999999983,
         'posy': -63.75,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'genString',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x077E7B50> : "genString"',
         'hide': True,
         'id': 6,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 458.4521922873746,
         'posy': 236.58734089252795,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'symbols',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x083A2C50> : "symbols"',
         'hide': True,
         'id': 7,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 53.750000000000114,
         'posy': -76.24999999999996,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'RunAdel',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x077E7AF0> : "RunAdel"',
         'hide': True,
         'id': 8,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 303.74999999999983,
         'posy': 98.74999999999991,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': 'Rdataframe',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x09E55DD0> : "Rdataframe"',
         'hide': True,
         'id': 9,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 463.67315671856375,
         'posy': 175.2192287374538,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': 'CanMTGPlanter',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0x076932D0> : "CanMTGPlanter"',
          'hide': True,
          'id': 10,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 621.2499999999999,
          'posy': 359.99999999999994,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 971.5,
                'posy': -601.75,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 1038.5,
                 'posy': 689.5,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [],
   4: [],
   6: [],
   7: [(2, 'True')],
   8: [],
   9: [],
   10: [(2, '0'), (3, 'None')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [255.00000000000003, 248.75000000000006], 'userColor': None, 'useUserColor': False},
   4: {'position': [239.99999999999983, -63.75], 'userColor': None, 'useUserColor': False},
   6: {'position': [458.4521922873746, 236.58734089252795], 'userColor': None, 'useUserColor': False},
   7: {'position': [53.750000000000114, -76.24999999999996], 'userColor': None, 'useUserColor': False},
   8: {'position': [303.74999999999983, 98.74999999999991], 'userColor': None, 'useUserColor': False},
   9: {'position': [463.67315671856375, 175.2192287374538], 'userColor': None, 'useUserColor': False},
   10: {'position': [621.2499999999999, 359.99999999999994], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [971.5, -601.75], 'userColor': None, 'useUserColor': False},
   '__out__': {'position': [1038.5, 689.5], 'userColor': None, 'useUserColor': False}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




animator = CompositeNodeFactory(name='animator',
                             description='animate a visualisation dataflow that respond to x incrementation',
                             category='visualisation',
                             doc='',
                             inputs=[  {  'desc': '',
      'interface': None,
      'name': 'Data flow ploting function',
      'value': None},
   {  'desc': '', 'interface': IInt, 'name': 'start', 'value': 0},
   {  'desc': '', 'interface': IInt, 'name': 'end', 'value': 100},
   {  'desc': '', 'interface': IInt, 'name': 'step', 'value': 10},
   {  'desc': '', 'interface': None, 'name': 'x', 'value': None}],
                             outputs=[{  'desc': '', 'interface': None, 'name': 'OUT1'}],
                             elt_factory={  7: ('openalea.function operator', 'map'),
   9: ('openalea.flow control', 'X'),
   10: ('openalea.function operator', 'map'),
   11: ('alinea.adel.macro', 'plot')},
                             elt_connections={  9988868: (10, 0, 7, 1),
   9988880: (11, 0, 7, 0),
   9988892: (9, 0, 11, 0),
   9988940: ('__in__', 1, 10, 1),
   9989000: (7, 0, '__out__', 0),
   9989012: ('__in__', 0, 10, 0)},
                             elt_data={  7: {  'block': False,
         'caption': 'map',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 612.1049518946406,
         'posy': 683.7157415466424,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'X2',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 566.25,
         'posy': 557.4519802363696,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'map',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 653.6049782263042,
          'posy': 552.5,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'plot',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 580.7018890392351,
          'posy': 615.862981756145,
          'priority': 0,
          'user_application': False},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 652.5,
                'posy': 475.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 450.0,
                 'posy': 740.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  7: [], 9: [(0, "'x'")], 10: [], 11: [], '__in__': [], '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




