# -*-python-*-

import os
bn = os.path.basename

Import( "env" )

lib_env = env.Clone()

#lib_env.EnableQt4Modules(['QtCore','QtOpenGL', 'QtGui'])

# Import/Export symbols for windows
if lib_env['compiler'] == 'mingw':
    LINKFLAGS=["-enable-stdcall-fixup",
               "-enable-auto-import",
               "-enable-runtime-pseudo-reloc",
               "-s"]
    lib_env.AppendUnique(LINKFLAGS=LINKFLAGS)

includes= lib_env.ALEAGlob('*.h')
sources = lib_env.ALEAGlob('*.cpp')
sources = [ src for src in sources if src != 'Main.cpp']



# Add defines to export symbols on Windows
#lib_env.AppendUnique(CPPDEFINES=['MESSAGE'])
#lib_env.AppendUnique(LIBS=['vptool'])

inc = lib_env.ALEAIncludes( 'nema', includes )
install_lib, lib = lib_env.ALEALibrary( 'nema', sources )

LIBRARIES = list(lib_env['LIBS'])
LIBRARIES.append('nema')

exe = lib_env.ALEAProgram('nema', ['Main.cpp'], LIBS=LIBRARIES)
