
# This file has been generated at Thu Jun 03 14:45:49 2010

from openalea.core import *


__name__ = 'alinea.caribu'

__editable__ = True
__description__ = ' Caribu package '
__license__ = ''
__url__ = ''
__alias__ = ['Caribu']
__version__ = '0.0.4'
__authors__ = 'M. Chelle,C. Fournier'
__institutes__ = 'INRA'
__icon__ = 'Caribou.png'


__all__ = ['LIE', 'CaribuScene_getIncidentEnergy', 'vcaribuOut_adaptor_vcaribuOut_adaptor', 'reduceDict_reduceDict', 'vcaribu_adaptor_vcaribu_adaptor', 'addSoil_addSoil', 'MCSail_MCSail', 'S2v_S2v', 'CaribuScene_newFileCaribuScene', 'Caribu', 'filterby_filterby', 'mtg_updateMTG', 'PARaggregators_PARaggregators', 'CaribuScene_newObjCaribuScene', 'Periodise_Periodise', 'vcaributest2', 'Canestra_Canestra', 'GenOutput_GenOutput', 'vcaribu_vcaribu', 'mtg_to_canestra', 'CaribuZenithPar', '_39992592', '_39993136', 'mydict_mydict', 'ScatteringOptions_ScatteringOptions', '_39992464', 'selectOutput_selectOutput', 'PARsums', 'lightString_lightString', 'debug', 'WriteCan_WriteCan', 'Tutorial']



LIE = CompositeNodeFactory(name='LIE',
                             description='Computes Light interception efficiency',
                             category='scene.light',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': IData, 'name': 'CaribuScene', 'value': None},
   {  'desc': '', 'interface': None, 'name': 'EnergyDict', 'value': None}],
                             outputs=[  {  'desc': '', 'interface': None, 'name': 'Efficience'},
   {  'desc': '', 'interface': None, 'name': 'Total sol'},
   {  'desc': '', 'interface': None, 'name': 'Total Incident'}],
                             elt_factory={  2: ('alinea.caribu', 'selectOutput'),
   3: ('alinea.caribu', 'selectOutput'),
   4: ('alinea.caribu', 'filterby'),
   6: ('openalea.functional', 'function'),
   7: ('openalea.python', 'mean'),
   9: ('alinea.caribu', 'get Ei'),
   10: ('openalea.math', '/'),
   11: ('openalea.math', '-')},
                             elt_connections={  9919048: ('__in__', 0, 9, 0),
   9919060: (11, 0, 10, 0),
   9919072: (4, 0, 7, 0),
   9919084: ('__in__', 1, 3, 0),
   9919096: (6, 0, 4, 2),
   9919108: (2, 0, 4, 1),
   9919120: ('__in__', 1, 2, 0),
   9919132: (9, 0, 10, 1),
   9919144: (9, 0, '__out__', 2),
   9919156: (10, 0, '__out__', 0),
   9919168: (9, 0, 11, 0),
   9919180: (7, 0, '__out__', 1),
   9919192: (3, 0, 4, 0),
   9919204: (7, 0, 11, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'selectOutput',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -321.25,
         'posy': 175.0,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'selectOutput',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -470.0,
         'posy': 176.25,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'filterby',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -343.75,
         'posy': 301.25,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'function',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -256.198347107438,
         'posy': 248.96694214876027,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'mean',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -335.0,
         'posy': 373.75,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'get Ei',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -80.0,
         'posy': 176.25,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': '/',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -121.25,
          'posy': 483.75,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': '-',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -216.25000000000003,
          'posy': 426.25000000000006,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': -452.5,
                'posy': 48.75,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': -112.5,
                 'posy': 590.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [(1, "'EiSup'")],
   3: [(1, "'Opt'")],
   4: [],
   6: [(0, "'def f(x):\\n  return x == 0.'")],
   7: [(0, '[]')],
   9: [],
   10: [],
   11: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




CaribuScene_getIncidentEnergy = Factory(name='get Ei',
                description='get total incident light energy',
                category='scene.light',
                nodemodule='CaribuScene',
                nodeclass='getIncidentEnergy',
                inputs=[{'interface': IStr, 'name': 'CaribuScene'}],
                outputs=[{'interface': IFloat, 'name': 'Energy'}],
                widgetmodule=None,
                widgetclass=None,
               )




vcaribuOut_adaptor_vcaribuOut_adaptor = Factory(name='vcaribuOut adaptor',
                description='adaptor from vcaribu nrj dict to genout like dict',
                category='data i/o',
                nodemodule='vcaribuOut_adaptor',
                nodeclass='vcaribuOut_adaptor',
                inputs=[{'interface': None, 'name': 'irradiance dict', 'value': None, 'desc': ''}],
                outputs=[{'interface': None, 'name': 'genout dict', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




reduceDict_reduceDict = Factory(name='reduceDict',
                description='apply dictionary reduction ',
                category='Unclassified',
                nodemodule='reduceDict',
                nodeclass='reduceDict',
                inputs=[{'interface': None, 'name': 'dictlist', 'value': None, 'desc': ''}],
                outputs=[{'interface': None, 'name': 'reduceddict', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




vcaribu_adaptor_vcaribu_adaptor = Factory(name='vcaribu adaptor',
                description='Adaptor to make vcaribu compatible with caribuScene and Scattering options nodes',
                category='data i/o',
                nodemodule='vcaribu_adaptor',
                nodeclass='vcaribu_adaptor',
                inputs=[{'interface': None, 'name': 'CaribuScene', 'value': None, 'desc': ''}, {'interface': IBool, 'name': 'Direct', 'value': None, 'desc': ''}, {'interface': None, 'name': 'Nz', 'value': None, 'desc': ''}, {'interface': None, 'name': 'dz', 'value': None, 'desc': ''}, {'interface': None, 'name': 'DS', 'value': None, 'desc': ''}],
                outputs=[{'interface': None, 'name': 'Scene', 'desc': ''}, {'interface': None, 'name': 'lightsources', 'desc': ''}, {'interface': None, 'name': 'opticals', 'desc': ''}, {'interface': None, 'name': 'pattern', 'desc': ''}, {'interface': None, 'name': 'optionDict', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




addSoil_addSoil = Factory(name='addSoil',
                description='Add 2 triangles representing the soil along with the pattern of a CaribuScene',
                category='scene.ecophysiology',
                nodemodule='addSoil',
                nodeclass='addSoil',
                inputs=[{'interface': IData, 'name': 'CaribuScene', 'value': None, 'desc': 'Scene to modify'}],
                outputs=[{'interface': IData, 'name': 'CaribuScene', 'desc': 'Modified scene'}],
                widgetmodule=None,
                widgetclass=None,
               )




MCSail_MCSail = Factory(name='MCSail',
                description='Compute mean fluxes on layered canopy',
                category='scene.canopy',
                nodemodule='MCSail',
                nodeclass='MCSail',
                inputs=[{'interface': None, 'name': 'Sailscene'}, {'interface': IBool, 'name': 'Sleep', 'value': False}],
                outputs=[{'interface': IStr, 'name': 'Fluxes'}, {'interface': IStr, 'name': 'Log'}],
                widgetmodule=None,
                widgetclass=None,
               )




S2v_S2v = Factory(name='S2v',
                description='Transform a 3D CaribuScene into a 1D Sail Scene',
                category='codec',
                nodemodule='S2v',
                nodeclass='S2v',
                inputs=[{'interface': None, 'name': 'CaribuScene', 'value': None, 'desc': ''}, {'interface': IInt, 'name': 'Number of layers', 'value': 5, 'desc': ''}, {'interface': IFloat, 'name': 'ZmaxLayer', 'value': 2.0, 'desc': ''}, {'interface': IBool, 'name': 'Sleep', 'value': False, 'desc': ''}],
                outputs=[{'interface': IStr, 'name': 'SailScene', 'desc': ''}, {'interface': ISequence, 'name': 'TriangleLayerLabels', 'desc': ''}, {'interface': IStr, 'name': 'Log', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




CaribuScene_newFileCaribuScene = Factory(name='FileCaribuScene',
                description='Create a CaribuScene object from files',
                category='io,codec',
                nodemodule='CaribuScene',
                nodeclass='newFileCaribuScene',
                inputs=[{'interface': IFileStr(filter="*.can", save=False), 'name': 'CanFile', 'value': None, 'desc': ''}, {'interface': IFileStr(filter="*.light", save=False), 'name': 'LightFile', 'value': None, 'desc': ''}, {'interface': IFileStr(filter="*.8", save=False), 'name': 'PatternFile', 'value': None, 'desc': ''}, {'interface': IFileStr(filter="*.opt", save=False), 'name': 'OptFile', 'value': None, 'desc': ''}],
                outputs=[{'interface': IStr, 'name': 'CaribuScene', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




Caribu = CompositeNodeFactory(name='Caribu',
                             description='Caribu script using objects',
                             category='composite',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': None, 'name': 'CaribuScene', 'value': None},
   {  'desc': '',
      'interface': IBool,
      'name': 'No Multiple Scattering',
      'value': True},
   {  'desc': 'Dictionary of parameters for multiple scaterring',
      'interface': IDict,
      'name': 'Multiple scattering options :',
      'value': {  'Nz': 5, 'SphereDiameter': 0.5, 'Zmax': 2, 'keepFF': False}}],
                             outputs=[  {  'desc': '', 'interface': IStr, 'name': 'CaribuScene'},
   {  'desc': '', 'interface': IDict, 'name': 'Energy'},
   {  'desc': '', 'interface': None, 'name': 'satus'}],
                             elt_factory={  3: ('alinea.caribu', 'Scattering Options'),
   8: ('alinea.caribu', 'vcaribu adaptor'),
   9: ('alinea.caribu', 'vcaribu'),
   10: ('alinea.caribu', 'vcaribuOut adaptor')},
                             elt_connections={  9988848: (9, 1, '__out__', 2),
   9988860: (3, 3, 8, 1),
   9988872: (3, 4, 8, 4),
   9988884: (3, 0, 8, 2),
   9988896: (9, 0, 10, 0),
   9988908: (8, 2, 9, 2),
   9988920: (8, 1, 9, 1),
   9988932: (10, 0, '__out__', 1),
   9988944: ('__in__', 0, 8, 0),
   9988956: (8, 4, 9, 4),
   9988968: ('__in__', 2, 3, 1),
   9988980: ('__in__', 1, 3, 0),
   9988992: (8, 0, 9, 0),
   9989004: (8, 3, 9, 3),
   9989016: ('__in__', 0, '__out__', 0),
   9989028: (3, 1, 8, 3)},
                             elt_data={  3: {  'block': False,
         'caption': 'Scattering Options',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 491.25,
         'posy': 100.0,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'vcaribu adaptor',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 445.0,
         'posy': 236.25,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'vcaribu',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 455.0,
         'posy': 307.5,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'vcaribuOut adaptor',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 290.0,
          'posy': 380.0,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 260.0,
                'posy': -10.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 268.75,
                 'posy': 523.75,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  3: [], 8: [], 9: [], 10: [], '__in__': [], '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




filterby_filterby = Factory(name='filterby',
                description='Return values whose indices match condition',
                category='Unclassified',
                nodemodule='filterby',
                nodeclass='filterby',
                inputs=[{'interface': ISequence, 'name': 'indices', 'value': None, 'desc': ''}, {'interface': ISequence, 'name': 'values', 'value': None, 'desc': ''}, {'interface': IFunction, 'name': 'condition', 'value': None, 'desc': ''}],
                outputs=[{'interface': None, 'name': 'values', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




mtg_updateMTG = Factory(name='updateMTG',
                description='',
                category='data i/o',
                nodemodule='mtg',
                nodeclass='updateMTG',
                inputs=[{'interface': None, 'name': 'mtg', 'value': None, 'desc': ''}, {'interface': None, 'name': 'caribu output', 'value': None, 'desc': ''}, {'interface': None, 'name': 'mtg id for triangles', 'value': None, 'desc': ''}, {'interface': IStr, 'name': 'prefix for mtg property', 'value': None, 'desc': ''}],
                outputs=[{'interface': None, 'name': 'updated mtg', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




PARaggregators_PARaggregators = Factory(name='PARaggregators',
                description='returns a dict of aggregators (0/1) for summing Eabs at different levels',
                category='Unclassified',
                nodemodule='PARaggregators',
                nodeclass='PARaggregators',
                inputs=[{'interface': None, 'name': 'aggregation table', 'value': None, 'desc': ''}],
                outputs=[{'interface': None, 'name': 'aggegators', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




CaribuScene_newObjCaribuScene = Factory(name='ObjCaribuScene',
                description='Generates CaribuScene from objects',
                category='codec,scene',
                nodemodule='CaribuScene',
                nodeclass='newObjCaribuScene',
                inputs=[{'interface': IData, 'name': 'CanObj', 'value': None, 'desc': 'Canopy object with to_canestra method'}, {'interface': IStr, 'name': 'LightString', 'value': None, 'desc': ''}, {'interface': ISequence, 'name': 'pattern', 'value': None, 'desc': 'Tuple describig pattern'}, {'interface': IStr, 'name': 'optstring', 'value': None, 'desc': 'Optical properties'}, {'interface': IStr, 'name': 'wavelength', 'value': None, 'desc': 'Current wavelength'}],
                outputs=[{'interface': IStr, 'name': 'CaribuScene', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




Periodise_Periodise = Factory(name='Periodise',
                description='Fit the scene within its pattern',
                category='scene',
                nodemodule='Periodise',
                nodeclass='Periodise',
                inputs=[{'interface': IStr, 'name': 'CaribuScene'}],
                outputs=[{'interface': IStr, 'name': 'FittedScene'}, {'interface': IStr, 'name': 'Log'}],
                widgetmodule=None,
                widgetclass=None,
               )




vcaributest2 = CompositeNodeFactory(name='vcaributest2',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('alinea.caribu', 'vcaribu'),
   3: ('alinea.caribu.data', 'filterT.can'),
   4: ('alinea.caribu.data', 'zenith.light'),
   5: ('alinea.caribu.data', 'par.opt'),
   6: ('openalea.data structure.dict', 'dict'),
   7: ('openalea.flow control', 'annotation'),
   8: ('openalea.file', 'read'),
   9: ('openalea.file', 'read'),
   10: ('openalea.file', 'read')},
                             elt_connections={  9988924: (9, 0, 2, 2),
   9988936: (6, 0, 2, 4),
   9988948: (4, 0, 10, 0),
   9988960: (10, 0, 2, 1),
   9988972: (5, 0, 9, 0),
   9988984: (3, 0, 8, 0),
   9988996: (8, 0, 2, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'vcaribu',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 195.46600843048085,
         'posy': 235.00000000000003,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'filterT.can',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 56.25,
         'posy': 118.75,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'zenith.light',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 112.5,
         'posy': 53.75,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'par.opt',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 222.5,
         'posy': 97.5,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'Caribu options',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 362.96600843048077,
         'posy': 139.53399156951909,
         'priority': 0,
         'user_application': None},
   7: {  'posx': 66.639283409126449,
         'posy': 3.9199578475956756,
         'txt': 'Test of vcaribu, the visualea interface to the caribu script (class Caribu)'},
   8: {  'block': False,
         'caption': 'read',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 92.5,
         'posy': 186.25,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'read',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 251.25,
         'posy': 158.75,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': 155.0,
          'posy': 146.25,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [(3, 'None')],
   3: [  (0, 'PackageData(alinea.caribu.data, filterT.can)'),
         (1, 'None'),
         (2, 'None')],
   4: [  (0, 'PackageData(alinea.caribu.data, zenith.light)'),
         (1, 'None'),
         (2, 'None')],
   5: [  (0, 'PackageData(alinea.caribu.data, par.opt)'),
         (1, 'None'),
         (2, 'None')],
   6: [  (  0,
            "{'wavelength': 'par', 'Hc': None, 'Nz': None, 'Ds': None, '1st': True}")],
   7: [],
   8: [],
   9: [],
   10: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




Canestra_Canestra = Factory(name='Canestra',
                description='Nested radiosity illumination of a 3D Scene ',
                category='scene.light',
                nodemodule='Canestra',
                nodeclass='Canestra',
                inputs=[{'interface': None, 'name': 'CaribuScene', 'value': None, 'desc': ''}, {'interface': IStr, 'name': 'SailFluxes', 'value': None, 'desc': ''}, {'interface': IBool, 'name': 'No Multiple Scattering', 'value': True, 'desc': ''}, {'interface': IFloat, 'name': 'Sphere Diameter', 'value': 0.5, 'desc': ''}, {'interface': IBool, 'name': 'keep FF in Scene', 'value': False, 'desc': ''}],
                outputs=[{'interface': IStr, 'name': 'CaribuScene', 'desc': ''}, {'interface': IStr, 'name': 'Etri', 'desc': ''}, {'interface': IStr, 'name': 'Eabs', 'desc': ''}, {'interface': IStr, 'name': 'Log', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




GenOutput_GenOutput = Factory(name='GenOutput',
                description='Generate a dictionnary from canestra outputs (Etri,Eabs)',
                category='codec',
                nodemodule='GenOutput',
                nodeclass='GenOutput',
                inputs=[{'interface': IStr, 'name': 'Etri', 'value': None, 'desc': ''}, {'interface': IStr, 'name': 'Eabs', 'value': None, 'desc': ''}],
                outputs=[{'interface': None, 'name': 'OutDict', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




vcaribu_vcaribu = Factory(name='vcaribu',
                description='Visualea interface to Caribu class',
                category='model',
                nodemodule='vcaribu',
                nodeclass='vcaribu',
                inputs=[{'interface': IFileStr, 'name': 'canopy', 'value': None, 'desc': "file '.can' or file content representing the 3d scene"}, {'interface': IFileStr, 'name': 'lightsource', 'value': None, 'desc': 'file or file content describing light sources (direction, irradiance)'}, {'interface': None, 'name': 'optics', 'value': None, 'desc': 'list of files/files contents defining optical property'}, {'interface': IFileStr, 'name': 'pattern', 'value': None, 'desc': 'file/file content that defines a domain to till the scene. Caribu consider a toric canopy if pattern is given'}, {'interface': None, 'name': 'options', 'value': None, 'desc': 'dictionarry allowing to set user option.Available options are:\n        \n        1st: consider only direct projection if True.\n        Nz: number of layers to be consider for the scene\n        Hc: height of the can scene\n        Ds: diameter of the sphere for nested radiosity\n        debug : print messages and prevent removal of tempdir\n        resdir : store caribu results as files in resdir if resdir is not None, store nothing otherwise\n        wavelength: list of name to be used as keys for output dict (if None use the name of the opt files or the generic names band0,band1 if optfiles are given as content)'}],
                outputs=[{'interface': None, 'name': 'irradiances', 'desc': ''}, {'interface': None, 'name': 'Settings', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




mtg_to_canestra = Factory(name='MtgToCan',
                description='Give a canestra repr of MTG',
                category='data i/o',
                nodemodule='mtg',
                nodeclass='to_canestra',
                inputs=[{'interface': None, 'name': 'MTG', 'value': None, 'desc': ''}, {'interface': IStr, 'name': 'Property to use as OptId', 'value': 'optical_specie', 'desc': ''}, {'interface': IStr, 'name': 'Property to use as opacity', 'value': 'transparency', 'desc': ''}, {'interface': IStr, 'name': 'Property to use as Geometry', 'value': 'geometry', 'desc': ''}, {'interface': IInt, 'name': 'Deault for optid', 'value': 1, 'desc': ''}, {'interface': IInt, 'name': 'Defalt for opacity', 'value': 0, 'desc': ''}, {'interface': IFloat(min=0, max=16777216, step=0.000001), 'name': 'minimal area', 'value': 1.0000000000000001e-05, 'desc': ''}],
                outputs=[{'interface': None, 'name': 'mtgId', 'desc': 'list of mtd id associated with triangles'}, {'interface': None, 'name': 'CanString', 'desc': 'Canestra input file'}],
                widgetmodule=None,
                widgetclass=None,
               )




CaribuZenithPar = CompositeNodeFactory(name='CaribuZenithPar',
                             description='Run Caribu with default PO and one ligth source at zenith',
                             category='scene.light,composite',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': IData, 'name': 'CanScene', 'value': None},
   {  'desc': '', 'interface': ISequence, 'name': 'Pattern', 'value': None}],
                             outputs=[  {  'desc': '', 'interface': None, 'name': 'CaribuScene'},
   {  'desc': '', 'interface': None, 'name': 'CaribuOutDict'}],
                             elt_factory={  3: ('Caribu', 'Caribu'),
   6: ('Caribu', 'ObjCaribuScene'),
   7: ('catalog.file', 'read'),
   8: ('catalog.file', 'read'),
   9: ('caribu.data', 'par.opt'),
   10: ('caribu.data', 'zenith.light')},
                             elt_connections={  9723276: (3, 0, '__out__', 0),
   9723288: ('__in__', 1, 6, 2),
   9723300: (9, 0, 7, 0),
   9723312: (8, 0, 6, 1),
   9723324: (3, 1, '__out__', 1),
   9723336: (10, 0, 8, 0),
   9723348: (6, 0, 3, 0),
   9723360: ('__in__', 0, 6, 0),
   9723372: (7, 0, 6, 3)},
                             elt_data={  3: {  'caption': 'Caribu',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 191.25,
         'posy': 256.25,
         'priority': 0,
         'user_application': None},
   6: {  'caption': 'ObjCaribuScene',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 145.0,
         'posy': 186.25,
         'priority': 0,
         'user_application': None},
   7: {  'caption': 'read',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 311.25,
         'posy': 77.5,
         'priority': 0,
         'user_application': None},
   8: {  'caption': 'read',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 210.0,
         'posy': 75.0,
         'priority': 0,
         'user_application': None},
   9: {  'caption': 'par.opt',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 301.25,
         'posy': 7.5,
         'priority': 0,
         'user_application': None},
   10: {  'caption': 'zenith.light',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': 191.25,
          'posy': 7.5,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 150.0,
                'posy': 71.25,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 198.75,
                 'posy': 340.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  3: [  (1, 'True'),
         (2, "{'SphereDiameter': 0.5, 'Nz': 5, 'Zmax': 2, 'keepFF': False}")],
   6: [(4, "'par'")],
   7: [],
   8: [],
   9: [(0, 'PackageData(caribu.data, par.opt)'), (1, 'None'), (2, 'None')],
   10: [  (0, 'PackageData(caribu.data, zenith.light)'),
          (1, 'None'),
          (2, 'None')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




_39992592 = CompositeNodeFactory(name='vcaribu_test',
                             description='Test of vcaribu',
                             category='composite',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('alinea.caribu', 'vcaribu'),
   3: ('alinea.caribu.data', 'filterT.can'),
   4: ('alinea.caribu.data', 'zenith.light'),
   5: ('alinea.caribu.data', 'par.opt'),
   6: ('openalea.data structure.dict', 'dict'),
   7: ('openalea.flow control', 'annotation')},
                             elt_connections={  16790896: (5, 0, 2, 2),
   16790908: (3, 0, 2, 0),
   16790920: (4, 0, 2, 1),
   16790932: (6, 0, 2, 4)},
                             elt_data={  2: {  'block': False,
         'caption': 'vcaribu',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 195.46600843048085,
         'posy': 235.00000000000003,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'filterT.can',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 56.25,
         'posy': 118.75,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'zenith.light',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 112.5,
         'posy': 53.75,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'par.opt',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 222.5,
         'posy': 97.5,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'Caribu options',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 362.96600843048077,
         'posy': 139.53399156951909,
         'priority': 0,
         'user_application': None},
   7: {  'posx': 66.639283409126449,
         'posy': 3.9199578475956756,
         'txt': 'Test of vcaribu, the visualea interface to the caribu script (class Caribu)'},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [(3, 'None')],
   3: [  (0, 'PackageData(alinea.caribu.data, filterT.can)'),
         (1, 'None'),
         (2, 'None')],
   4: [  (0, 'PackageData(alinea.caribu.data, zenith.light)'),
         (1, 'None'),
         (2, 'None')],
   5: [  (0, 'PackageData(alinea.caribu.data, par.opt)'),
         (1, 'None'),
         (2, 'None')],
   6: [(0, "{'Hc': None, 'Nz': None, 'Ds': None, '1st': True}")],
   7: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




_39993136 = CompositeNodeFactory(name='Demo Glasgow',
                             description='',
                             category='tutorial',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('alinea.caribu', 'Caribu'),
   3: ('alinea.caribu', 'FileCaribuScene'),
   4: ('openalea.flow control', 'annotation'),
   5: ('alinea.caribu.visualisation', 'ViewMapOnCan'),
   6: ('alinea.caribu.data', 'f331s1_100plantes.can'),
   7: ('openalea.flow control', 'annotation'),
   8: ('alinea.caribu.data', 'par.opt'),
   9: ('alinea.caribu.data', 'zenith.light'),
   10: ('alinea.caribu', 'ObjCaribuScene'),
   11: ('alinea.caribu', 'LIE'),
   12: ('alinea.caribu', 'addSoil'),
   13: ('alinea.caribu', 'selectOutput'),
   14: ('alinea.caribu.visualisation', 'Plot CaribuScene'),
   15: ('alinea.Caribu.Sky_tools', 'GenSkyFile'),
   16: ('openalea.flow control', 'annotation'),
   22: ('openalea.flow control', 'annotation'),
   23: ('openalea.flow control', 'annotation'),
   24: ('alinea.caribu', 'MtgToCan'),
   25: ('openalea.flow control', 'annotation')},
                             elt_connections={  9920664: (2, 1, 13, 0),
   9920676: (9, 0, 15, 0),
   9920688: (2, 1, 11, 1),
   9920700: (8, 0, 3, 3),
   9920712: (2, 0, 5, 0),
   9920724: (13, 0, 5, 1),
   9920736: (3, 0, 14, 0),
   9920748: (12, 0, 2, 0),
   9920772: (2, 0, 11, 0),
   9920784: (24, 0, 10, 0),
   9920796: (15, 0, 3, 1),
   9920808: (3, 0, 12, 0),
   9920820: (6, 0, 3, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'Caribu',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 456.25,
         'posy': 588.75,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'FileCaribuScene',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 402.5,
         'posy': 365.0,
         'priority': 0,
         'user_application': None},
   4: {  'posx': -27.5,
         'posy': 24.999999999999986,
         'txt': 'Caribu : Nested radiosity for illuminating 3D scene (Chelle 1998)'},
   5: {  'block': False,
         'caption': 'ViewMapOnCan',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 573.75,
         'posy': 743.75,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'f331s1_100plantes.can',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 211.25,
         'posy': 227.5,
         'priority': 0,
         'user_application': None},
   7: {  'posx': 216.25, 'posy': 591.25, 'txt': 'Radiosity computation'},
   8: {  'block': False,
         'caption': 'par.opt',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 700.0,
         'posy': 278.75,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'Meteo.xls',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 497.5,
         'posy': 162.5,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'ObjCaribuScene',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 53.75,
          'posy': 321.25,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'LIE',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 387.5,
          'posy': 732.5,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': 'addSoil',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 435.0,
          'posy': 486.25,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'selectOutput',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 588.75,
          'posy': 651.25,
          'priority': 0,
          'user_application': None},
   14: {  'block': False,
          'caption': 'Plot CaribuScene',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 165.0,
          'posy': 477.5,
          'priority': 0,
          'user_application': None},
   15: {  'block': False,
          'caption': 'GenSkyFile',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 531.24999999999977,
          'posy': 228.75,
          'priority': 0,
          'user_application': None},
   16: {  'posx': 774.99999999999977,
          'posy': 746.25,
          'txt': 'Visualise  output'},
   22: {  'posx': 696.25, 'posy': 220.0, 'txt': 'Lighting specification'},
   23: {  'posx': 95.0, 'posy': 157.5, 'txt': '3D scene (file or MTG)'},
   24: {  'block': False,
          'caption': 'MtgToCan',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 27.5,
          'posy': 228.74999999999989,
          'priority': 0,
          'user_application': None},
   25: {  'posx': 57.5,
          'posy': 787.5,
          'txt': 'Compute light interception efficiency'},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [  (1, 'True'),
         (2, "{'SphereDiameter': 0.5, 'Nz': 5, 'Zmax': 2, 'keepFF': False}")],
   3: [  (  0,
            "'d:\\\\openaleapkg\\\\caribu\\\\src\\\\caribu\\\\data\\\\f331s1_100plantes.can'"),
         (2, 'None')],
   4: [],
   5: [(2, '0.20000000000000001')],
   6: [  (0, 'PackageData(alinea.caribu.data, f331s1_100plantes.can)'),
         (1, 'None'),
         (2, 'None')],
   7: [],
   8: [  (0, 'PackageData(alinea.caribu.data, par.opt)'),
         (1, 'None'),
         (2, 'None')],
   9: [  (0, 'PackageData(alinea.caribu.data, zenith.light)'),
         (1, 'None'),
         (2, 'None')],
   10: [(1, 'None'), (2, 'None'), (3, 'None'), (4, 'None')],
   11: [],
   12: [],
   13: [(1, "'EiSup'")],
   14: [],
   15: [(1, 'None'), (2, 'None'), (3, 'None'), (4, 'None'), (5, 'None')],
   16: [],
   22: [],
   23: [],
   24: [  (0, 'None'),
          (1, "'optical_specie'"),
          (2, "'transparency'"),
          (3, "'geometry'"),
          (4, '1'),
          (5, '0'),
          (6, '0')],
   25: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




mydict_mydict = Factory(name='mydict',
                description='debug dict',
                category='Unclassified',
                nodemodule='mydict',
                nodeclass='mydict',
                inputs=[{'interface': None, 'name': 'liste of tuple', 'value': None, 'desc': ''}],
                outputs=[{'interface': None, 'name': 'dict', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




ScatteringOptions_ScatteringOptions = Factory(name='Scattering Options',
                description='handles multiple scattering options',
                category='scene',
                nodemodule='ScatteringOptions',
                nodeclass='ScatteringOptions',
                inputs=[{'interface': IBool, 'name': 'No Multiple Scaterring', 'value': True, 'desc': 'Turn off multiple scattering calculations'}, {'interface': IDict, 'name': 'Multiple scattering options :', 'value': {'SphereDiameter': 0.5, 'Nz': 5, 'Zmax': 2, 'keepFF': False}, 'desc': 'Dictionary of parameters for multiple scaterring'}],
                outputs=[{'interface': IInt, 'name': 'Number of layers', 'desc': ''}, {'interface': IFloat, 'name': 'ZmaxLayer', 'desc': ''}, {'interface': IBool, 'name': 'Sleep!', 'desc': ''}, {'interface': IBool, 'name': 'No multiple scattering', 'desc': ''}, {'interface': IFloat, 'name': 'Sphere Diameter', 'desc': ''}, {'interface': IBool, 'name': 'keep FF in Scene', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




_39992464 = CompositeNodeFactory(name='Directional gap fraction',
                             description='Compute the directional gap fraction of a scene after making it infinite',
                             category='data processing',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': None, 'name': 'CanMTG', 'value': None},
   {  'desc': '', 'interface': None, 'name': 'Pattern', 'value': None},
   {  'desc': 'zenithal direction of view',
      'interface': IFloat,
      'name': 'zenith angle',
      'value': 0},
   {  'desc': 'azimuthal direction of view',
      'interface': IFloat,
      'name': 'azimuth angle',
      'value': 0}],
                             outputs=[{  'desc': '', 'interface': None, 'name': 'Gap fraction'}],
                             elt_factory={  2: ('alinea.caribu', 'Caribu'),
   4: ('alinea.caribu', 'addSoil'),
   5: ('alinea.caribu', 'selectOutput'),
   6: ('alinea.caribu.data', 'par.opt'),
   7: ('alinea.caribu', 'light string'),
   8: ('alinea.caribu', 'ObjCaribuScene'),
   9: ('openalea.file', 'read'),
   10: ('alinea.caribu', 'selectOutput'),
   11: ('alinea.caribu', 'filterby'),
   12: ('openalea.function operator', 'function'),
   13: ('openalea.python method', 'mean')},
                             elt_connections={  9988816: (5, 0, 11, 1),
   9988828: ('__in__', 0, 8, 0),
   9988840: (13, 0, '__out__', 0),
   9988852: (2, 1, 10, 0),
   9988864: ('__in__', 2, 7, 1),
   9988876: ('__in__', 3, 7, 2),
   9988888: (9, 0, 8, 3),
   9988900: (8, 0, 4, 0),
   9988912: (4, 0, 2, 0),
   9988924: (11, 0, 13, 0),
   9988936: (2, 1, 5, 0),
   9988948: (6, 0, 9, 0),
   9988960: (12, 0, 11, 2),
   9988972: (10, 0, 11, 0),
   9988984: (7, 0, 8, 1),
   9988996: ('__in__', 1, 8, 2)},
                             elt_data={  2: {  'block': False,
         'caption': 'Caribu',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 636.25,
         'posy': 471.25,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'addSoil',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 608.75,
         'posy': 402.5,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'selectOutput',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 73.75,
         'posy': 325.0,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'par.opt',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 675.0,
         'posy': 148.75,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'light string',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 545.0,
         'posy': 148.75,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'ObjCaribuScene',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 547.5,
         'posy': 336.25,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'read',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 670.0,
         'posy': 236.25,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'selectOutput',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -75.0,
          'posy': 326.25,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'filterby',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 51.25,
          'posy': 451.25,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': 'function',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 138.80165289256206,
          'posy': 398.96694214876027,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'mean',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 60.0,
          'posy': 523.75,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 418.75,
                'posy': 37.5,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 605.0,
                 'posy': 691.25,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [  (1, 'True'),
         (2, "{'SphereDiameter': 0.5, 'Nz': 5, 'Zmax': 2, 'keepFF': False}")],
   4: [],
   5: [(1, "'EiSup'")],
   6: [  (0, 'PackageData(alinea.caribu.data, par.opt)'),
         (1, 'None'),
         (2, 'None')],
   7: [(0, '1')],
   8: [(4, "'par'")],
   9: [],
   10: [(1, "'Opt'")],
   11: [],
   12: [(0, "'def f(x):\\n  return x == 0.'")],
   13: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




selectOutput_selectOutput = Factory(name='selectOutput',
                description='Select a variable in the output dictionnary of caribu',
                category='io',
                nodemodule='selectOutput',
                nodeclass='selectOutput',
                inputs=[{'interface': None, 'name': 'EnergyLabel', 'value': None, 'desc': ''}, {'interface': IEnumStr(enum=['Eabs', 'Area', 'Eabsm2', 'EiInf', 'EiSup', 'Opt', 'Opak', 'Plt', 'Elt']), 'name': 'variable', 'value': None, 'desc': ''}],
                outputs=[{'interface': None, 'name': 'selected output', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




PARsums = CompositeNodeFactory(name='PARsums',
                             description='Sums of Eabs for different scene elements',
                             category='data i/o',
                             doc='',
                             inputs=[{  'desc': '', 'interface': None, 'name': 'CaribuOut', 'value': None}],
                             outputs=[{  'desc': '', 'interface': None, 'name': 'sumdict'}],
                             elt_factory={  2: ('alinea.caribu', 'PARaggregators'),
   3: ('alinea.caribu', 'filterby'),
   4: ('openalea.function operator', 'function'),
   5: ('openalea.python method', 'getitem'),
   6: ('openalea.python method', 'sum'),
   7: ('openalea.data structure.string', 'string'),
   8: ('alinea.caribu', 'filterby'),
   9: ('openalea.function operator', 'function'),
   10: ('openalea.python method', 'getitem'),
   11: ('openalea.python method', 'sum'),
   12: ('openalea.data structure.string', 'string'),
   13: ('openalea.python method', 'getitem'),
   14: ('openalea.data structure.string', 'string'),
   15: ('alinea.caribu', 'filterby'),
   16: ('openalea.function operator', 'function'),
   17: ('openalea.python method', 'sum'),
   18: ('openalea.python method', 'getitem'),
   19: ('openalea.data structure.string', 'string'),
   20: ('alinea.caribu', 'filterby'),
   21: ('openalea.function operator', 'function'),
   22: ('openalea.python method', 'sum'),
   23: ('openalea.python method', 'getitem'),
   24: ('openalea.data structure.string', 'string'),
   25: ('alinea.caribu', 'filterby'),
   26: ('openalea.function operator', 'function'),
   27: ('openalea.python method', 'getitem'),
   28: ('openalea.python method', 'sum'),
   29: ('openalea.data structure.string', 'string'),
   30: ('openalea.python method', 'zip'),
   31: ('alinea.caribu', 'mydict')},
                             elt_connections={  10018732: (2, 0, 23, 0),
   10018744: (13, 0, 15, 1),
   10018756: (20, 0, 22, 0),
   10018768: (22, 0, 30, 1),
   10018780: (16, 0, 15, 2),
   10018792: (26, 0, 25, 2),
   10018804: (29, 0, 27, 1),
   10018816: (14, 0, 13, 1),
   10018828: (5, 0, 3, 0),
   10018840: (19, 0, 30, 0),
   10018852: (8, 0, 11, 0),
   10018864: (13, 0, 8, 1),
   10018876: (13, 0, 20, 1),
   10018888: (25, 0, 28, 0),
   10018900: (7, 0, 30, 0),
   10018912: (17, 0, 30, 1),
   10018924: (13, 0, 25, 1),
   10018936: (12, 0, 30, 0),
   10018948: ('__in__', 0, 2, 0),
   10018960: (2, 0, 18, 0),
   10018972: (11, 0, 30, 1),
   10018984: (24, 0, 23, 1),
   10018996: (4, 0, 3, 2),
   10019008: (30, 0, 31, 0),
   10019020: (18, 0, 15, 0),
   10019032: (13, 0, 3, 1),
   10019044: (21, 0, 20, 2),
   10019056: (19, 0, 18, 1),
   10019068: (24, 0, 30, 0),
   10019080: (9, 0, 8, 2),
   10019092: (23, 0, 20, 0),
   10019104: (2, 0, 5, 0),
   10019116: (3, 0, 6, 0),
   10019128: (7, 0, 5, 1),
   10019140: (29, 0, 30, 0),
   10019152: (15, 0, 17, 0),
   10019164: (27, 0, 25, 0),
   10019176: (12, 0, 10, 1),
   10019188: (6, 0, 30, 1),
   10019200: (2, 0, 27, 0),
   10019212: (28, 0, 30, 1),
   10019224: (2, 0, 10, 0),
   10019236: (10, 0, 8, 0),
   10019248: ('__in__', 0, 13, 0),
   10019260: (31, 0, '__out__', 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'PARaggregators',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 69.723581400544504,
         'posy': 92.928643495772064,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'filterby',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -171.27406947106351,
         'posy': 267.64489661153095,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'f',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -140.25829716739622,
         'posy': 228.16717782253733,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'getitem',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -184.66886914838165,
         'posy': 191.82490630075426,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'sum',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -159.59189337038447,
         'posy': 319.38024791453745,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': "'Green'",
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -205.89256249672724,
         'posy': 20.94633804466028,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'filterby',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -309.57221137129977,
         'posy': 273.94844010782913,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': 'f',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -280.13514032699686,
         'posy': 232.91545030872749,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': 'getitem',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -324.0,
          'posy': 197.96583763784142,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   11: {  'block': False,
          'caption': 'sum',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -297.89003527062096,
          'posy': 325.68379141083562,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   12: {  'block': False,
          'caption': "'Total'",
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -316.56072386333619,
          'posy': 20.94633804466028,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   13: {  'block': False,
          'caption': 'getitem',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 188.59205589920793,
          'posy': 93.316978325802864,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   14: {  'block': False,
          'caption': "'Eabs'",
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 203.58203610176145,
          'posy': -55.0,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   15: {  'block': False,
          'caption': 'filterby',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 288.9881219048475,
          'posy': 272.21347410652197,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   16: {  'block': False,
          'caption': 'f',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 318.42519294915041,
          'posy': 231.18048430742033,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   17: {  'block': False,
          'caption': 'sum',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 300.67029800552632,
          'posy': 323.94882540952847,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   18: {  'block': False,
          'caption': 'getitem',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 290.10781562842578,
          'posy': 169.22734965626117,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   19: {  'block': False,
          'caption': "'Leaves'",
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 307.36655430337078,
          'posy': 20.94633804466028,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   20: {  'block': False,
          'caption': 'filterby',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -36.765398181095748,
          'posy': 266.48545429252465,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   21: {  'block': False,
          'caption': 'f',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -6.5100385919359951,
          'posy': 222.99759885885271,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   22: {  'block': False,
          'caption': 'sum',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -25.083222080416931,
          'posy': 326.40369104409871,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   23: {  'block': False,
          'caption': 'getitem',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -35.645704457517468,
          'posy': 186.41140909825305,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   24: {  'block': False,
          'caption': "'Stem'",
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -18.386965782572588,
          'posy': 20.94633804466028,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   25: {  'block': False,
          'caption': 'filterby',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 442.82636833791832,
          'posy': 289.39753354851393,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   26: {  'block': False,
          'caption': 'f',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 472.26343938222124,
          'posy': 248.36454374941229,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   27: {  'block': False,
          'caption': 'getitem',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 427.58029116436126,
          'posy': 207.68691126452887,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   28: {  'block': False,
          'caption': 'sum',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 454.50854443859714,
          'posy': 341.13288485152043,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   29: {  'block': False,
          'caption': "'Soil'",
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 435.8378558458819,
          'posy': 20.94633804466028,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   30: {  'block': False,
          'caption': 'zip',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 86.879575118491459,
          'posy': 416.43814419434943,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   31: {  'block': False,
          'caption': 'mydict',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 78.837290383062424,
          'posy': 460.79036965272695,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 74.131719691110618,
                'posy': -115.0,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 74.131719691110618,
                 'posy': 510.28044722759307,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [],
   3: [],
   4: [(0, "'def f(x):\\n    return x'")],
   5: [],
   6: [],
   7: [(0, "'Green'")],
   8: [],
   9: [(0, "'def f(x):\\n    return x'")],
   10: [],
   11: [],
   12: [(0, "'Total'")],
   13: [],
   14: [(0, "'Eabs'")],
   15: [],
   16: [(0, "'def f(x):\\n    return x'")],
   17: [],
   18: [],
   19: [(0, "'Leaves'")],
   20: [],
   21: [(0, "'def f(x):\\n    return x'")],
   22: [],
   23: [],
   24: [(0, "'Stem'")],
   25: [],
   26: [(0, "'def f(x):\\n    return x'")],
   27: [],
   28: [],
   29: [(0, "'Soil'")],
   30: [],
   31: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [69.723581400544504, 92.928643495772064], 'userColor': None, 'useUserColor': False},
   3: {'position': [-171.27406947106351, 267.64489661153095], 'userColor': None, 'useUserColor': False},
   4: {'position': [-140.25829716739622, 228.16717782253733], 'userColor': None, 'useUserColor': False},
   5: {'position': [-184.66886914838165, 191.82490630075426], 'userColor': None, 'useUserColor': False},
   6: {'position': [-159.59189337038447, 319.38024791453745], 'userColor': None, 'useUserColor': False},
   7: {'position': [-205.89256249672724, 20.94633804466028], 'userColor': None, 'useUserColor': False},
   8: {'position': [-309.57221137129977, 273.94844010782913], 'userColor': None, 'useUserColor': False},
   9: {'position': [-280.13514032699686, 232.91545030872749], 'userColor': None, 'useUserColor': False},
   10: {'position': [-324.0, 197.96583763784142], 'userColor': None, 'useUserColor': False},
   11: {'position': [-297.89003527062096, 325.68379141083562], 'userColor': None, 'useUserColor': False},
   12: {'position': [-316.56072386333619, 20.94633804466028], 'userColor': None, 'useUserColor': False},
   13: {'position': [188.59205589920793, 93.316978325802864], 'userColor': None, 'useUserColor': False},
   14: {'position': [203.58203610176145, -55.0], 'userColor': None, 'useUserColor': False},
   15: {'position': [288.9881219048475, 272.21347410652197], 'userColor': None, 'useUserColor': False},
   16: {'position': [318.42519294915041, 231.18048430742033], 'userColor': None, 'useUserColor': False},
   17: {'position': [300.67029800552632, 323.94882540952847], 'userColor': None, 'useUserColor': False},
   18: {'position': [290.10781562842578, 169.22734965626117], 'userColor': None, 'useUserColor': False},
   19: {'position': [307.36655430337078, 20.94633804466028], 'userColor': None, 'useUserColor': False},
   20: {'position': [-36.765398181095748, 266.48545429252465], 'userColor': None, 'useUserColor': False},
   21: {'position': [-6.5100385919359951, 222.99759885885271], 'userColor': None, 'useUserColor': False},
   22: {'position': [-25.083222080416931, 326.40369104409871], 'userColor': None, 'useUserColor': False},
   23: {'position': [-35.645704457517468, 186.41140909825305], 'userColor': None, 'useUserColor': False},
   24: {'position': [-18.386965782572588, 20.94633804466028], 'userColor': None, 'useUserColor': False},
   25: {'position': [442.82636833791832, 289.39753354851393], 'userColor': None, 'useUserColor': False},
   26: {'position': [472.26343938222124, 248.36454374941229], 'userColor': None, 'useUserColor': False},
   27: {'position': [427.58029116436126, 207.68691126452887], 'userColor': None, 'useUserColor': False},
   28: {'position': [454.50854443859714, 341.13288485152043], 'userColor': None, 'useUserColor': False},
   29: {'position': [435.8378558458819, 20.94633804466028], 'userColor': None, 'useUserColor': False},
   30: {'position': [86.879575118491459, 416.43814419434943], 'userColor': None, 'useUserColor': False},
   31: {'position': [78.837290383062424, 460.79036965272695], 'userColor': None, 'useUserColor': False},
   32: {'position': [-74.606441869508018, 74.170676445996378], 'userColor': None, 'useUserColor': False},
   33: {'position': [-119.28959008736796, 33.493043961112988], 'userColor': None, 'useUserColor': False},
   34: {'position': [-92.361336813132112, 166.93901754810452], 'userColor': None, 'useUserColor': False},
   35: {'position': [-111.03202540584729, -153.24752925875561], 'userColor': None, 'useUserColor': False},
   50: {'position': [180.23928841047382, 809.40791554703515], 'userColor': None, 'useUserColor': False},
   51: {'position': [305.40546091774723, 971.28949865644211], 'userColor': None, 'useUserColor': False},
   52: {'position': [388.84957592259627, 922.89191195362969], 'userColor': None, 'useUserColor': False},
   53: {'position': [278.70334411619558, 892.85203055188413], 'userColor': None, 'useUserColor': False},
   54: {'position': [317.08763701842611, 1023.0248499594486], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [74.131719691110618, -115.0], 'useUserColor': False, 'userColor': None},
   '__out__': {'position': [74.131719691110618, 510.28044722759307], 'useUserColor': False, 'userColor': None}},
                             lazy=True,
                             )




lightString_lightString = Factory(name='light string',
                description='return a string formated for caribu light input from radiance plus azimutal and zenital angles',
                category='Unclassified',
                nodemodule='lightString',
                nodeclass='lightString',
                inputs=[{'interface': IFloat, 'name': 'Radiance', 'value': 1, 'desc': ''}, {'interface': IFloat, 'name': 'Zenith angle (deg)', 'value': 0, 'desc': ''}, {'interface': IFloat, 'name': 'Azimuth angle (deg)', 'value': 46, 'desc': ''}],
                outputs=[{'interface': IStr, 'name': 'vector', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




debug = CompositeNodeFactory(name='debug',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('alinea.caribu', 'Periodise'),
   3: ('alinea.caribu', 'FileCaribuScene'),
   4: ('alinea.caribu.visualisation', 'Plot CaribuScene'),
   5: ('alinea.caribu.visualisation', 'ViewMapOnCan'),
   6: ('alinea.caribu.data', 'f331s1_100plantes.can'),
   7: ('alinea.caribu.data', 'maize.8'),
   8: ('alinea.caribu.data', 'par.opt'),
   9: ('alinea.caribu.data', 'zenith.light'),
   10: ('alinea.caribu', 'selectOutput'),
   11: ('alinea.caribu', 'addSoil'),
   12: ('alinea.caribu.data', 'filterT.can'),
   13: ('alinea.caribu', 'selectOutput'),
   14: ('alinea.caribu', 'Scattering Options'),
   15: ('alinea.caribu', 'S2v'),
   16: ('alinea.caribu', 'MCSail'),
   17: ('alinea.caribu', 'Canestra'),
   18: ('alinea.caribu', 'GenOutput'),
   19: ('alinea.caribu', 'filterby'),
   20: ('system', 'X'),
   21: ('openalea.math', 'not'),
   22: ('openalea.data structure', '#list'),
   24: ('openalea.functional', 'map'),
   25: ('openalea.functional', 'function')},
                             elt_connections={  9918844: (24, 0, 5, 1),
   9918856: (10, 0, 24, 1),
   9918880: (13, 0, 19, 0),
   9918892: (2, 0, 15, 0),
   9918904: (14, 5, 17, 4),
   9918916: (10, 0, 19, 1),
   9918928: (11, 0, 2, 0),
   9918940: (14, 4, 17, 3),
   9918952: (18, 0, 10, 0),
   9918964: (16, 0, 17, 1),
   9918976: (8, 0, 3, 3),
   9918988: (20, 0, 21, 0),
   9919000: (3, 0, 11, 0),
   9919012: (17, 1, 18, 0),
   9919024: (21, 0, 19, 2),
   9919036: (2, 0, 17, 0),
   9919048: (14, 2, 16, 1),
   9919060: (19, 0, 22, 0),
   9919072: (14, 0, 15, 1),
   9919084: (15, 0, 16, 0),
   9919096: (6, 0, 3, 0),
   9919108: (14, 1, 15, 2),
   9919120: (14, 2, 15, 3),
   9919132: (25, 0, 24, 0),
   9919144: (14, 3, 17, 2),
   9919156: (18, 0, 13, 0),
   9919168: (7, 0, 3, 2),
   9919180: (17, 0, 5, 0),
   9919192: (17, 2, 18, 1),
   9919204: (9, 0, 3, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'Periodise',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 106.25,
         'posy': 325.0,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'FileCaribuScene',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 90.0,
         'posy': 176.25,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'Plot CaribuScene',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 612.5,
         'posy': 330.0,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'ViewMapOnCan',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 702.5,
         'posy': 650.0,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'f331s1_100plantes.can',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': -21.25,
         'posy': 16.25,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'maize.8',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 205.0,
         'posy': 17.5,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'par.opt',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 271.25,
         'posy': 66.25,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'zenith.light',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 88.75,
         'posy': 67.5,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'selectOutput',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 553.75,
          'posy': 770.0,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'addSoil',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 126.25,
          'posy': 233.75,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': 'filterT.can',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': 2.5,
          'posy': 93.75,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'selectOutput',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 345.0,
          'posy': 766.25,
          'priority': 0,
          'user_application': None},
   14: {  'block': False,
          'caption': 'Scattering Options',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 253.75,
          'posy': 311.25,
          'priority': 0,
          'user_application': None},
   15: {  'block': False,
          'caption': 'S2v',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 233.75,
          'posy': 388.75,
          'priority': 0,
          'user_application': None},
   16: {  'block': False,
          'caption': 'MCSail',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 281.25,
          'posy': 431.25,
          'priority': 0,
          'user_application': None},
   17: {  'block': False,
          'caption': 'Canestra',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 293.75,
          'posy': 531.25,
          'priority': 0,
          'user_application': None},
   18: {  'block': False,
          'caption': 'GenOutput',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 401.25,
          'posy': 646.25,
          'priority': 0,
          'user_application': None},
   19: {  'block': False,
          'caption': 'filterby',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 500.0,
          'posy': 882.5,
          'priority': 0,
          'user_application': None},
   20: {  'block': False,
          'caption': 'X1',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 716.25,
          'posy': 752.5,
          'priority': 0,
          'user_application': None},
   21: {  'block': False,
          'caption': 'not',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 725.0,
          'posy': 853.75,
          'priority': 0,
          'user_application': None},
   22: {  'block': False,
          'caption': 'list',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 516.25,
          'posy': 941.25,
          'priority': 0,
          'user_application': None},
   24: {  'block': False,
          'caption': 'map',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 750.0,
          'posy': 548.75,
          'priority': 0,
          'user_application': None},
   25: {  'block': False,
          'caption': 'function',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 710.0,
          'posy': 475.0,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [],
   3: [],
   4: [(0, 'None')],
   5: [(0, '<60241864.FileCaribuScene object at 0x06ADCA70>')],
   6: [  (0, 'PackageData(alinea.caribu.data, f331s1_100plantes.can)'),
         (1, 'None'),
         (2, 'None')],
   7: [  (0, 'PackageData(alinea.caribu.data, maize.8)'),
         (1, 'None'),
         (2, 'None')],
   8: [  (0, 'PackageData(alinea.caribu.data, par.opt)'),
         (1, 'None'),
         (2, 'None')],
   9: [  (0, 'PackageData(alinea.caribu.data, zenith.light)'),
         (1, 'None'),
         (2, 'None')],
   10: [(1, "'Eabsm2'")],
   11: [],
   12: [  (0, 'PackageData(alinea.caribu.data, filterT.can)'),
          (1, 'None'),
          (2, 'None')],
   13: [(1, "'Opt'")],
   14: [  (0, 'True'),
          (1, "{'SphereDiameter': 0.5, 'Nz': 5, 'Zmax': 2, 'keepFF': False}")],
   15: [],
   16: [],
   17: [],
   18: [],
   19: [],
   20: [(0, "'x'")],
   21: [],
   22: [],
   24: [],
   25: [  (  0,
             "'from math import log\\ndef f(x):\\n    if x > 0:\\n       return log(x)\\n    else:\\n        return log(1e-3)'")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




WriteCan_WriteCan = Factory(name='WriteCan',
                description='',
                category='io',
                nodemodule='WriteCan',
                nodeclass='WriteCan',
                inputs=[{'interface': IInterface, 'name': 'CaribuScene', 'value': None, 'desc': ''}, {'interface': IFileStr, 'name': 'filename', 'value': None, 'desc': ''}],
                outputs=[{'interface': IFileStr, 'name': 'filename', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




Tutorial = CompositeNodeFactory(name='Tutorial',
                             description='',
                             category='composite,tutorial',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('alinea.caribu', 'Caribu'),
   3: ('alinea.caribu', 'FileCaribuScene'),
   4: ('alinea.caribu.visualisation', 'Plot CaribuScene'),
   5: ('alinea.caribu.visualisation', 'ViewMapOnCan'),
   6: ('alinea.caribu.data', 'f331s1_100plantes.can'),
   7: ('alinea.caribu.data', 'maize.8'),
   8: ('alinea.caribu.data', 'par.opt'),
   9: ('alinea.caribu.data', 'zenith.light'),
   10: ('alinea.adel.wheat', 'Write_Table'),
   11: ('alinea.caribu', 'LIE'),
   12: ('alinea.caribu', 'addSoil'),
   13: ('alinea.caribu', 'selectOutput')},
                             elt_connections={  9988868: (3, 0, 4, 0),
   9988880: (12, 0, 2, 0),
   9988892: (13, 0, 5, 1),
   9988904: (6, 0, 3, 0),
   9988916: (8, 0, 3, 3),
   9988928: (2, 0, 5, 0),
   9988940: (3, 0, 12, 0),
   9988952: (2, 0, 11, 0),
   9988964: (9, 0, 3, 1),
   9988976: (2, 1, 13, 0),
   9988988: (2, 1, 11, 1),
   9989000: (7, 0, 3, 2),
   9989012: (2, 1, 10, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'Caribu',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 136.25,
         'posy': 431.25,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'FileCaribuScene',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 90.0,
         'posy': 176.25,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'Plot CaribuScene',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -85.0,
         'posy': 365.0,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'ViewMapOnCan',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 313.75,
         'posy': 573.75,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'f331s1_100plantes.can',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': -21.25,
         'posy': 16.25,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'maize.8',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 205.0,
         'posy': 17.5,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'par.opt',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 271.25,
         'posy': 66.25,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'zenith.light',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 88.75,
         'posy': 67.5,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'Write_Table',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 577.49999999999989,
          'posy': 472.49999999999989,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'LIE',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 141.25,
          'posy': 573.75,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': 'addSoil',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 108.75,
          'posy': 297.5,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'selectOutput',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 350.0,
          'posy': 485.0,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [  (1, 'True'),
         (2, "{'SphereDiameter': 0.5, 'Nz': 5, 'Zmax': 2, 'keepFF': False}")],
   3: [],
   4: [],
   5: [(2, '0.20000000000000001')],
   6: [  (0, 'PackageData(alinea.caribu.data, f331s1_100plantes.can)'),
         (1, 'None'),
         (2, 'None')],
   7: [  (0, 'PackageData(alinea.caribu.data, maize.8)'),
         (1, 'None'),
         (2, 'None')],
   8: [  (0, 'PackageData(alinea.caribu.data, par.opt)'),
         (1, 'None'),
         (2, 'None')],
   9: [  (0, 'PackageData(alinea.caribu.data, zenith.light)'),
         (1, 'None'),
         (2, 'None')],
   10: [(1, 'None')],
   11: [],
   12: [],
   13: [(1, "'EiSup'")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




