package:
  name: alinea.adel
  version: "2.0.1"

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: {{PYTHON}} -m pip install .

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
    - openalea.deploy
  run:
    - python >=3.6
    - openalea.mtg
    - scipy
    - rpy2
    - alinea.caribu
    - alinea.astk

test:
  requires:
    - pytest
  imports:
    - alinea.adel
  source_files:
    - test/**
    - test/data/**
  commands:
    - cd test
    - pytest -v --ignore=test_povray.py --ignore=test_dataflow.py --ignore=test_plantgen.py

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

