# -*-python-*-

import os

Import( "env" )

lib_env = env.Clone(static=True)
# lib_env.Prepend(CPPPATH='../include')

# Import/Export symbols for windows
if lib_env['compiler'] == 'mingw':
    lib_env.AppendUnique(CPPDEFINES=['MINGW','WIN32'])

sources = lib_env.ALEAGlob("*.c")

lib, install_lib = lib_env.ALEALibrary("meschach", sources)
Return('lib')
