# -*-python-*-

Import("env")
Import("bibliotek")

lib_env = env.Clone()

# Import/Export symbols for windows
if lib_env['compiler'] == 'mingw':
    lib_env.AppendUnique(CPPDEFINES=['MINGW','WIN32'])
#    LINKFLAGS=["-enable-stdcall-fixup",
#               "-enable-auto-import",
#               "-enable-runtime-pseudo-reloc",
#               "-s"]
#    lib_env.AppendUnique(LINKFLAGS=LINKFLAGS)
#    lib_env.AppendUnique(CPPDEFINES=['BCC32','WIN32'])

sources = """
msail.cpp
multicou.cpp
profil.cpp
"""
sources = lib_env.Split(sources)
sources.append(bibliotek)

lib_env.ALEAProgram("mcsail", sources)
