from openalea.core import CompositeNodeFactory as CNF
from openalea.core import IFunction, ISequence, IStr

__name__ = 'alinea.adel.Applications.Avignon'

__editable__ = True
__description__ = 'Application for Avignon'
__license__ = 'CECILL'
__url__ = ''
__alias__ = []
__version__ = '0.0.1'
__authors__ = 'C. Fournier, C. Pradal'
__institutes__ = 'INRA, CIRAD'
__icon__ = ''

__all__ = ['buildname', 'writecan', '_182572748', '_174394508', '_174658092']

buildname = CNF(uid="175664ea4f2011e6b469d4bed973e64a",
                name='buildname',
                description='',
                category='Unclassified',
                doc='',
                inputs=[{'interface': ISequence,
                         'name': 'String List(join)',
                         'value': ['Mycan', '2']},
                        {'interface': IStr, 'name': 'Join Char(join)',
                         'value': '\n'},
                        {'interface': IStr, 'name': "String('2')", 'value': 2},
                        {'interface': ISequence,
                         'name': 'a(joinpath)',
                         'value': ['D:/ADEL', 'Mycan2']}],
                outputs=[{'interface': IStr, 'name': 'path(joinpath)'}],
                elt_factory={32: ('openalea.data structure.string', 'join'),
                             37: ('openalea.data structure.string', 'string'),
                             39: ('openalea.file', 'joinpath')},
                elt_connections={9919740: (39, 0, '__out__', 0),
                                 9919752: ('__in__', 3, 39, 0),
                                 9919764: ('__in__', 1, 32, 1),
                                 9919776: (37, 0, 32, 0),
                                 9919788: (32, 0, 39, 0),
                                 9919800: ('__in__', 2, 37, 0),
                                 9919812: ('__in__', 0, 32, 0)},
                elt_data={32: {'block': False,
                               'caption': 'join',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 43.018241294362468,
                               'posy': -78.194446967168929,
                               'priority': 0,
                               'user_application': None},
                          37: {'block': False,
                               'caption': "'2'",
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 9.9228845329274407,
                               'posy': -200.63930623875768,
                               'priority': 0,
                               'user_application': None},
                          39: {'block': False,
                               'caption': 'joinpath',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 135.81591967508001,
                               'posy': -13.844944457015107,
                               'priority': 0,
                               'user_application': None},
                          '__in__': {'block': False,
                                     'caption': 'In',
                                     'hide': True,
                                     'lazy': True,
                                     'port_hide_changed': set(),
                                     'posx': 79.396351741127518,
                                     'posy': -291.9817587056375,
                                     'priority': 0,
                                     'user_application': None},
                          '__out__': {'block': False,
                                      'caption': 'Out',
                                      'hide': True,
                                      'lazy': True,
                                      'port_hide_changed': set(),
                                      'posx': 151.54353263199877,
                                      'posy': 87.885985098878621,
                                      'priority': 0,
                                      'user_application': None}},
                elt_value={32: [], 37: [], 39: [], '__in__': [], '__out__': []},
                elt_ad_hoc={},
                lazy=True,
                )

writecan = CNF(uid="175664eb4f2011e6b469d4bed973e64a",
               name='writecan',
               description='',
               category='Unclassified',
               doc='',
               inputs=[],
               outputs=[],
               elt_factory={2: ('alinea.adel.data', 'Arvalis.RData'),
                            3: ('alinea.adel.io', 'readRData'),
                            4: ('openalea.python method', 'getitem'),
                            5: ('openalea.data structure.string', 'string'),
                            6: ('alinea.adel.io', 'RlistAsDict'),
                            7: ('openalea.python method', 'getitem'),
                            8: ('alinea.adel.parameterisation', 'setAdelArv'),
                            9: ('alinea.adel.simulation', 'RunAdel'),
                            10: ('openalea.python method', 'range'),
                            11: ('alinea.adel.wheat', 'CanMTGInterpreter'),
                            12: ('alinea.adel.stand', 'agronomic plot'),
                            13: ('alinea.adel.wheat.data', 'SRSo.RData'),
                            14: ('openalea.python method', 'getitem'),
                            15: ('openalea.data structure', 'int'),
                            16: ('alinea.adel.macro', 'plot'),
                            17: ('alinea.caribu', 'CaribuZenithPar'),
                            18: ('alinea.adel.fitting', 'fit leaves'),
                            19: ('openalea.data structure', 'int'),
                            20: ('alinea.adel.wheat.data', 'So99.RData'),
                            21: ('alinea.adel.macro', 'plot'),
                            22: ('openalea.flow control', 'annotation'),
                            23: ('alinea.adel.geometry', 'symbols'),
                            24: ('alinea.adel.stand', 'CanMTGPlanter'),
                            25: ('alinea.adel.io', 'to_canestra'),
                            26: ('alinea.adel.wheat', 'extract_leaves'),
                            27: ('alinea.caribu', 'selectOutput'),
                            28: ('alinea.caribu.visualisation', 'ViewMapOnCan'),
                            29: ('alinea.caribu', 'LIE'),
                            30: ('openalea.flow control', 'X'),
                            31: ('openalea.function operator', 'map'),
                            32: ('openalea.data structure.string', 'join'),
                            33: ('openalea.data structure.string', 'string'),
                            34: ('openalea.file', 'write'),
                            35: ('alinea.adel.io', 'to_canestra'),
                            36: ('openalea.python method', 'range'),
                            37: ('openalea.data structure.string', 'string'),
                            38: ('openalea.file', 'dirname'),
                            39: ('openalea.file', 'joinpath'),
                            40: ('openalea.file', 'read'),
                            41: ('alinea.adel.data', 'Rfun.R')},
               elt_connections={9916232: (7, 0, 8, 0),
                                9916244: (11, 0, 21, 0),
                                9916256: (10, 0, 9, 0),
                                9916268: (12, 1, 24, 1),
                                9916280: (38, 0, 39, 0),
                                9916292: (11, 0, 35, 0),
                                9916304: (36, 0, 31, 1),
                                9916316: (33, 0, 32, 0),
                                9916328: (40, 0, 8, 1),
                                9916340: (6, 0, 7, 0),
                                9916352: (26, 0, 18, 0),
                                9916364: (18, 0, 23, 0),
                                9916376: (41, 0, 40, 0),
                                9916388: (24, 0, 25, 0),
                                9916400: (30, 0, 14, 1),
                                9916412: (19, 0, 18, 1),
                                9916424: (34, 0, 31, 0),
                                9916436: (17, 1, 29, 1),
                                9916448: (17, 0, 29, 0),
                                9916460: (3, 0, 4, 0),
                                9916472: (5, 0, 4, 1),
                                9916484: (32, 0, 39, 0),
                                9916496: (2, 0, 3, 0),
                                9916508: (24, 0, 16, 0),
                                9916520: (8, 0, 9, 1),
                                9916532: (12, 2, 17, 1),
                                9916544: (4, 0, 6, 0),
                                9916556: (20, 0, 26, 0),
                                9916568: (14, 0, 11, 1),
                                9916580: (23, 0, 11, 0),
                                9916592: (39, 0, 34, 1),
                                9916604: (35, 0, 34, 0),
                                9916616: (17, 0, 28, 0),
                                9916628: (30, 0, 37, 0),
                                9916640: (17, 1, 27, 0),
                                9916652: (9, 0, 14, 0),
                                9916664: (27, 0, 28, 1),
                                9916676: (13, 0, 26, 1),
                                9916688: (37, 0, 32, 0),
                                9916700: (24, 0, 17, 0),
                                9916712: (11, 0, 24, 0),
                                9916724: (12, 0, 8, 2)},
               elt_data={2: {'block': False,
                             'caption': 'Arvalis.RData',
                             'hide': True,
                             'lazy': True,
                             'port_hide_changed': set([2]),
                             'posx': 47.500000000000028,
                             'posy': 28.750000000000007,
                             'priority': 0,
                             'user_application': None},
                         3: {'block': False,
                             'caption': 'readRData',
                             'hide': True,
                             'lazy': True,
                             'port_hide_changed': set(),
                             'posx': 54.999999999999972,
                             'posy': 93.750000000000028,
                             'priority': 0,
                             'user_application': None},
                         4: {'block': False,
                             'caption': 'getitem',
                             'hide': True,
                             'lazy': True,
                             'port_hide_changed': set(),
                             'posx': 121.24999999999997,
                             'posy': 162.49999999999997,
                             'priority': 0,
                             'user_application': None},
                         5: {'block': False,
                             'caption': "'Calagedb'",
                             'hide': True,
                             'lazy': True,
                             'port_hide_changed': set(),
                             'posx': 183.74999999999994,
                             'posy': 93.750000000000014,
                             'priority': 0,
                             'user_application': None},
                         6: {'block': False,
                             'caption': 'RlistAsDict',
                             'hide': True,
                             'lazy': True,
                             'port_hide_changed': set(),
                             'posx': 110.0,
                             'posy': 223.74999999999994,
                             'priority': 0,
                             'user_application': None},
                         7: {'block': False,
                             'caption': 'getitem',
                             'hide': True,
                             'lazy': True,
                             'port_hide_changed': set(),
                             'posx': 128.74999999999991,
                             'posy': 277.49999999999994,
                             'priority': 0,
                             'user_application': None},
                         8: {'block': False,
                             'caption': 'setAdelArv',
                             'hide': True,
                             'lazy': True,
                             'port_hide_changed': set(),
                             'posx': 273.75,
                             'posy': 398.75,
                             'priority': 0,
                             'user_application': None},
                         9: {'block': False,
                             'caption': 'RunAdel',
                             'hide': True,
                             'lazy': True,
                             'port_hide_changed': set(),
                             'posx': 281.4898989898989,
                             'posy': 517.38636363636351,
                             'priority': 0,
                             'user_application': None},
                         10: {'block': False,
                              'caption': 'range',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 150.11363636363629,
                              'posy': 455.40404040404024,
                              'priority': 0,
                              'user_application': None},
                         11: {'block': False,
                              'caption': 'CanMTGInterpreter',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 178.24494949494931,
                              'posy': 662.14646464646432,
                              'priority': 0,
                              'user_application': None},
                         12: {'block': False,
                              'caption': 'agronomic plot',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 474.99999999999989,
                              'posy': 256.24999999999994,
                              'priority': 0,
                              'user_application': None},
                         13: {'block': False,
                              'caption': 'SRSo.RData',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set([2]),
                              'posx': -111.25000000000001,
                              'posy': 269.99999999999994,
                              'priority': 0,
                              'user_application': None},
                         14: {'block': False,
                              'caption': 'getitem',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 334.99999999999994,
                              'posy': 583.88888888888869,
                              'priority': 0,
                              'user_application': None},
                         15: {'block': False,
                              'caption': '2',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 471.25,
                              'posy': 592.5,
                              'priority': 0,
                              'user_application': None},
                         16: {'block': False,
                              'caption': 'plot',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 370.93267141093884,
                              'posy': 1026.8172057806619,
                              'priority': 0,
                              'user_application': None},
                         17: {'block': False,
                              'caption': 'CaribuZenithPar',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 590.85510178595916,
                              'posy': 940.72970317656223,
                              'priority': 0,
                              'user_application': None},
                         18: {'block': False,
                              'caption': 'fit leaves',
                              'hide': True,
                              'lazy': True,
                              'minimal': False,
                              'port_hide_changed': set(),
                              'posx': -146.24999999999989,
                              'posy': 473.74999999999966,
                              'priority': 0,
                              'user_application': None},
                         19: {'block': False,
                              'caption': '9',
                              'hide': True,
                              'lazy': True,
                              'minimal': False,
                              'port_hide_changed': set(),
                              'posx': -17.49999999999995,
                              'posy': 318.74999999999994,
                              'priority': 0,
                              'user_application': None},
                         20: {'block': False,
                              'caption': 'So99.RData',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set([2]),
                              'posx': -227.50000000000003,
                              'posy': 269.99999999999994,
                              'priority': 0,
                              'user_application': None},
                         21: {'block': False,
                              'caption': 'plot',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 140.0,
                              'posy': 780.0,
                              'priority': 0,
                              'user_application': False},
                         22: {'posx': 1.2500000000000568,
                              'posy': 448.74999999999994, 'txt': ''},
                         23: {'block': False,
                              'caption': 'symbols',
                              'hide': True,
                              'lazy': True,
                              'minimal': False,
                              'port_hide_changed': set(),
                              'posx': -137.49999999999994,
                              'posy': 534.99999999999966,
                              'priority': 0,
                              'user_application': None},
                         24: {'block': False,
                              'caption': 'CanMTGPlanter',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 472.49999999999989,
                              'posy': 741.24999999999989,
                              'priority': 0,
                              'user_application': None},
                         25: {'block': False,
                              'caption': 'to_canestra',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 82.034278336526484,
                              'posy': 1025.0064381187481,
                              'priority': 0,
                              'user_application': None},
                         26: {'block': False,
                              'caption': 'extract_leaves',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': -175.0,
                              'posy': 365.0,
                              'priority': 0,
                              'user_application': None},
                         27: {'block': False,
                              'caption': 'selectOutput',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 796.31622331346807,
                              'posy': 1008.6672161970596,
                              'priority': 0,
                              'user_application': None},
                         28: {'block': False,
                              'caption': 'ViewMapOnCan',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 772.72166854862462,
                              'posy': 1114.8427126388553,
                              'priority': 0,
                              'user_application': None},
                         29: {'block': False,
                              'caption': 'LIE',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 619.35706257714219,
                              'posy': 1169.8966737568235,
                              'priority': 0,
                              'user_application': None},
                         30: {'block': False,
                              'caption': 'X0',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 388.75,
                              'posy': 516.25,
                              'priority': 0,
                              'user_application': None},
                         31: {'block': False,
                              'caption': 'map',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 215.44941897853272,
                              'posy': 863.82490316308872,
                              'priority': 0,
                              'user_application': None},
                         32: {'block': False,
                              'caption': 'join',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 430.0,
                              'posy': 673.75,
                              'priority': 0,
                              'user_application': None},
                         33: {'block': False,
                              'caption': "'Mycan'",
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 353.82490316308883,
                              'posy': 629.91261297639642,
                              'priority': 0,
                              'user_application': None},
                         34: {'block': False,
                              'caption': 'write',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 338.75,
                              'posy': 810.0,
                              'priority': 0,
                              'user_application': None},
                         35: {'block': False,
                              'caption': 'to_canestra',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 245.95038734764489,
                              'posy': 739.97503227897062,
                              'priority': 0,
                              'user_application': None},
                         36: {'block': False,
                              'caption': 'range',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 210.0,
                              'posy': 788.75,
                              'priority': 0,
                              'user_application': None},
                         37: {'block': False,
                              'caption': "'2'",
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 426.25,
                              'posy': 591.25,
                              'priority': 0,
                              'user_application': None},
                         38: {'block': False,
                              'caption': 'dirname',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 495.53035020805544,
                              'posy': 648.52690445925384,
                              'priority': 0,
                              'user_application': None},
                         39: {'block': False,
                              'caption': 'joinpath',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set(),
                              'posx': 373.95738378319101,
                              'posy': 734.61461427256143,
                              'priority': 0,
                              'user_application': None},
                         40: {'block': False,
                              'caption': 'read',
                              'hide': True,
                              'lazy': False,
                              'port_hide_changed': set(),
                              'posx': 308.74999999999994,
                              'posy': 278.74999999999989,
                              'priority': 0,
                              'user_application': None},
                         41: {'block': False,
                              'caption': 'Rfun.R',
                              'hide': True,
                              'lazy': True,
                              'port_hide_changed': set([2]),
                              'posx': 541.24999999999977,
                              'posy': 28.75,
                              'priority': 0,
                              'user_application': None},
                         '__in__': {'block': False,
                                    'caption': 'In',
                                    'hide': True,
                                    'lazy': True,
                                    'port_hide_changed': set(),
                                    'posx': 20.0,
                                    'posy': 5.0,
                                    'priority': 0,
                                    'user_application': None},
                         '__out__': {'block': False,
                                     'caption': 'Out',
                                     'hide': True,
                                     'lazy': True,
                                     'port_hide_changed': set(),
                                     'posx': 20.0,
                                     'posy': 250.0,
                                     'priority': 0,
                                     'user_application': None}},
               elt_value={
                   2: [(0, 'PackageData(alinea.adel.data, Arvalis.RData)'),
                       (1, 'None'),
                       (2, 'None')],
                   3: [],
                   4: [],
                   5: [(0, "'Calagedb'")],
                   6: [],
                   7: [(1, "'Vra08.s2d2'")],
                   8: [(3, '20')],
                   9: [],
                   10: [(0, '0'), (1, '3000'), (2, '1000')],
                   11: [],
                   12: [(0, '0.5'),
                        (1, '0.5'),
                        (2, '150'),
                        (3, '130.0'),
                        (4, '0.125'),
                        (5, '1.0'),
                        (6, '100')],
                   13: [(0, 'PackageData(alinea.adel.wheat.data, SRSo.RData)'),
                        (1, 'None'),
                        (2, 'None')],
                   14: [],
                   15: [(0, '2')],
                   16: [],
                   17: [],
                   18: [],
                   19: [(0, '9')],
                   20: [(0, 'PackageData(alinea.adel.wheat.data, So99.RData)'),
                        (1, 'None'),
                        (2, 'None')],
                   21: [],
                   22: [],
                   23: [],
                   24: [],
                   25: [],
                   26: [],
                   27: [(1, "'EiSup'")],
                   28: [(2, '0.20000000000000001')],
                   29: [],
                   30: [(0, "'x'")],
                   31: [],
                   32: [(1, "''")],
                   33: [(0, "'Mycan'")],
                   34: [(2, "'w'")],
                   35: [],
                   36: [(0, '0'), (1, '3'), (2, '1')],
                   37: [],
                   38: [(0, "'D:/ADEL'")],
                   39: [],
                   40: [],
                   41: [(0, 'PackageData(alinea.adel.data, Rfun.R)'),
                        (1, 'None'),
                        (2, 'None')],
                   '__in__': [],
                   '__out__': []},
               elt_ad_hoc={},
               lazy=True,
               )

_182572748 = CNF(uid="175664ec4f2011e6b469d4bed973e64a",
                 name='test_groimp',
                 description='',
                 category='Unclassified',
                 doc='',
                 inputs=[{'interface': None,
                          'name': 'InitValue(for)',
                          'value': '<graph>\r\n <root root_id="1"/>\r\n</graph>\r\n\r\n'},
                         {'interface': ISequence, 'name': 'list(for)',
                          'value': [0]},
                         {'interface': IFunction, 'name': 'Function(for)',
                          'value': None}],
                 outputs=[{'interface': None, 'name': 'Result(for)'}],
                 elt_factory={18: ('openalea.flow control', 'for')},
                 elt_connections={170132300: ('__in__', 0, 18, 0),
                                  179162524: ('__in__', 1, 18, 1),
                                  181946724: (18, 0, '__out__', 0),
                                  181947084: ('__in__', 2, 18, 2)},
                 elt_data={18: {'block': False,
                                'caption': 'for',
                                'hide': True,
                                'is_in_error_state': False,
                                'is_user_application': False,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 22.167508417508415,
                                'posy': 555.65796857463533,
                                'priority': 0,
                                'use_user_color': False,
                                'user_application': None,
                                'user_color': None}},
                 elt_value={18: []},
                 elt_ad_hoc={
                     18: {'position': [22.167508417508415, 555.65796857463533],
                          'userColor': None, 'useUserColor': False}},
                 lazy=True,
                 )

_174394508 = CNF(uid="175664ed4f2011e6b469d4bed973e64a",
                 name='Output of the file can',
                 description='Output of the file can and index of leaf',
                 category='demo',
                 doc='',
                 inputs=[],
                 outputs=[],
                 elt_factory={2: ('alinea.adel.data', 'Arvalis.RData'),
                              3: ('alinea.adel.io', 'readRData'),
                              4: ('openalea.python method', 'getitem'),
                              5: ('openalea.data structure.string', 'string'),
                              6: ('alinea.adel.io', 'RlistAsDict'),
                              7: ('openalea.python method', 'getitem'),
                              8: ('alinea.adel.parameterisation', 'setAdelArv'),
                              9: ('alinea.adel.simulation', 'RunAdel'),
                              10: ('openalea.python method', 'range'),
                              11: ('alinea.adel.wheat', 'CanMTGInterpreter'),
                              12: ('alinea.adel.stand', 'agronomic plot'),
                              13: ('alinea.adel.wheat.data', 'SRSo.RData'),
                              14: ('openalea.python method', 'getitem'),
                              15: ('openalea.data structure', 'int'),
                              16: ('alinea.adel.macro', 'plot'),
                              17: ('alinea.caribu', 'CaribuZenithPar'),
                              18: ('alinea.adel.fitting', 'fit leaves'),
                              19: ('openalea.data structure', 'int'),
                              20: ('alinea.adel.wheat.data', 'So99.RData'),
                              21: ('alinea.adel.macro', 'plot'),
                              22: ('openalea.flow control', 'annotation'),
                              23: ('alinea.adel.geometry', 'symbols'),
                              24: ('alinea.adel.stand', 'CanMTGPlanter'),
                              25: ('alinea.adel.io', 'to_canestra'),
                              26: ('alinea.adel.wheat', 'extract_leaves'),
                              27: ('alinea.caribu', 'selectOutput'),
                              28: (
                                  'alinea.caribu.visualisation',
                                  'ViewMapOnCan'),
                              30: ('openalea.file', 'read'),
                              31: ('alinea.adel.data', 'Rfun.R'),
                              32: ('openalea.flow control', 'annotation'),
                              33: ('alinea.adel.data', 'mais.RData'),
                              34: ('alinea.adel.data', 'leaves.db'),
                              35: ('alinea.adel.io', 'load leaf data'),
                              36: ('alinea.adel.io', 'readRData'),
                              37: ('openalea.python method', 'getitem'),
                              38: ('alinea.adel.io', 'RlistAsDict'),
                              39: ('openalea.python method', 'getitem'),
                              40: ('alinea.adel.wheat', 'To_Aggregation_Table'),
                              41: ('openalea.flow control', 'annotation'),
                              42: ('openalea.flow control', 'annotation'),
                              43: ('openalea.file', 'write'),
                              44: ('alinea.caribu', 'Periodise'),
                              45: ('alinea.adel.wheat', 'Write_Table'),
                              46: ('openalea.flow control', 'annotation'),
                              47: ('openalea.file', 'write'),
                              48: ('openalea.flow control', 'annotation'),
                              49: ('openalea.flow control', 'annotation'),
                              50: ('alinea.caribu', 'ObjCaribuScene'),
                              52: ('alinea.caribu', 'WriteCan')},
                 elt_connections={9916220: (24, 0, 40, 0),
                                  9916232: (24, 0, 50, 0),
                                  9916244: (19, 0, 18, 1),
                                  9916256: (12, 2, 50, 2),
                                  9916268: (12, 0, 8, 2),
                                  9916280: (12, 2, 17, 1),
                                  9916292: (26, 0, 18, 0),
                                  9916304: (38, 0, 39, 0),
                                  9916316: (11, 0, 24, 0),
                                  9916328: (44, 0, 52, 0),
                                  9916340: (12, 1, 24, 1),
                                  9916352: (25, 0, 43, 0),
                                  9916364: (31, 0, 30, 0),
                                  9916376: (8, 0, 9, 1),
                                  9916388: (30, 0, 8, 1),
                                  9916400: (3, 0, 4, 0),
                                  9916412: (18, 0, 23, 0),
                                  9916424: (12, 2, 47, 0),
                                  9916436: (36, 0, 37, 0),
                                  9916448: (17, 0, 28, 0),
                                  9916460: (2, 0, 3, 0),
                                  9916472: (20, 0, 26, 0),
                                  9916484: (13, 0, 26, 1),
                                  9916496: (11, 0, 21, 0),
                                  9916508: (10, 0, 9, 0),
                                  9916520: (37, 0, 38, 0),
                                  9916532: (23, 0, 11, 0),
                                  9916544: (24, 0, 25, 0),
                                  9916556: (24, 0, 17, 0),
                                  9916568: (17, 1, 27, 0),
                                  9916580: (50, 0, 44, 0),
                                  9916592: (9, 0, 14, 0),
                                  9916604: (40, 0, 45, 0),
                                  9916616: (14, 0, 11, 1),
                                  9916628: (7, 0, 8, 0),
                                  9916640: (4, 0, 6, 0),
                                  9916652: (27, 0, 28, 1),
                                  9916664: (24, 0, 16, 0),
                                  9916676: (33, 0, 36, 0),
                                  9916688: (15, 0, 14, 1),
                                  9916700: (34, 0, 35, 0),
                                  9916712: (6, 0, 7, 0),
                                  9916724: (5, 0, 4, 1)},
                 elt_data={2: {'block': False,
                               'caption': 'Arvalis.RData',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set([2]),
                               'posx': 47.500000000000028,
                               'posy': 28.750000000000007,
                               'priority': 0,
                               'user_application': None},
                           3: {'block': False,
                               'caption': 'readRData',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 54.999999999999972,
                               'posy': 93.750000000000028,
                               'priority': 0,
                               'user_application': None},
                           4: {'block': False,
                               'caption': 'getitem',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 123.74999999999997,
                               'posy': 162.49999999999997,
                               'priority': 0,
                               'user_application': None},
                           5: {'block': False,
                               'caption': "'Calagedb'",
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 183.74999999999994,
                               'posy': 93.750000000000014,
                               'priority': 0,
                               'user_application': None},
                           6: {'block': False,
                               'caption': 'RlistAsDict',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 110.0,
                               'posy': 223.74999999999994,
                               'priority': 0,
                               'user_application': None},
                           7: {'block': False,
                               'caption': 'getitem',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 127.49999999999991,
                               'posy': 281.24999999999994,
                               'priority': 0,
                               'user_application': None},
                           8: {'block': False,
                               'caption': 'setAdelArv',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 333.75,
                               'posy': 400.0,
                               'priority': 0,
                               'user_application': None},
                           9: {'block': False,
                               'caption': 'RunAdel',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 281.4898989898989,
                               'posy': 517.38636363636351,
                               'priority': 0,
                               'user_application': None},
                           10: {'block': False,
                                'caption': 'range',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 150.11363636363629,
                                'posy': 455.40404040404024,
                                'priority': 0,
                                'user_application': None},
                           11: {'block': False,
                                'caption': 'CanMTGInterpreter',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 136.37424305195469,
                                'posy': 659.9427432547277,
                                'priority': 0,
                                'user_application': None},
                           12: {'block': False,
                                'caption': 'agronomic plot',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 468.56503378968682,
                                'posy': 226.42271123792418,
                                'priority': 0,
                                'user_application': None},
                           13: {'block': False,
                                'caption': 'SRSo.RData',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set([2]),
                                'posx': -111.25000000000001,
                                'posy': 269.99999999999994,
                                'priority': 0,
                                'user_application': None},
                           14: {'block': False,
                                'caption': 'getitem',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 334.99999999999994,
                                'posy': 583.88888888888869,
                                'priority': 0,
                                'user_application': None},
                           15: {'block': False,
                                'caption': '1',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 413.74999999999994,
                                'posy': 518.74999999999989,
                                'priority': 0,
                                'user_application': None},
                           16: {'block': False,
                                'caption': 'plot',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 364.92597121854163,
                                'posy': 1010.9609523929568,
                                'priority': 0,
                                'user_application': False},
                           17: {'block': False,
                                'caption': 'CaribuZenithPar',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 497.76254456943229,
                                'posy': 892.50737482614284,
                                'priority': 0,
                                'user_application': None},
                           18: {'block': False,
                                'caption': 'fit leaves',
                                'hide': True,
                                'lazy': True,
                                'minimal': False,
                                'port_hide_changed': set(),
                                'posx': -146.24999999999989,
                                'posy': 473.74999999999966,
                                'priority': 0,
                                'user_application': None},
                           19: {'block': False,
                                'caption': '18',
                                'hide': True,
                                'lazy': True,
                                'minimal': False,
                                'port_hide_changed': set(),
                                'posx': 10.246531656668065,
                                'posy': 364.99421942777997,
                                'priority': 0,
                                'user_application': None},
                           20: {'block': False,
                                'caption': 'So99.RData',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set([2]),
                                'posx': -227.50000000000003,
                                'posy': 269.99999999999994,
                                'priority': 0,
                                'user_application': None},
                           21: {'block': False,
                                'caption': 'plot',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 78.295801031376413,
                                'posy': 729.31440799005918,
                                'priority': 0,
                                'user_application': False},
                           22: {'posx': 1.2500000000000568,
                                'posy': 448.74999999999994, 'txt': ''},
                           23: {'block': False,
                                'caption': 'symbols',
                                'hide': True,
                                'lazy': True,
                                'minimal': False,
                                'port_hide_changed': set(),
                                'posx': -137.49999999999994,
                                'posy': 534.99999999999966,
                                'priority': 0,
                                'user_application': None},
                           24: {'block': False,
                                'caption': 'CanMTGPlanter',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 472.49999999999989,
                                'posy': 741.24999999999989,
                                'priority': 0,
                                'user_application': None},
                           25: {'block': False,
                                'caption': 'to_canestra',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 167.96167883612341,
                                'posy': 1017.4506741110783,
                                'priority': 0,
                                'user_application': None},
                           26: {'block': False,
                                'caption': 'extract_leaves',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': -175.0,
                                'posy': 365.0,
                                'priority': 0,
                                'user_application': None},
                           27: {'block': False,
                                'caption': 'selectOutput',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 592.54666120101103,
                                'posy': 1024.1581515061619,
                                'priority': 0,
                                'user_application': None},
                           28: {'block': False,
                                'caption': 'ViewMapOnCan',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 527.08139999317348,
                                'posy': 1144.7410907314309,
                                'priority': 0,
                                'user_application': None},
                           30: {'block': False,
                                'caption': 'read',
                                'hide': True,
                                'lazy': False,
                                'port_hide_changed': set(),
                                'posx': 387.83433891962278,
                                'posy': 225.18284516754261,
                                'priority': 0,
                                'user_application': None},
                           31: {'block': False,
                                'caption': 'Rfun.R',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set([2]),
                                'posx': 679.33886753189825,
                                'posy': 143.75473319217684,
                                'priority': 0,
                                'user_application': None},
                           32: {'posx': 467.43574770285636,
                                'posy': 100.03046334574063,
                                'txt': "This file is an example of R functiions : don't modify it ! "},
                           33: {'block': False,
                                'caption': 'mais.RData',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set([2]),
                                'posx': 370.76818559107659,
                                'posy': 29.472721613385033,
                                'priority': 0,
                                'user_application': None},
                           34: {'block': False,
                                'caption': 'leaves.db',
                                'hide': True,
                                'lazy': True,
                                'minimal': False,
                                'port_hide_changed': set(),
                                'posx': -172.80170351559201,
                                'posy': 82.94873873169071,
                                'priority': 0,
                                'user_application': None},
                           35: {'block': False,
                                'caption': 'load leaf data',
                                'hide': True,
                                'lazy': True,
                                'minimal': False,
                                'port_hide_changed': set(),
                                'posx': -190.6500081841923,
                                'posy': 160.76992628208973,
                                'priority': 0,
                                'user_application': None},
                           36: {'block': False,
                                'caption': 'readRData',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 328.0500103754606,
                                'posy': 90.459082420077536,
                                'priority': 0,
                                'user_application': None},
                           37: {'block': False,
                                'caption': 'getitem',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 259.99999999999989,
                                'posy': 163.74999999999997,
                                'priority': 0,
                                'user_application': None},
                           38: {'block': False,
                                'caption': 'RlistAsDict',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 244.80455677322982,
                                'posy': 221.20453602230836,
                                'priority': 0,
                                'user_application': None},
                           39: {'block': False,
                                'caption': 'getitem',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 245.74545360223084,
                                'posy': 287.47726801115414,
                                'priority': 0,
                                'user_application': None},
                           40: {'block': False,
                                'caption': 'To_Aggregation_Table',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': -156.24999999999997,
                                'posy': 888.74999999999977,
                                'priority': 0,
                                'user_application': None},
                           41: {'posx': 898.74999999999989,
                                'posy': 1203.7499999999998, 'txt': ''},
                           42: {'posx': -162.3814937754907,
                                'posy': 1098.4702530540583,
                                'txt': 'choose all index of leaves'},
                           43: {'block': False,
                                'caption': 'write',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 201.3041294238871,
                                'posy': 1126.0098562683177,
                                'priority': 0,
                                'user_application': None},
                           44: {'block': False,
                                'caption': 'Periodise',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 823.9579430775583,
                                'posy': 1014.9262458248202,
                                'priority': 0,
                                'user_application': None},
                           45: {'block': False,
                                'caption': 'Write_Table',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': -101.43564101019909,
                                'posy': 1028.0701072977779,
                                'priority': 0,
                                'user_application': None},
                           46: {'posx': 287.52407574163118,
                                'posy': 1135.6175431060008,
                                'txt': 'file can'},
                           47: {'block': False,
                                'caption': 'write',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 703.53292861836655,
                                'posy': 400.83845544815773,
                                'priority': 0,
                                'user_application': None},
                           48: {'posx': 933.74999999999966,
                                'posy': 1123.7499999999998,
                                'txt': 'file can of Caribu'},
                           49: {'posx': 653.82670796941022,
                                'posy': 461.69640465371236,
                                'txt': 'write to the file scene '},
                           50: {'block': False,
                                'caption': 'ObjCaribuScene',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 794.05097787097202,
                                'posy': 894.12445055192882,
                                'priority': 0,
                                'user_application': None},
                           52: {'block': False,
                                'caption': 'WriteCan',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 828.69370154706428,
                                'posy': 1132.1755721652692,
                                'priority': 0,
                                'user_application': None},
                           '__in__': {'block': False,
                                      'caption': 'In',
                                      'hide': True,
                                      'lazy': True,
                                      'port_hide_changed': set(),
                                      'posx': 20.0,
                                      'posy': 5.0,
                                      'priority': 0,
                                      'user_application': None},
                           '__out__': {'block': False,
                                       'caption': 'Out',
                                       'hide': True,
                                       'lazy': True,
                                       'port_hide_changed': set(),
                                       'posx': 20.0,
                                       'posy': 250.0,
                                       'priority': 0,
                                       'user_application': None}},
                 elt_value={
                     2: [(0, 'PackageData(alinea.adel.data, Arvalis.RData)'),
                         (1, 'None'),
                         (2, 'None')],
                     3: [],
                     4: [],
                     5: [(0, "'Calagedb'")],
                     6: [],
                     7: [(1, "'Vra08.s2d2'")],
                     8: [(3, '20')],
                     9: [],
                     10: [(0, '0'), (1, '3000'), (2, '1000')],
                     11: [],
                     12: [(0, '1'),
                          (1, '1'),
                          (2, '150'),
                          (3, '100.0'),
                          (4, '0.12'),
                          (5, '0'),
                          (6, '100')],
                     13: [
                         (0, 'PackageData(alinea.adel.wheat.data, SRSo.RData)'),
                         (1, 'None'),
                         (2, 'None')],
                     14: [],
                     15: [(0, '1')],
                     16: [],
                     17: [],
                     18: [],
                     19: [(0, '18')],
                     20: [
                         (0, 'PackageData(alinea.adel.wheat.data, So99.RData)'),
                         (1, 'None'),
                         (2, 'None')],
                     21: [],
                     22: [],
                     23: [],
                     24: [],
                     25: [],
                     26: [],
                     27: [(1, "'EiSup'")],
                     28: [(2, '0.20000000000000001')],
                     30: [],
                     31: [(0, 'PackageData(alinea.adel.data, Rfun.R)'),
                          (1, 'None'),
                          (2, 'None')],
                     32: [],
                     33: [(0, 'PackageData(alinea.adel.data, mais.RData)'),
                          (1, 'None'),
                          (2, 'None')],
                     34: [(0, 'PackageData(alinea.adel.data, leaves.db)'),
                          (1, 'None'),
                          (2, 'None')],
                     35: [],
                     36: [],
                     37: [(1, "'maisdb'")],
                     38: [],
                     39: [(1, "'test'")],
                     40: [],
                     41: [],
                     42: [],
                     43: [(1, "'D:/ADEL/feuille.can'"), (2, "'w'")],
                     44: [],
                     45: [(1, "'D:/ADEL/indice.dat'")],
                     46: [],
                     47: [(1, "'D:/ADEL/scene.8'"), (2, "'w'")],
                     48: [],
                     49: [],
                     50: [(1, "'1 0 0 -1\\n'"),
                          (3,
                           '"#     par.opt  MC96\\n#simulation \\n#format e : tige,  feuille sup,  feuille inf\\n# nbre d\'especes\\nn 2\\n#1 ESPECES\\ns d 0.15\\n# espece 1\\ne d 0.10   d 0.10 0.05  d 0.10 0.05\\n# espece 2\\ne d 0.01   d 0.01 0.005  d 0.01 0.005\\n\\n"'),
                          (4, "'par'")],
                     52: [(1, "'D:/ADEL/feuille2.can'")],
                     '__in__': [],
                     '__out__': []},
                 elt_ad_hoc={},
                 lazy=True,
                 )

_174658092 = CNF(uid="175664ee4f2011e6b469d4bed973e64a",
                 name='demo Base',
                 description='',
                 category='demo',
                 doc='',
                 inputs=[],
                 outputs=[],
                 elt_factory={2: ('alinea.adel.data', 'Arvalis.RData'),
                              3: ('alinea.adel.io', 'readRData'),
                              4: ('openalea.python method', 'getitem'),
                              5: ('openalea.data structure.string', 'string'),
                              6: ('alinea.adel.io', 'RlistAsDict'),
                              7: ('openalea.python method', 'getitem'),
                              8: ('alinea.adel.parameterisation', 'setAdelArv'),
                              9: ('alinea.adel.simulation', 'RunAdel'),
                              10: ('openalea.python method', 'range'),
                              11: ('alinea.adel.wheat', 'CanMTGInterpreter'),
                              12: ('alinea.adel.stand', 'agronomic plot'),
                              13: ('alinea.adel.wheat.data', 'SRSo.RData'),
                              14: ('openalea.python method', 'getitem'),
                              15: ('openalea.data structure', 'int'),
                              16: ('alinea.adel.macro', 'plot'),
                              17: ('alinea.caribu', 'CaribuZenithPar'),
                              18: ('alinea.adel.fitting', 'fit leaves'),
                              19: ('openalea.data structure', 'int'),
                              20: ('alinea.adel.wheat.data', 'So99.RData'),
                              21: ('alinea.adel.macro', 'plot'),
                              22: ('openalea.flow control', 'annotation'),
                              23: ('alinea.adel.geometry', 'symbols'),
                              24: ('alinea.adel.stand', 'CanMTGPlanter'),
                              25: ('alinea.adel.io', 'to_canestra'),
                              26: ('alinea.adel.wheat', 'extract_leaves'),
                              27: ('alinea.caribu', 'selectOutput'),
                              28: (
                                  'alinea.caribu.visualisation',
                                  'ViewMapOnCan'),
                              29: ('alinea.caribu', 'LIE'),
                              30: ('openalea.file', 'read'),
                              31: ('alinea.adel.data', 'Rfun.R'),
                              32: ('openalea.flow control', 'annotation'),
                              33: ('alinea.adel.data', 'mais.RData'),
                              34: ('alinea.adel.data', 'leaves.db'),
                              35: ('alinea.adel.io', 'load leaf data'),
                              36: ('alinea.adel.io', 'readRData'),
                              37: ('openalea.python method', 'getitem'),
                              38: ('alinea.adel.io', 'RlistAsDict'),
                              39: ('openalea.python method', 'getitem')},
                 elt_connections={9916292: (2, 0, 3, 0),
                                  9916304: (17, 1, 29, 1),
                                  9916316: (36, 0, 37, 0),
                                  9916328: (6, 0, 7, 0),
                                  9916340: (13, 0, 26, 1),
                                  9916352: (31, 0, 30, 0),
                                  9916364: (5, 0, 4, 1),
                                  9916376: (8, 0, 9, 1),
                                  9916388: (24, 0, 16, 0),
                                  9916400: (12, 1, 24, 1),
                                  9916412: (26, 0, 18, 0),
                                  9916424: (30, 0, 8, 1),
                                  9916436: (24, 0, 25, 0),
                                  9916448: (17, 0, 29, 0),
                                  9916460: (9, 0, 14, 0),
                                  9916472: (12, 0, 8, 2),
                                  9916484: (33, 0, 36, 0),
                                  9916496: (11, 0, 21, 0),
                                  9916508: (37, 0, 38, 0),
                                  9916520: (14, 0, 11, 1),
                                  9916532: (23, 0, 11, 0),
                                  9916544: (11, 0, 24, 0),
                                  9916556: (19, 0, 18, 1),
                                  9916568: (20, 0, 26, 0),
                                  9916580: (18, 0, 23, 0),
                                  9916592: (3, 0, 4, 0),
                                  9916604: (10, 0, 9, 0),
                                  9916616: (17, 0, 28, 0),
                                  9916628: (15, 0, 14, 1),
                                  9916640: (12, 2, 17, 1),
                                  9916652: (38, 0, 39, 0),
                                  9916664: (7, 0, 8, 0),
                                  9916676: (4, 0, 6, 0),
                                  9916688: (24, 0, 17, 0),
                                  9916700: (34, 0, 35, 0),
                                  9916712: (17, 1, 27, 0),
                                  9916724: (27, 0, 28, 1)},
                 elt_data={2: {'block': False,
                               'caption': 'Arvalis.RData',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set([2]),
                               'posx': 47.500000000000028,
                               'posy': 28.750000000000007,
                               'priority': 0,
                               'user_application': None},
                           3: {'block': False,
                               'caption': 'readRData',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 54.999999999999972,
                               'posy': 93.750000000000028,
                               'priority': 0,
                               'user_application': None},
                           4: {'block': False,
                               'caption': 'getitem',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 123.74999999999997,
                               'posy': 162.49999999999997,
                               'priority': 0,
                               'user_application': None},
                           5: {'block': False,
                               'caption': "'Calagedb'",
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 183.74999999999994,
                               'posy': 93.750000000000014,
                               'priority': 0,
                               'user_application': None},
                           6: {'block': False,
                               'caption': 'RlistAsDict',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 110.0,
                               'posy': 223.74999999999994,
                               'priority': 0,
                               'user_application': None},
                           7: {'block': False,
                               'caption': 'getitem',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 127.49999999999991,
                               'posy': 281.24999999999994,
                               'priority': 0,
                               'user_application': None},
                           8: {'block': False,
                               'caption': 'setAdelArv',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 329.99999999999994,
                               'posy': 414.99999999999994,
                               'priority': 0,
                               'user_application': None},
                           9: {'block': False,
                               'caption': 'RunAdel',
                               'hide': True,
                               'lazy': True,
                               'port_hide_changed': set(),
                               'posx': 281.4898989898989,
                               'posy': 517.38636363636351,
                               'priority': 0,
                               'user_application': None},
                           10: {'block': False,
                                'caption': 'range',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 150.11363636363629,
                                'posy': 455.40404040404024,
                                'priority': 0,
                                'user_application': None},
                           11: {'block': False,
                                'caption': 'CanMTGInterpreter',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 178.24494949494931,
                                'posy': 662.14646464646432,
                                'priority': 0,
                                'user_application': None},
                           12: {'block': False,
                                'caption': 'agronomic plot',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 474.99999999999989,
                                'posy': 256.24999999999994,
                                'priority': 0,
                                'user_application': None},
                           13: {'block': False,
                                'caption': 'SRSo.RData',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set([2]),
                                'posx': -111.25000000000001,
                                'posy': 269.99999999999994,
                                'priority': 0,
                                'user_application': None},
                           14: {'block': False,
                                'caption': 'getitem',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 334.99999999999994,
                                'posy': 583.88888888888869,
                                'priority': 0,
                                'user_application': None},
                           15: {'block': False,
                                'caption': '2',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 419.99999999999994,
                                'posy': 522.49999999999989,
                                'priority': 0,
                                'user_application': None},
                           16: {'block': False,
                                'caption': 'plot',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 370.93267141093884,
                                'posy': 1026.8172057806619,
                                'priority': 0,
                                'user_application': None},
                           17: {'block': False,
                                'caption': 'CaribuZenithPar',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 590.85510178595916,
                                'posy': 940.72970317656223,
                                'priority': 0,
                                'user_application': None},
                           18: {'block': False,
                                'caption': 'fit leaves',
                                'hide': True,
                                'lazy': True,
                                'minimal': False,
                                'port_hide_changed': set(),
                                'posx': -146.24999999999989,
                                'posy': 473.74999999999966,
                                'priority': 0,
                                'user_application': None},
                           19: {'block': False,
                                'caption': '9',
                                'hide': True,
                                'lazy': True,
                                'minimal': False,
                                'port_hide_changed': set(),
                                'posx': -17.49999999999995,
                                'posy': 318.74999999999994,
                                'priority': 0,
                                'user_application': None},
                           20: {'block': False,
                                'caption': 'So99.RData',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set([2]),
                                'posx': -227.50000000000003,
                                'posy': 269.99999999999994,
                                'priority': 0,
                                'user_application': None},
                           21: {'block': False,
                                'caption': 'plot',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 140.0,
                                'posy': 780.0,
                                'priority': 0,
                                'user_application': False},
                           22: {'posx': 1.2500000000000568,
                                'posy': 448.74999999999994, 'txt': ''},
                           23: {'block': False,
                                'caption': 'symbols',
                                'hide': True,
                                'lazy': True,
                                'minimal': False,
                                'port_hide_changed': set(),
                                'posx': -137.49999999999994,
                                'posy': 534.99999999999966,
                                'priority': 0,
                                'user_application': None},
                           24: {'block': False,
                                'caption': 'CanMTGPlanter',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 472.49999999999989,
                                'posy': 741.24999999999989,
                                'priority': 0,
                                'user_application': None},
                           25: {'block': False,
                                'caption': 'to_canestra',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 82.034278336526484,
                                'posy': 1025.0064381187481,
                                'priority': 0,
                                'user_application': None},
                           26: {'block': False,
                                'caption': 'extract_leaves',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': -175.0,
                                'posy': 365.0,
                                'priority': 0,
                                'user_application': None},
                           27: {'block': False,
                                'caption': 'selectOutput',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 796.31622331346807,
                                'posy': 1008.6672161970596,
                                'priority': 0,
                                'user_application': None},
                           28: {'block': False,
                                'caption': 'ViewMapOnCan',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 772.72166854862462,
                                'posy': 1114.8427126388553,
                                'priority': 0,
                                'user_application': None},
                           29: {'block': False,
                                'caption': 'LIE',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 619.35706257714219,
                                'posy': 1169.8966737568235,
                                'priority': 0,
                                'user_application': None},
                           30: {'block': False,
                                'caption': 'read',
                                'hide': True,
                                'lazy': False,
                                'port_hide_changed': set(),
                                'posx': 365.02523574862374,
                                'posy': 237.46466995192671,
                                'priority': 0,
                                'user_application': None},
                           31: {'block': False,
                                'caption': 'Rfun.R',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set([2]),
                                'posx': 635.71260179554451,
                                'posy': 27.9527968259506,
                                'priority': 0,
                                'user_application': None},
                           32: {'posx': 728.74999999999989,
                                'posy': 33.749999999999986,
                                'txt': "This file is an example of R functiions : don't modify it ! "},
                           33: {'block': False,
                                'caption': 'mais.RData',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set([2]),
                                'posx': 363.74999999999994,
                                'posy': 39.999999999999993,
                                'priority': 0,
                                'user_application': None},
                           34: {'block': False,
                                'caption': 'leaves.db',
                                'hide': True,
                                'lazy': True,
                                'minimal': False,
                                'port_hide_changed': set(),
                                'posx': -334.99999999999983,
                                'posy': 269.99999999999977,
                                'priority': 0,
                                'user_application': None},
                           35: {'block': False,
                                'caption': 'load leaf data',
                                'hide': True,
                                'lazy': True,
                                'minimal': False,
                                'port_hide_changed': set(),
                                'posx': -344.99999999999983,
                                'posy': 368.74999999999983,
                                'priority': 0,
                                'user_application': None},
                           36: {'block': False,
                                'caption': 'readRData',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 308.74999999999994,
                                'posy': 106.24999999999997,
                                'priority': 0,
                                'user_application': None},
                           37: {'block': False,
                                'caption': 'getitem',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 259.99999999999989,
                                'posy': 163.74999999999997,
                                'priority': 0,
                                'user_application': None},
                           38: {'block': False,
                                'caption': 'RlistAsDict',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 223.74999999999994,
                                'posy': 238.74999999999994,
                                'priority': 0,
                                'user_application': None},
                           39: {'block': False,
                                'caption': 'getitem',
                                'hide': True,
                                'lazy': True,
                                'port_hide_changed': set(),
                                'posx': 247.49999999999994,
                                'posy': 296.24999999999994,
                                'priority': 0,
                                'user_application': None},
                           '__in__': {'block': False,
                                      'caption': 'In',
                                      'hide': True,
                                      'lazy': True,
                                      'port_hide_changed': set(),
                                      'posx': 20.0,
                                      'posy': 5.0,
                                      'priority': 0,
                                      'user_application': None},
                           '__out__': {'block': False,
                                       'caption': 'Out',
                                       'hide': True,
                                       'lazy': True,
                                       'port_hide_changed': set(),
                                       'posx': 20.0,
                                       'posy': 250.0,
                                       'priority': 0,
                                       'user_application': None}},
                 elt_value={
                     2: [(0, 'PackageData(alinea.adel.data, Arvalis.RData)'),
                         (1, 'None'),
                         (2, 'None')],
                     3: [],
                     4: [],
                     5: [(0, "'Calagedb'")],
                     6: [],
                     7: [(1, "'Vra08.s2d2'")],
                     8: [(3, '20')],
                     9: [],
                     10: [(0, '0'), (1, '3000'), (2, '1000')],
                     11: [],
                     12: [(0, '1'),
                          (1, '1'),
                          (2, '150'),
                          (3, '150'),
                          (4, '0.125'),
                          (5, '0'),
                          (6, '100')],
                     13: [
                         (0, 'PackageData(alinea.adel.wheat.data, SRSo.RData)'),
                         (1, 'None'),
                         (2, 'None')],
                     14: [],
                     15: [(0, '2')],
                     16: [],
                     17: [],
                     18: [],
                     19: [(0, '9')],
                     20: [
                         (0, 'PackageData(alinea.adel.wheat.data, So99.RData)'),
                         (1, 'None'),
                         (2, 'None')],
                     21: [],
                     22: [],
                     23: [],
                     24: [],
                     25: [],
                     26: [],
                     27: [(1, "'EiSup'")],
                     28: [(2, '0.20000000000000001')],
                     29: [],
                     30: [],
                     31: [(0, 'PackageData(alinea.adel.data, Rfun.R)'),
                          (1, 'None'),
                          (2, 'None')],
                     32: [],
                     33: [(0, 'PackageData(alinea.adel.data, mais.RData)'),
                          (1, 'None'),
                          (2, 'None')],
                     34: [(0, 'PackageData(alinea.adel.data, leaves.db)'),
                          (1, 'None'),
                          (2, 'None')],
                     35: [],
                     36: [],
                     37: [(1, "'maisdb'")],
                     38: [],
                     39: [(1, "'test'")],
                     '__in__': [],
                     '__out__': []},
                 elt_ad_hoc={},
                 lazy=True,
                 )
