
# This file has been generated at Wed Aug 25 20:22:41 2010

from openalea.core import *


__name__ = 'alinea.adel.wheat.macro'

__editable__ = True
__description__ = 'Tutorial and test'
__license__ = ''
__url__ = ''
__alias__ = ['adel.wheat.macro']
__version__ = '0.0.1'
__authors__ = 'Jessica Bertheloot'
__institutes__ = 'INRA'
__icon__ = ''


__all__ = ['GenField', '_57234960', 'DebugLeafElement', '_57235184', '_57235024', 'LIEgreen', '_57235056', 'GeomLeaf', '_57235120']



GenField = CompositeNodeFactory(name='GenField',
                             description='',
                             category='composite',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': IData, 'name': 'Symbols', 'value': None},
   {  'desc': '', 'interface': IStr, 'name': 'LSystem String', 'value': None},
   {  'desc': '', 'interface': IInt, 'name': 'nb_plants', 'value': None},
   {  'desc': '', 'interface': IInt, 'name': 'nb_ranks', 'value': None},
   {  'desc': '',
      'interface': IFloat,
      'name': 'Distance betwen plants in a rank',
      'value': None},
   {  'desc': '',
      'interface': IFloat,
      'name': 'Distance between ranks',
      'value': None}],
                             outputs=[  {  'desc': '', 'interface': None, 'name': 'StandMTG'},
   {  'desc': '', 'interface': ISequence, 'name': 'domain'}],
                             elt_factory={  2: ('adel.stand', 'CanMTGPlanter'),
   3: ('adel.stand', 'regular'),
   4: ('adel.wheat', 'CanMTGInterpreter')},
                             elt_connections={  9853520: (3, 1, '__out__', 1),
   9853532: ('__in__', 5, 3, 3),
   9853544: ('__in__', 0, 4, 0),
   9853556: ('__in__', 3, 3, 1),
   9853568: (3, 0, 2, 1),
   9853580: ('__in__', 1, 4, 1),
   9853592: (4, 0, 2, 0),
   9853604: ('__in__', 4, 3, 2),
   9853616: (2, 0, '__out__', 0),
   9853628: ('__in__', 2, 3, 0)},
                             elt_data={  2: {  'caption': 'CanMTGPlanter',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 458.75,
         'posy': 271.25,
         'priority': 0,
         'user_application': None},
   3: {  'caption': 'regular',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2, 3]),
         'posx': 567.5,
         'posy': 182.5,
         'priority': 0,
         'user_application': None},
   4: {  'caption': 'CanMTGInterpreter',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 342.5,
         'posy': 185.0,
         'priority': 0,
         'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 447.5,
                'posy': 70.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 572.5,
                 'posy': 370.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [], 3: [], 4: [], '__in__': [], '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




_57234960 = CompositeNodeFactory(name='3. test leaf',
                             description='',
                             category='scene,composite.alinea',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('adel.wheat.data', 'So99.RData'),
   3: ('adel.wheat.data', 'SRSo.RData'),
   4: ('adel.fitting', 'fit leaves'),
   5: ('catalog.data', 'int'),
   6: ('adel.macro', 'get leaf'),
   7: ('adel.geometry', 'leaf to mesh'),
   8: ('catalog.data', 'int'),
   9: ('catalog.data', 'int'),
   10: ('PlantGL.Visualization', 'plot3D'),
   11: ('catalog.data', 'int'),
   12: ('catalog.data', 'int'),
   13: ('adel.wheat', 'extract_leaves'),
   14: ('adel.geometry', 'leaf element'),
   15: ('catalog.data', 'int'),
   16: ('catalog.data', 'int'),
   17: ('PlantGL.Visualization', 'plot3D'),
   18: ('stat.graphics', 'plot (x,y)'),
   19: ('catalog.python', 'getitem'),
   20: ('catalog.data', 'int'),
   21: ('catalog.python', 'getitem'),
   22: ('catalog.data', 'int'),
   23: ('catalog.data', 'string'),
   24: ('catalog.data', 'string'),
   25: ('catalog.data', 'int')},
                             elt_connections={  9793172: (14, 0, 17, 0),
   9793184: (6, 0, 7, 0),
   9793196: (6, 0, 21, 0),
   9793208: (24, 0, 18, 3),
   9793220: (2, 0, 13, 0),
   9793232: (16, 0, 14, 5),
   9793244: (22, 0, 21, 1),
   9793256: (8, 0, 7, 2),
   9793268: (7, 0, 10, 0),
   9793280: (23, 0, 18, 2),
   9793292: (6, 0, 19, 0),
   9793304: (8, 0, 7, 1),
   9793316: (3, 0, 13, 1),
   9793328: (6, 0, 14, 0),
   9793340: (13, 0, 4, 0),
   9793352: (20, 0, 19, 1),
   9793364: (9, 0, 7, 3),
   9793376: (21, 0, 18, 1),
   9793388: (11, 0, 6, 1),
   9793400: (15, 0, 14, 1),
   9793412: (4, 0, 6, 0),
   9793424: (5, 0, 4, 1),
   9793436: (19, 0, 18, 0),
   9793448: (25, 0, 14, 2),
   9793460: (12, 0, 6, 2)},
                             elt_data={  2: {  'caption': 'So99.RData',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 120.0,
         'posy': 43.75,
         'priority': 0,
         'user_application': None},
   3: {  'caption': 'SRSo.RData',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 246.25,
         'posy': 48.75,
         'priority': 0,
         'user_application': None},
   4: {  'caption': 'fit leaves',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 227.5,
         'posy': 207.5,
         'priority': 0,
         'user_application': None},
   5: {  'caption': '9',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 321.25,
         'posy': 120.0,
         'priority': 0,
         'user_application': None},
   6: {  'caption': 'get leaf',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 285.0,
         'posy': 265.0,
         'priority': 0,
         'user_application': None},
   7: {  'caption': 'leaf to mesh',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 378.75,
         'posy': 318.75,
         'priority': 0,
         'user_application': None},
   8: {  'caption': '7',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 397.5,
         'posy': 248.75,
         'priority': 0,
         'user_application': None},
   9: {  'caption': '1',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 453.75,
         'posy': 245.0,
         'priority': 0,
         'user_application': None},
   10: {  'caption': 'plot3D',
          'hide': True,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 375.7128099173554,
          'posy': 391.5805785123967,
          'priority': 0,
          'user_application': False},
   11: {  'caption': '31',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 357.5,
          'posy': 187.5,
          'priority': 0,
          'user_application': None},
   12: {  'caption': '2',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 407.5,
          'posy': 185.0,
          'priority': 0,
          'user_application': None},
   13: {  'caption': 'extract_leaves',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 172.5,
          'posy': 117.5,
          'priority': 0,
          'user_application': None},
   14: {  'caption': 'leaf element',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 151.25,
          'posy': 343.75,
          'priority': 0,
          'user_application': None},
   15: {  'caption': '7',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 150.0,
          'posy': 253.75,
          'priority': 0,
          'user_application': None},
   16: {  'caption': '1',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 236.25,
          'posy': 262.5,
          'priority': 0,
          'user_application': None},
   17: {  'caption': 'plot3D',
          'hide': True,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 213.56404958677695,
          'posy': 411.25000000000006,
          'priority': 0,
          'user_application': True},
   18: {  'caption': 'plot (x,y)',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 267.56198347107443,
          'posy': 833.67768595041287,
          'priority': 0,
          'user_application': None},
   19: {  'caption': 'getitem',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 237.60330578512398,
          'posy': 610.53719008264454,
          'priority': 0,
          'user_application': None},
   20: {  'caption': '0',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 280.23760330578523,
          'posy': 512.60330578512389,
          'priority': 0,
          'user_application': None},
   21: {  'caption': 'getitem',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 324.42148760330582,
          'posy': 612.64462809917359,
          'priority': 0,
          'user_application': None},
   22: {  'caption': '1',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 366.02272727272737,
          'posy': 522.97520661157,
          'priority': 0,
          'user_application': None},
   23: {  'caption': "'s'",
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 357.43801652892552,
          'posy': 748.96694214876038,
          'priority': 0,
          'user_application': None},
   24: {  'caption': "'r'",
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 387.43801652892552,
          'posy': 778.96694214876038,
          'priority': 0,
          'user_application': None},
   25: {  'caption': '7',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 186.25,
          'posy': 253.75,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [  (0, 'PackageData(adel.wheat.data, So99.RData)'),
         (1, 'None'),
         (2, 'None')],
   3: [  (0, 'PackageData(adel.wheat.data, SRSo.RData)'),
         (1, 'None'),
         (2, 'None')],
   4: [],
   5: [(0, '9')],
   6: [],
   7: [],
   8: [(0, '7')],
   9: [(0, '1')],
   10: [],
   11: [(0, '31')],
   12: [(0, '2')],
   13: [],
   14: [(3, '0.0'), (4, '1.0')],
   15: [(0, '7')],
   16: [(0, '1')],
   17: [],
   18: [(4, 'None')],
   19: [],
   20: [(0, '0')],
   21: [],
   22: [(0, '1')],
   23: [(0, "'s'")],
   24: [(0, "'r'")],
   25: [(0, '7')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




DebugLeafElement = CompositeNodeFactory(name='DebugLeafElement',
                             description='',
                             category='composite.alinea',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('alinea.adel.wheat.data', 'So99.RData'),
   3: ('alinea.adel.wheat.data', 'SRSo.RData'),
   4: ('adel.fitting', 'fit leaves'),
   5: ('adel.wheat', 'extract_leaves'),
   6: ('adel.geometry', 'symbols'),
   7: ('adel.wheat', 'CanMTGInterpreter'),
   8: ('adel.macro', 'plot'),
   9: ('catalog.file', 'read'),
   10: ('catalog.python', 'keys'),
   11: ('catalog.pickle', 'pickle dump'),
   12: ('catalog.pickle', 'pickle load'),
   13: ('catalog.file', 'tmpnam'),
   14: ('adel.wheat.data', 'testStr.txt')},
                             elt_connections={  9723292: (12, 0, 6, 0),
   9723304: (14, 0, 9, 0),
   9723316: (13, 0, 11, 1),
   9723328: (4, 0, 10, 0),
   9723340: (7, 0, 8, 0),
   9723352: (9, 0, 7, 1),
   9723364: (6, 0, 7, 0),
   9723376: (4, 0, 11, 0),
   9723388: (3, 0, 5, 1),
   9723400: (2, 0, 5, 0),
   9723412: (5, 0, 4, 0)},
                             elt_data={  2: {  'caption': 'So99.RData',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 150.0,
         'posy': 73.75,
         'priority': 0,
         'user_application': None},
   3: {  'caption': 'SRSo.RData',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 276.25,
         'posy': 78.75,
         'priority': 0,
         'user_application': None},
   4: {  'caption': 'fit leaves',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 257.5,
         'posy': 237.5,
         'priority': 0,
         'user_application': None},
   5: {  'caption': 'extract_leaves',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 202.5,
         'posy': 147.5,
         'priority': 0,
         'user_application': None},
   6: {  'caption': 'symbols',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 356.25,
         'posy': 330.0,
         'priority': 0,
         'user_application': None},
   7: {  'caption': 'CanMTGInterpreter',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 412.5,
         'posy': 438.75,
         'priority': 0,
         'user_application': None},
   8: {  'caption': 'plot',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 340.0,
         'posy': 495.0,
         'priority': 0,
         'user_application': None},
   9: {  'caption': 'read',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 588.75,
         'posy': 207.5,
         'priority': 0,
         'user_application': None},
   10: {  'caption': 'keys',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 73.75,
          'posy': 307.5,
          'priority': 0,
          'user_application': None},
   11: {  'caption': 'pickle dump',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': 182.5,
          'posy': 378.75,
          'priority': 0,
          'user_application': None},
   12: {  'caption': 'pickle load',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': 445.0,
          'posy': 257.5,
          'priority': 0,
          'user_application': None},
   13: {  'caption': 'tmpnam',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 363.75,
          'posy': 176.25,
          'priority': 0,
          'user_application': None},
   14: {  'caption': 'testStr.txt',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': 596.25,
          'posy': 90.0,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [  (0, 'PackageData(adel.wheat.data, So99.RData)'),
         (1, 'None'),
         (2, 'None')],
   3: [  (0, 'PackageData(adel.wheat.data, SRSo.RData)'),
         (1, 'None'),
         (2, 'None')],
   4: [(1, '7')],
   5: [],
   6: [],
   7: [],
   8: [],
   9: [],
   10: [],
   11: [(2, 'False')],
   12: [(0, "'c:\\\\docume~1\\\\pradal\\\\locals~1\\\\temp\\\\tmpwhntio'")],
   13: [],
   14: [  (0, 'PackageData(adel.wheat.data, testStr.txt)'),
          (1, 'None'),
          (2, 'None')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




_57235184 = CompositeNodeFactory(name='1. view leaves database',
                             description='',
                             category='composite.alinea',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('adel.wheat.data', 'leaves_wheat.db'),
   3: ('adel.io', 'load leaf data'),
   4: ('adel.fitting', 'fit leaves'),
   5: ('catalog.data', 'int'),
   6: ('adel.macro', 'get leaf'),
   7: ('adel.geometry', 'leaf to mesh'),
   8: ('catalog.data', 'int'),
   9: ('catalog.data', 'int'),
   10: ('PlantGL.Visualization', 'plot3D'),
   11: ('catalog.data', 'int'),
   12: ('catalog.data', 'int')},
                             elt_connections={  9791172: (12, 0, 6, 2),
   9791184: (11, 0, 6, 1),
   9791196: (6, 0, 7, 0),
   9791208: (7, 0, 10, 0),
   9791220: (8, 0, 7, 2),
   9791232: (9, 0, 7, 3),
   9791244: (8, 0, 7, 1),
   9791256: (4, 0, 6, 0),
   9791268: (5, 0, 4, 1),
   9791280: (3, 0, 4, 0),
   9791292: (2, 0, 3, 0)},
                             elt_data={  2: {  'caption': 'leaves_wheat.db',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 168.75,
         'posy': 57.5,
         'priority': 0,
         'user_application': None},
   3: {  'caption': 'load leaf data',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 181.25,
         'posy': 118.75,
         'priority': 0,
         'user_application': None},
   4: {  'caption': 'fit leaves',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 238.75,
         'posy': 186.25,
         'priority': 0,
         'user_application': None},
   5: {  'caption': '9',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 321.25,
         'posy': 120.0,
         'priority': 0,
         'user_application': None},
   6: {  'caption': 'get leaf',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 285.0,
         'posy': 265.0,
         'priority': 0,
         'user_application': None},
   7: {  'caption': 'leaf to mesh',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 378.75,
         'posy': 318.75,
         'priority': 0,
         'user_application': None},
   8: {  'caption': '7',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 397.5,
         'posy': 248.75,
         'priority': 0,
         'user_application': None},
   9: {  'caption': '1',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 453.75,
         'posy': 245.0,
         'priority': 0,
         'user_application': None},
   10: {  'caption': 'plot3D',
          'hide': True,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 350.0,
          'posy': 372.5,
          'priority': 0,
          'user_application': True},
   11: {  'caption': '36',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 356.25,
          'posy': 187.5,
          'priority': 0,
          'user_application': None},
   12: {  'caption': '4',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 407.5,
          'posy': 185.0,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [  (0, 'PackageData(adel.wheat.data, leaves_wheat.db)'),
         (1, 'None'),
         (2, 'None')],
   3: [],
   4: [],
   5: [(0, '9')],
   6: [],
   7: [],
   8: [(0, '7')],
   9: [(0, '1')],
   10: [],
   11: [(0, '36')],
   12: [(0, '4')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




_57235024 = CompositeNodeFactory(name='2. view leaf db with R data',
                             description='',
                             category='composite.alinea',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('adel.wheat.data', 'So99.RData'),
   3: ('adel.wheat.data', 'SRSo.RData'),
   4: ('adel.fitting', 'fit leaves'),
   5: ('catalog.data', 'int'),
   6: ('adel.macro', 'get leaf'),
   7: ('adel.geometry', 'leaf to mesh'),
   8: ('catalog.data', 'int'),
   9: ('catalog.data', 'int'),
   10: ('PlantGL.Visualization', 'plot3D'),
   11: ('catalog.data', 'int'),
   12: ('catalog.data', 'int'),
   13: ('adel.wheat', 'extract_leaves')},
                             elt_connections={  9779236: (6, 0, 7, 0),
   9779248: (3, 0, 13, 1),
   9779260: (8, 0, 7, 1),
   9779272: (5, 0, 4, 1),
   9779284: (2, 0, 13, 0),
   9779296: (13, 0, 4, 0),
   9779308: (11, 0, 6, 1),
   9779320: (12, 0, 6, 2),
   9779332: (4, 0, 6, 0),
   9779356: (9, 0, 7, 3),
   9779368: (7, 0, 10, 0),
   9779380: (8, 0, 7, 2)},
                             elt_data={  2: {  'caption': 'So99.RData',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 120.0,
         'posy': 43.75,
         'priority': 0,
         'user_application': None},
   3: {  'caption': 'SRSo.RData',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 246.25,
         'posy': 48.75,
         'priority': 0,
         'user_application': None},
   4: {  'caption': 'fit leaves',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 227.5,
         'posy': 207.5,
         'priority': 0,
         'user_application': None},
   5: {  'caption': '50',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 321.25,
         'posy': 120.0,
         'priority': 0,
         'user_application': None},
   6: {  'caption': 'get leaf',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 285.0,
         'posy': 265.0,
         'priority': 0,
         'user_application': None},
   7: {  'caption': 'leaf to mesh',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 378.75,
         'posy': 318.75,
         'priority': 0,
         'user_application': None},
   8: {  'caption': '7',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 397.5,
         'posy': 248.75,
         'priority': 0,
         'user_application': None},
   9: {  'caption': '1',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 453.75,
         'posy': 245.0,
         'priority': 0,
         'user_application': None},
   10: {  'caption': 'plot3D',
          'hide': True,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 361.25,
          'posy': 381.25,
          'priority': 0,
          'user_application': True},
   11: {  'caption': '38',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 357.5,
          'posy': 187.5,
          'priority': 0,
          'user_application': None},
   12: {  'caption': '4',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 407.5,
          'posy': 185.0,
          'priority': 0,
          'user_application': None},
   13: {  'caption': 'extract_leaves',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 172.5,
          'posy': 117.5,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [  (0, 'PackageData(adel.wheat.data, So99.RData)'),
         (1, 'None'),
         (2, 'None')],
   3: [  (0, 'PackageData(adel.wheat.data, SRSo.RData)'),
         (1, 'None'),
         (2, 'None')],
   4: [],
   5: [(0, '50')],
   6: [],
   7: [],
   8: [(0, '7')],
   9: [(0, '1')],
   10: [],
   11: [(0, '38')],
   12: [(0, '4')],
   13: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




LIEgreen = CompositeNodeFactory(name='LIEgreen',
                             description='Computes light interception efficiency for green tissues only',
                             category='data processing',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': IData, 'name': 'CaribuScene', 'value': None},
   {  'desc': '', 'interface': IDict, 'name': 'EnergyDict', 'value': None}],
                             outputs=[  {  'desc': '', 'interface': IFloat, 'name': 'Efficiency'},
   {  'desc': '', 'interface': IFloat, 'name': 'energy on soil'},
   {  'desc': '', 'interface': IFloat, 'name': 'incident energy'}],
                             elt_factory={  3: ('alinea.adel.wheat', 'Sum_EnergyDensities'),
   6: ('openalea.python method', 'mean'),
   7: ('alinea.caribu', 'get Ei'),
   8: ('openalea.math', '/'),
   9: ('openalea.math', '-'),
   10: ('alinea.caribu', 'selectOutput'),
   11: ('alinea.caribu', 'filterby'),
   12: ('openalea.function operator', 'function'),
   13: ('alinea.caribu', 'selectOutput'),
   14: ('alinea.caribu', 'filterby'),
   15: ('alinea.caribu', 'filterby'),
   16: ('alinea.caribu', 'selectOutput'),
   17: ('alinea.caribu', 'selectOutput'),
   18: ('alinea.caribu', 'filterby'),
   19: ('openalea.function operator', 'function')},
                             elt_connections={  10018892: (11, 0, 3, 0),
   10018904: ('__in__', 0, 7, 0),
   10018916: (16, 0, 11, 1),
   10018928: (3, 0, 9, 1),
   10018940: ('__in__', 1, 17, 0),
   10018952: (17, 0, 15, 0),
   10018964: (15, 0, 3, 3),
   10018976: ('__in__', 1, 16, 0),
   10018988: (17, 0, 18, 0),
   10019000: (8, 0, '__out__', 0),
   10019012: ('__in__', 1, 13, 0),
   10019024: (10, 0, 14, 1),
   10019036: (7, 0, '__out__', 2),
   10019048: (7, 0, 9, 0),
   10019060: (19, 0, 18, 2),
   10019072: (12, 0, 14, 2),
   10019084: (10, 0, 15, 1),
   10019096: (12, 0, 11, 2),
   10019108: (18, 0, 6, 0),
   10019120: (19, 0, 15, 2),
   10019132: ('__in__', 1, 10, 0),
   10019144: (9, 0, 8, 0),
   10019156: (17, 0, 14, 0),
   10019168: (14, 0, 3, 1),
   10019180: (6, 0, '__out__', 1),
   10019192: (13, 0, 18, 1),
   10019204: (18, 0, 3, 2),
   10019216: (7, 0, 8, 1),
   10019228: (17, 0, 11, 0)},
                             elt_data={  3: {  'block': False,
         'caption': 'Sum_EnergyDensities',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -274.23326660564601,
         'posy': 63.209795494209217,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'mean',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 76.999939115883606,
         'posy': -6.5835261330350257,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'get Ei',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -479.64181323170999,
         'posy': -180.54504351930242,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': '/',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -397.96862624888445,
         'posy': 155.72421300859293,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': '-',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -519.1224958196982,
         'posy': 106.94216953219757,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': 'selectOutput',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -40.906129186461413,
          'posy': -141.25593760568358,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   11: {  'block': False,
          'caption': 'filterby',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -368.49708726931442,
          'posy': -62.169556748002009,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   12: {  'block': False,
          'caption': 'f',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -273.90051841465248,
          'posy': -63.353702697876074,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   13: {  'block': False,
          'caption': 'selectOutput',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -149.33346330647331,
          'posy': -140.87371745113649,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   14: {  'block': False,
          'caption': 'filterby',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -366.42596257451771,
          'posy': -2.5661494368284679,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   15: {  'block': False,
          'caption': 'filterby',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -139.38185083976498,
          'posy': -0.27375624395493503,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   16: {  'block': False,
          'caption': 'selectOutput',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -272.11109000716249,
          'posy': -143.43603481544199,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   17: {  'block': False,
          'caption': 'selectOutput',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -378.8208609527677,
          'posy': -140.0377860027528,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   18: {  'block': False,
          'caption': 'filterby',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -139.96942732046722,
          'posy': -66.224183680567194,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   19: {  'block': False,
          'caption': 'f',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -41.045780158711636,
          'posy': -68.421754687559471,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': -221.0612783519073,
                'posy': -240.54504351930242,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': -221.0612783519073,
                 'posy': 215.72421300859293,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  3: [],
   6: [],
   7: [],
   8: [],
   9: [],
   10: [(1, "'Area'")],
   11: [],
   12: [(0, "'def f(x):\\n  return x == 2.'")],
   13: [(1, "'EiSup'")],
   14: [],
   15: [],
   16: [(1, "'Eabsm2'")],
   17: [(1, "'Opt'")],
   18: [],
   19: [(0, "'def f(x):\\n  return x == 0.'")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [95.108917377685998, -148.66680872960475], 'useUserColor': False, 'userColor': None},
   3: {'position': [-274.23326660564601, 63.209795494209217], 'userColor': None, 'useUserColor': False},
   4: {'position': [65.634552158802251, -59.032226128744327], 'useUserColor': False, 'userColor': None},
   5: {'position': [160.160570270248, -115.67426224178638], 'useUserColor': False, 'userColor': None},
   6: {'position': [76.999939115883606, -6.5835261330350257], 'userColor': None, 'useUserColor': False},
   7: {'position': [-479.64181323170999, -180.54504351930242], 'userColor': None, 'useUserColor': False},
   8: {'position': [-397.96862624888445, 155.72421300859293], 'userColor': None, 'useUserColor': False},
   9: {'position': [-519.1224958196982, 106.94216953219757], 'userColor': None, 'useUserColor': False},
   10: {'position': [-40.906129186461413, -141.25593760568358], 'userColor': None, 'useUserColor': False},
   11: {'position': [-368.49708726931442, -62.169556748002009], 'userColor': None, 'useUserColor': False},
   12: {'position': [-273.90051841465248, -63.353702697876074], 'userColor': None, 'useUserColor': False},
   13: {'position': [-149.33346330647331, -140.87371745113649], 'userColor': None, 'useUserColor': False},
   14: {'position': [-366.42596257451771, -2.5661494368284679], 'userColor': None, 'useUserColor': False},
   15: {'position': [-139.38185083976498, -0.27375624395493503], 'userColor': None, 'useUserColor': False},
   16: {'position': [-272.11109000716249, -143.43603481544199], 'userColor': None, 'useUserColor': False},
   17: {'position': [-378.8208609527677, -140.0377860027528], 'userColor': None, 'useUserColor': False},
   18: {'position': [-139.96942732046722, -66.224183680567194], 'userColor': None, 'useUserColor': False},
   19: {'position': [-41.045780158711636, -68.421754687559471], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [-221.0612783519073, -240.54504351930242], 'useUserColor': False, 'userColor': None},
   '__out__': {'position': [-221.0612783519073, 215.72421300859293], 'useUserColor': False, 'userColor': None}},
                             lazy=True,
                             )




_57235056 = CompositeNodeFactory(name='CanMTG generation',
                             description='Test MTG generation from lsystem',
                             category='scene.MTG,composite.alinea',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('alinea.adel.wheat.data', 'So99.RData'),
   3: ('alinea.adel.wheat.data', 'SRSo.RData'),
   4: ('alinea.adel.fitting', 'fit leaves'),
   5: ('alinea.adel.wheat', 'extract_leaves'),
   6: ('alinea.adel.geometry', 'symbols'),
   7: ('alinea.adel.wheat', 'CanMTGInterpreter'),
   8: ('alinea.adel.macro', 'plot'),
   9: ('openalea.file', 'read'),
   11: ('alinea.adel.wheat.data', 'AleaStr190.txt')},
                             elt_connections={  9790136: (11, 0, 9, 0),
   9790148: (6, 0, 7, 0),
   9790160: (4, 0, 6, 0),
   9790172: (3, 0, 5, 1),
   9790184: (2, 0, 5, 0),
   9790196: (5, 0, 4, 0),
   9790208: (9, 0, 7, 1),
   9790220: (7, 0, 8, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'So99.RData',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 150.0,
         'posy': 73.75,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'SRSo.RData',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 276.25,
         'posy': 78.75,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'fit leaves',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 257.5,
         'posy': 237.5,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'extract_leaves',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 202.5,
         'posy': 147.5,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'symbols',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 356.25,
         'posy': 330.0,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'CanMTGInterpreter',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 412.5,
         'posy': 438.75,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'plot',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 145.0,
         'posy': 510.0,
         'priority': 0,
         'user_application': True},
   9: {  'block': False,
         'caption': 'read',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 556.24999999999989,
         'posy': 352.49999999999994,
         'priority': 0,
         'user_application': None},
   11: {  'block': False,
          'caption': 'AleaStr190.txt',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': 534.99999999999989,
          'posy': 266.24999999999994,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [  (0, 'PackageData(alinea.adel.wheat.data, So99.RData)'),
         (1, 'None'),
         (2, 'None')],
   3: [  (0, 'PackageData(alinea.adel.wheat.data, SRSo.RData)'),
         (1, 'None'),
         (2, 'None')],
   4: [(1, '7')],
   5: [],
   6: [],
   7: [],
   8: [],
   9: [],
   11: [  (0, 'PackageData(alinea.adel.wheat.data, AleaStr190.txt)'),
          (1, 'None'),
          (2, 'None')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




GeomLeaf = CompositeNodeFactory(name='GeomLeaf',
                             description='Generate the geometry of all leaves measured',
                             category='composite.alinea,scene',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': IData, 'name': 'xy', 'value': None},
   {  'desc': '', 'interface': IData, 'name': 'sr', 'value': None}],
                             outputs=[{  'desc': '', 'interface': IDict, 'name': 'A set of symbols'}],
                             elt_factory={  2: ('adel.fitting', 'fit leaves'),
   3: ('adel.wheat', 'extract_leaves'),
   4: ('adel.geometry', 'symbols')},
                             elt_connections={  9853580: ('__in__', 1, 3, 1),
   9853592: ('__in__', 0, 3, 0),
   9853604: (4, 0, '__out__', 0),
   9853616: (2, 0, 4, 0),
   9853628: (3, 0, 2, 0)},
                             elt_data={  2: {  'caption': 'fit leaves',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 177.5,
         'posy': 220.0,
         'priority': 0,
         'user_application': None},
   3: {  'caption': 'extract_leaves',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 145.0,
         'posy': 150.0,
         'priority': 0,
         'user_application': None},
   4: {  'caption': 'symbols',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 181.25,
         'posy': 296.25,
         'priority': 0,
         'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 191.25,
                'posy': 43.75,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 192.5,
                 'posy': 385.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [(1, '7')], 3: [], 4: [], '__in__': [], '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




_57235120 = CompositeNodeFactory(name='Stand Generation',
                             description='',
                             category='scene,composite',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('alinea.adel.wheat.data', 'So99.RData'),
   3: ('alinea.adel.wheat.data', 'SRSo.RData'),
   4: ('alinea.adel.fitting', 'fit leaves'),
   5: ('alinea.adel.wheat', 'extract_leaves'),
   6: ('alinea.adel.geometry', 'symbols'),
   7: ('alinea.adel.wheat', 'CanMTGInterpreter'),
   8: ('openalea.flow control', 'annotation'),
   9: ('openalea.file', 'read'),
   10: ('alinea.adel.macro', 'plot'),
   11: ('alinea.adel.stand', 'CanMTGPlanter'),
   12: ('alinea.adel.stand', 'regular'),
   13: ('openalea.data structure', 'int'),
   14: ('openalea.data structure', 'int'),
   15: ('alinea.adel.wheat.data', 'AleaStr190.txt'),
   16: ('alinea.caribu.visualisation', 'ViewMapOnCan'),
   17: ('alinea.caribu', 'CaribuZenithPar'),
   18: ('alinea.caribu', 'selectOutput'),
   19: ('openalea.flow control', 'annotation'),
   20: ('openalea.flow control', 'annotation'),
   21: ('openalea.flow control', 'annotation'),
   22: ('openalea.flow control', 'annotation')},
                             elt_connections={  9915948: (17, 1, 18, 0),
   9915960: (12, 0, 11, 1),
   9915972: (18, 0, 16, 1),
   9915984: (15, 0, 9, 0),
   9915996: (17, 0, 16, 0),
   9916008: (12, 1, 17, 1),
   9916020: (5, 0, 4, 0),
   9916032: (4, 0, 6, 0),
   9916044: (14, 0, 12, 3),
   9916056: (6, 0, 7, 0),
   9916068: (11, 0, 10, 0),
   9916080: (7, 0, 11, 0),
   9916092: (3, 0, 5, 1),
   9916104: (9, 0, 7, 1),
   9916116: (13, 0, 12, 2),
   9916128: (2, 0, 5, 0),
   9916140: (11, 0, 17, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'So99.RData',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 283.75,
         'posy': 36.25,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'SRSo.RData',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 412.5,
         'posy': 35.0,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'fit leaves',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 370.0,
         'posy': 201.25000000000006,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'extract_leaves',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 337.5,
         'posy': 131.25000000000006,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'symbols',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 373.75,
         'posy': 277.50000000000006,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'CanMTGInterpreter',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 603.74999999999989,
         'posy': 386.25000000000006,
         'priority': 0,
         'user_application': None},
   8: {  'posx': 37.499999999999943,
         'posy': 126.24999999999994,
         'txt': 'Import Digitalisation data\nfrom R'},
   9: {  'block': False,
         'caption': 'read',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 681.24999999999989,
         'posy': 232.50000000000006,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'plot',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 659.99999999999989,
          'posy': 496.25000000000006,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'CanMTGPlanter',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 893.75000000000011,
          'posy': 456.25000000000006,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': 'regular',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2, 3]),
          'posx': 945.00000000000011,
          'posy': 262.50000000000006,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': '100',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 966.24999999999966,
          'posy': 181.25000000000006,
          'priority': 0,
          'user_application': None},
   14: {  'block': False,
          'caption': '100',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 1033.7499999999995,
          'posy': 178.75000000000006,
          'priority': 0,
          'user_application': None},
   15: {  'block': False,
          'caption': 'AleaStr190.txt',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': 642.49999999999989,
          'posy': 160.00000000000006,
          'priority': 0,
          'user_application': None},
   16: {  'block': False,
          'caption': 'ViewMapOnCan',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 1151.25,
          'posy': 738.75,
          'priority': 0,
          'user_application': None},
   17: {  'block': False,
          'caption': 'CaribuZenithPar',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 1142.5,
          'posy': 607.5,
          'priority': 0,
          'user_application': None},
   18: {  'block': False,
          'caption': 'selectOutput',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 1232.5,
          'posy': 681.25,
          'priority': 0,
          'user_application': None},
   19: {  'posx': 30.000000000000014,
          'posy': 279.99999999999994,
          'txt': 'Creates shapes'},
   20: {  'posx': 633.74999999999989, 'posy': 101.25, 'txt': 'L-System string'},
   21: {  'posx': 994.99999999999977,
          'posy': 673.74999999999989,
          'txt': 'Caribu'},
   22: {  'posx': 1078.7499999999998,
          'posy': 266.24999999999994,
          'txt': 'Position of plants on the scene'},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [  (0, 'PackageData(alinea.adel.wheat.data, So99.RData)'),
         (1, 'None'),
         (2, 'None')],
   3: [  (0, 'PackageData(alinea.adel.wheat.data, SRSo.RData)'),
         (1, 'None'),
         (2, 'None')],
   4: [(1, '7')],
   5: [],
   6: [],
   7: [],
   8: [],
   9: [],
   10: [],
   11: [],
   12: [(0, '1'), (1, '1')],
   13: [(0, '0')],
   14: [(0, '0')],
   15: [  (0, 'PackageData(alinea.adel.wheat.data, AleaStr190.txt)'),
          (1, 'None'),
          (2, 'None')],
   16: [(2, '0.20000000000000001')],
   17: [],
   18: [(1, "'Eabs'")],
   19: [],
   20: [],
   21: [],
   22: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             )




