#
#                Ce fichier : Core Code modèle ADEL(cinetique, ssi...) sous R
#
#                Doc input et exemples sont dans docAdel.R
#
#                macros Parametrisation et visu parametres sont dans setAdel.R
#
#                macros pour utilisation R,alea et python sont dans UseAdel.R
#
#
# disparition gaine a faire disp - ssi dd apres sa senescence
#
# accrocher la feuille axilante lors de l'inclinaison
#
# inclinaison talle : fonction a definir (debut a f1) par Mariem et a ajouter
#
#
# Linear interpolator/extrapolator
#
openapprox <- function(x,y,xout,extrapolate=TRUE) {
  xy <- cbind(x,y)
  xy <- xy[order(xy[,1]),]
  res <- approx(xy[,1],xy[,2],xout = xout,rule=2)$y
  last <- nrow(xy)
  twolast <- c(last - 1,last)
  if (extrapolate) {
    lastrate <- diff(xy[twolast,2]) / diff(xy[twolast,1])
    firstrate <- diff(xy[1:2,2]) / diff(xy[1:2,1])
  } else {
    lastrate <- 0
    firstrate <- 0
  }
  extrax <- xout > xy[last,1]
  res[extrax] <- xy[last,2] + lastrate * (xout[extrax] - xy[last,1])
  extrax <- xout < xy[1,1]
  res[extrax] <- xy[1,2] +  firstrate * (xout[extrax] - xy[1,1])
  res
}
#
#proportion Senesced as a function of Relative ssi and number from top
#
psen <- function(rssi,nt,ssisenT) {
  ndelsen <- max(ssisenT$ndel)
  ssisenT <- ssisenT[order(ssisenT$ndel),]
  t1delsen <- ssisenT$dssit1 - ssisenT$ndel
  t2delsen <- ssisenT$dssit2 - ssisenT$ndel
  senrate <- ssisenT$rate
  psen <- ifelse(rssi<=(-1),0,ifelse(rssi >= 1,1,rssi + 1))
  if (nt < ndelsen) {
    t0 <- (nt-ndelsen)
    t1 <- t1delsen[ndelsen-nt]
    t2 <- t2delsen[ndelsen-nt]
    psen <- openapprox(c(t0,t1,t2),c(0,senrate[ndelsen-nt]*(t1-t0),1),rssi,extrapolate=FALSE)
  }
  psen
}
                 
#
# kinL : Model for organ extension and leaf senescence
#
#
# TO DO : voir systeme avec HS "continu", et duree croissance leaf = 2 phyllos, et fin croissance = ligulation => Tip ne sera plus utilise
#
#
# Pb 2 : comme la gaine est sur l'arrondi de fin de croissance, dans le modele elle va trop vite (prolongement de la lineaire) : how to deal with that (concernerait surtout les 3 derniers ) ?
#
#
#plant are the parameters generated by setAdel
#
kinL <- function(x,plant,pars=list("startLeaf" = -0.4, "endLeaf" = 1.6, "stemLeaf" = 1.2)) {
  #Model parameter
  startLeaf <- pars$startLeaf
  endLeaf <- pars$endLeaf
  stemleaf <- pars$stemLeaf
  startE <- endLeaf
  endE <- startE + (endLeaf - startLeaf) / stemleaf
  #setting output
  naxe <- nrow(plant$axeT)
  nf <- plant$axeT$nf
  nx <- length(x)
  res <- vector("list",naxe)
  names(res) <- plant$axeT$axe
  #compute kinetic
  for (a in seq(naxe)) {
    xa <- x
    xend <- plant$axeT$end[a]
    if (!is.na(xend))
      xa[xa>=xend] <- xend
    ph <- openapprox(plant$pheno[[a]]$tip,plant$pheno[[a]]$n,xa)
    ssi <- openapprox(plant$pheno[[a]]$ssi,plant$pheno[[a]]$n,x)
    disp <- openapprox(plant$pheno[[a]]$disp,plant$pheno[[a]]$n,x)
    dim <- data.frame(plant$phytoT[,,a])
    ped <- plant$pedT[[a]]
    kin <- array(NA,c(nx,nf[a]+3,7),list(1:nx,1:(nf[a]+3),c("Ll","Gl","El","Llsen","Glsen","Elsen","ntop")))
    for (i in seq(nf[a])) {
      rph <- ph - i
      rssi <- ssi - i
#longueur blade+sheath
      LGl <- approx(c(startLeaf,endLeaf),c(0,dim$Ll[i]+dim$Gl[i]),xout=rph,rule=2)$y
      kin[,i,"Ll"] <- sapply(LGl,function(x) min(x,dim$Ll[i]))
      kin[,i,"Gl"] <- LGl - kin[,i,"Ll"]
      kin[,i,"El"] <- approx(c(startE,endE),c(0,dim$El[i]),xout=rph,rule=2)$y
      #sene
      kin[,i,"Llsen"] <- psen(rssi,nf[a]-i, plant$ssisenT) * kin[,i,"Ll"]
      kin[,i,"Glsen"] <- psen(rssi - 2,nf[a]-i, plant$ssisenT) * kin[,i,"Gl"]
      ## disparition feuille
      kin[i <= disp,i,c("Ll","Llsen")] <- 0
      kin[i <= (disp-1),i,c("Gl","Glsen")] <- 0
    }
    #ear + peduncle elongation
    nfa <- nf[a]
    for (i in (nfa+1):(nfa+3))
      kin[,i,c("Ll","Gl","Llsen","Glsen")] <- 0
    for (i in (nfa+2):(nfa+3))
      kin[,i,"El"] <- ifelse(ph < (nfa + 1.6),0,dim$El[i])
    if (dim$El[nfa+1] > 0)
      kin[,nfa+1,"El"] <- approx(c(ped$startPed,ped$endPed),c(0,dim$El[nfa+1]),xout=xa,rule=2)$y
    else
      kin[,nfa+1,"El"] = 0
    #senescence of stem + ear + awn + peduncle
    for (i in 1:(nfa+3))
      kin[,i,"Elsen"] <- ifelse(xa < ped$senPed,0,dim$El[i])
    ##disparition axe = longueurs nulles
    if (!is.na(plant$axeT$disp[a]))
      kin[x > plant$axeT$disp[a],,] <- 0
    #rang depuis flag leaf
    for (d in seq(along=x))
    kin[d,,"ntop"] <- -(seq(nrow(kin[d,,])) - nfa)
    res[[a]] <- kin
  }
  res
}
#
#compute rolling (to be done)  + visibilty
#
#hauteur du tube forme par les gaines d'un axe, a prtir des cinetiques de longeur.
#ht0 est la cinetique du tube dans lequel emerge la premiere feuille
#hauteur du tube = depuis la base de l'entreneoud, pour chaque phyto
#
htube <- function(kin,ht0) {
  if (dim(kin)[1] == 1) {
    stem <- matrix(cumsum(kin[,,"El"]),nrow=1)
  } else {
    stem <- t(apply(kin[,,"El"],1,cumsum))
  }
  hcol <- stem + kin[,,"Gl"]
  hcol <- cbind(matrix(ht0,ncol=1,nrow=nrow(hcol)),hcol)
  htube <- t(apply(hcol,1,function(hc) {
    res <- hc[-1]
    for (i in seq(along=res))
      res[i] <- max(hc[1:i])
    res
  }))
  htube - stem + kin[,,"El"]
}
#
#model: kinlist is the output of kinL
#
kinLvis <- function(kinlist,pars=NULL) {
  res <- kinlist
  for (a in seq(kinlist)) {
    kin <- kinlist[[a]]
    kinLv <- kin
    ht <- htube(kin,0)
    #calcul Lvis
    zero <- kin[,,1]
    if (length(dim(zero)) > 0)
      zero[,] <- 0
    else
      zero[] <- 0
    kinLv[,,"Ll"] <- pmin(pmax(zero,kin[,,"Ll"] + kin[,,"Gl"] + kin[,,"El"] - ht),kin[,,"Ll"])
    kinLv[,,"Gl"] <- pmin(pmax(zero,kin[,,"Gl"] + kin[,,"El"] - ht),kin[,,"Gl"])
    kinLv[,,"El"] <- pmin(pmax(zero,kin[,,"El"] - ht),kin[,,"El"])
    kinLv[,,"Llsen"] <- pmin(kinLv[,,"Ll"],kin[,,"Llsen"])
    kinLv[,,"Glsen"] <- pmin(kinLv[,,"Gl"],kin[,,"Glsen"])
    kinLv[,,"Elsen"] <- pmin(kinLv[,,"El"],kin[,,"Elsen"])
    res[[a]] <- kinLv
  }
  res
}
#
# Converting kinetics -> Canopy desc table

#generate desc table(s) for one plant at time t
getdesc <- function(kinlist,plantlist,pars=list("senescence_leaf_shrink" = 0.5,"epsillon" = 1e-6),t=1) {
  epsillon = pars$epsillon
  fshrink = pars$senescence_leaf_shrink
  res <- NULL
  for (p in seq(kinlist)) {
    kin <- kinlist[[p]]
    plant <- plantlist[[p]]
    pldesc <- NULL
    
    for (a in seq(kin)) {
      axename <- names(kin)[a]
      dat <- data.frame(kin[[a]][t,,c("Ll","Gl","El","Llsen","Glsen","Elsen")])
      if (sum(dat) > epsillon) {
        colnames(dat) <- c("Lv","Gv","Ev","Lsen","Gsen","Esen")
                                        #  infos brutes de plant parameters
        datp <- data.frame(plant$phytoT[,,axename])
        dataxe <- plant$axeT[plant$axeT$axe == as.numeric(axename),]
        nbleaf <- dataxe$nf
        nbphy <- nrow(dat)#inclus ear,ped et awn
        datp <- datp[1:nbphy,]
      # Calcul des inclinaisons de tiges
                                        # 1er phyto = entrenoeud a incT
        Einc <- rep(0,nbphy)
        Ginc <- rep(0,nbphy)
        incT <- dataxe$incT
        Einc[1] <- incT 
      # redressement (if any)
        if (dataxe$dredT > 0) {
          dincd <- incT / dataxe$dredT
          n <- 2
          while (incT > 0 & n <= nbphy) {
            lprec <- dat$Gv[n-1]
            d <- lprec * cos(incT * pi / 180)
            dinc <- min(d * dincd, incT)
            Einc[n] <- (-dinc)
            incT <- incT - dinc
            lprec <- dat$Ev[n]
            d <- lprec * cos(incT * pi / 180)
            dinc <- min(d * dincd, incT)
            Ginc[n] <- (-dinc)
            incT <- incT - dinc
            n <- n + 1
          }
        }

        #azimuts : Attention new 21 fev 2011 : azimuts en relatif / phytomere precedent !
        Laz <- datp$Azim
        Laz[1] <- dataxe$azT
        
        # control of blade basal inclination (to be moved in kinL?)
        Linc <- ifelse(datp$Ll > 0,dat$Lv / datp$Ll,1)
        # setup of Lindex (for Tino, no more needed) as a function of leaf stage
        #LcType <- plant$geoLeaf$Lindex(as.numeric(axename),seq(nbphy),nbleaf - seq(nbphy),dat$Lv/datp$Ll)
        #LcType <- plant$geoLeaf$Lindex(as.numeric(axename),seq(nbphy),nbleaf - seq(nbphy))
      #Epo
        Epo <- c(rep(1,nbleaf),3,3,3)
        Epos <- c(rep(2,nbleaf),4,4,4)
        pogreen <- rep(1,nbphy)
        posen <- rep(2,nbphy)
      #
        pldesc <- rbind(pldesc,
                        cbind(data.frame(
                                         axe=rep(as.numeric(axename),nbphy),
                                         numphy=1:nbphy,
                                         Ll=datp$Ll,
                                         Lw=datp$Lw,
                                         LsenShrink = fshrink,
                                         LcType=datp$Lindex,
                                         LcIndex=datp$Lseed,
                                         Linc=Linc,
                                         Laz=Laz,
                                         Lpo=pogreen,
                                         Lpos=posen,
                                         Gl=datp$Gl,
                                         Gd=datp$Gd,
                                         Ginc=Ginc,
                                         Gpo=pogreen,
                                         Gpos=posen,
                                         El=datp$Gl,
                                         Ed=datp$Ed,
                                         Einc=Einc,
                                         Epo=Epo,
                                         Epos=Epos),
                              dat))
      }
    }
    res <- rbind(res,cbind(plant=p,pldesc))
  }
  res
}
  
    

